#!/usr/bin/env bash
set -euo pipefail
#
# Useful probing examples:
#   CLASH95_FIRST_MISSION_MOVE_LEAVE_RUNNING=1 \
#     bash tests/run_first_mission_stack6_manual_probe.sh build/bin/clash95_bootstrap
#
#   CLASH95_STACK6_CHASE_MANUAL_TACTICAL_SEQUENCE="next-unit defence exit" \
#     bash tests/run_first_mission_stack6_manual_probe.sh build/bin/clash95_bootstrap
#
#   CLASH95_STACK6_CHASE_MANUAL_TACTICAL_SEQUENCE="wait,20 battle-click,577,386,battle_action_next_unit_selected,12,6,1.0 defence" \
#     bash tests/run_first_mission_stack6_manual_probe.sh build/bin/clash95_bootstrap
#
#   CLASH95_STACK6_CHASE_MANUAL_TACTICAL_SEQUENCE_FILE=/tmp/stack6-sequence.txt \
#     bash tests/run_first_mission_stack6_manual_probe.sh build/bin/clash95_bootstrap
#
#   CLASH95_STACK6_CHASE_MANUAL_BATTLE_SCRIPT_FILE=tests/stack6_manual_battle_script.example \
#   CLASH95_FIRST_MISSION_MOVE_EXPECT_LOGS_FILE=tests/stack6_manual_expected_logs.example \
#     bash tests/run_first_mission_stack6_manual_probe.sh build/bin/clash95_bootstrap
#
# Sequence token forms:
#   wait,reads,gap
#   key,scan_code,reads,expected_pattern,timeout,gap
#   battle-click,x,y,expected_pattern,timeout,reads,gap
#   pulse,dx,dy,expected_pattern,timeout,left,right,reads,gap
#   next-unit | defence | shoot | charge | retreat | exit
# Keep expected_pattern to a single shell word here. For patterns containing
# spaces, use CLASH95_STACK6_CHASE_MANUAL_BATTLE_EXPECT_PATTERN instead.
#
# For lower-level battle input, pass CLASH95_STACK6_CHASE_MANUAL_BATTLE_SCRIPT
# or CLASH95_STACK6_CHASE_MANUAL_BATTLE_SCRIPT_FILE. Those commands are appended
# to CLASH95_BATTLE_INPUT_SCRIPT after the recovered battle loop is reached.

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <path-to-clash95_bootstrap> [verify-args...]" >&2
  exit 2
fi

export CLASH95_ENABLE_REAL_INPUT_SMOKES="${CLASH95_ENABLE_REAL_INPUT_SMOKES:-1}"
export CLASH95_TRACE_WORLD_CLICK="${CLASH95_TRACE_WORLD_CLICK:-1}"
export CLASH95_KEEP_SMOKE_ARTIFACTS="${CLASH95_KEEP_SMOKE_ARTIFACTS:-1}"
export CLASH95_SMOKE_FAIL_TAIL_LINES="${CLASH95_SMOKE_FAIL_TAIL_LINES:-240}"
export CLASH95_DUMP_PRESENTED_FRAMES_RESET_ON_BATTLE_ENTER="${CLASH95_DUMP_PRESENTED_FRAMES_RESET_ON_BATTLE_ENTER:-1}"
export CLASH95_BATTLE_SAFE_CURSOR_ON_TURN_LOOP="${CLASH95_BATTLE_SAFE_CURSOR_ON_TURN_LOOP:-1}"

export CLASH95_FIRST_MISSION_MOVE_END_TURN="${CLASH95_FIRST_MISSION_MOVE_END_TURN:-1}"
export CLASH95_CLICK_END_TURN_X="${CLASH95_CLICK_END_TURN_X:-500}"
export CLASH95_CLICK_END_TURN_Y="${CLASH95_CLICK_END_TURN_Y:-2}"
export CLASH95_CLICK_END_TURN_HOLD="${CLASH95_CLICK_END_TURN_HOLD:-0.25}"
export CLASH95_CLICK_END_TURN_GAP="${CLASH95_CLICK_END_TURN_GAP:-2.0}"
export CLASH95_FIRST_MISSION_MOVE_POST_END_TURN_SKIPS="${CLASH95_FIRST_MISSION_MOVE_POST_END_TURN_SKIPS:-2}"
export CLASH95_CLICK_POST_END_TURN_SKIP_GAP="${CLASH95_CLICK_POST_END_TURN_SKIP_GAP:-0.8}"

export CLASH95_FIRST_MISSION_MOVE_THIRD_ACTION="${CLASH95_FIRST_MISSION_MOVE_THIRD_ACTION:-1}"
export CLASH95_THIRD_ACTION_WAIT_FOR_SELECT="${CLASH95_THIRD_ACTION_WAIT_FOR_SELECT:-0}"
export CLASH95_FIRST_MISSION_MOVE_FOURTH_ACTION="${CLASH95_FIRST_MISSION_MOVE_FOURTH_ACTION:-1}"
export CLASH95_FOURTH_ACTION_WAIT_FOR_SELECT="${CLASH95_FOURTH_ACTION_WAIT_FOR_SELECT:-0}"
export CLASH95_FOURTH_ACTION_CLICK_BATTLE_PROMPT="${CLASH95_FOURTH_ACTION_CLICK_BATTLE_PROMPT:-1}"
export CLASH95_FOURTH_ACTION_BATTLE_RESULT_TIMEOUT="${CLASH95_FOURTH_ACTION_BATTLE_RESULT_TIMEOUT:-30}"
export CLASH95_FOURTH_ACTION_WAIT_FOR_ATTACK_RETURN="${CLASH95_FOURTH_ACTION_WAIT_FOR_ATTACK_RETURN:-1}"

export CLASH95_FIRST_MISSION_MOVE_FIFTH_ACTION="${CLASH95_FIRST_MISSION_MOVE_FIFTH_ACTION:-0}"
export CLASH95_FIRST_MISSION_MOVE_SIXTH_ACTION="${CLASH95_FIRST_MISSION_MOVE_SIXTH_ACTION:-0}"
export CLASH95_FIRST_MISSION_MOVE_SEVENTH_ACTION="${CLASH95_FIRST_MISSION_MOVE_SEVENTH_ACTION:-0}"

export CLASH95_FIRST_MISSION_STACK4_CHASE_REPEATS="${CLASH95_FIRST_MISSION_STACK4_CHASE_REPEATS:-8}"
export CLASH95_FIRST_MISSION_STACK5_PROBE="${CLASH95_FIRST_MISSION_STACK5_PROBE:-1}"
export CLASH95_FIRST_MISSION_STACK5_CHASE_REPEATS="${CLASH95_FIRST_MISSION_STACK5_CHASE_REPEATS:-5}"
export CLASH95_FIRST_MISSION_STACK6_CHASE_REPEATS="${CLASH95_FIRST_MISSION_STACK6_CHASE_REPEATS:-5}"
export CLASH95_STACK6_CHASE_WAIT_FOR_OBJECTIVE_ADVANCE="${CLASH95_STACK6_CHASE_WAIT_FOR_OBJECTIVE_ADVANCE:-0}"
export CLASH95_STACK6_CHASE_MANUAL_BATTLE_MILESTONE="${CLASH95_STACK6_CHASE_MANUAL_BATTLE_MILESTONE:-1}"
export CLASH95_STACK6_CHASE_MANUAL_BATTLE_TIMEOUT="${CLASH95_STACK6_CHASE_MANUAL_BATTLE_TIMEOUT:-35}"

if [ "${CLASH95_STACK6_CHASE_MANUAL_TACTICAL_SEQUENCE:-}" ] || \
  [ "${CLASH95_STACK6_CHASE_MANUAL_TACTICAL_SEQUENCE_FILE:-}" ] || \
  [ "${CLASH95_STACK6_CHASE_MANUAL_BATTLE_SCRIPT:-}" ] || \
  [ "${CLASH95_STACK6_CHASE_MANUAL_BATTLE_SCRIPT_FILE:-}" ]; then
  export CLASH95_STACK6_CHASE_MANUAL_TACTICAL_ACTION="${CLASH95_STACK6_CHASE_MANUAL_TACTICAL_ACTION:-0}"
else
  export CLASH95_STACK6_CHASE_MANUAL_TACTICAL_ACTION="${CLASH95_STACK6_CHASE_MANUAL_TACTICAL_ACTION:-1}"
fi
export CLASH95_STACK6_CHASE_MANUAL_TACTICAL_EXIT="${CLASH95_STACK6_CHASE_MANUAL_TACTICAL_EXIT:-0}"
export CLASH95_STACK6_CHASE_TACTICAL_NEXT_UNIT_TIMEOUT="${CLASH95_STACK6_CHASE_TACTICAL_NEXT_UNIT_TIMEOUT:-12}"
export CLASH95_STACK6_CHASE_TACTICAL_DEFENCE_TIMEOUT="${CLASH95_STACK6_CHASE_TACTICAL_DEFENCE_TIMEOUT:-12}"

export CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES:-1}"
export CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES:-0}"
export CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET="${CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET:-route,world-click,playable-turn,end-turn,post-end-turn,turn-advance,stack6-manual}"
export CLASH95_FIRST_MISSION_MOVE_TIMEOUT_SECONDS="${CLASH95_FIRST_MISSION_MOVE_TIMEOUT_SECONDS:-900}"
export CLASH95_FIRST_MISSION_MOVE_LEAVE_RUNNING="${CLASH95_FIRST_MISSION_MOVE_LEAVE_RUNNING:-0}"
if [ "${CLASH95_FIRST_MISSION_MOVE_LEAVE_RUNNING:-0}" = "1" ]; then
  export CLASH95_FIRST_MISSION_MOVE_LEAVE_RUNNING_EXPECT_PATTERN="${CLASH95_FIRST_MISSION_MOVE_LEAVE_RUNNING_EXPECT_PATTERN:-manual battle input loop reached}"
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec bash "$repo_root/tests/verify_first_mission_real_input_move_smoke.sh" "$@"
