#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 /path/to/clash95_bootstrap" >&2
  exit 2
fi

if [ "${CLASH95_ENABLE_FIRST_MISSION_TURN_PROBE:-0}" != "1" ]; then
  echo "first-mission turn probe skipped; set CLASH95_ENABLE_FIRST_MISSION_TURN_PROBE=1 to run" >&2
  exit 77
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export CLASH95_ENABLE_REAL_INPUT_SMOKES="${CLASH95_ENABLE_REAL_INPUT_SMOKES:-1}"
export CLASH95_TRACE_WORLD_CLICK="${CLASH95_TRACE_WORLD_CLICK:-1}"
export CLASH95_TRACE_HOST_CLICK_PULSES="${CLASH95_TRACE_HOST_CLICK_PULSES:-1}"
export CLASH95_FIRST_MISSION_MOVE_PRE_ROUTE_WAIT="${CLASH95_FIRST_MISSION_MOVE_PRE_ROUTE_WAIT:-1.0}"
export CLASH95_FIRST_MISSION_MOVE_SKIP_COUNT="${CLASH95_FIRST_MISSION_MOVE_SKIP_COUNT:-6}"
export CLASH95_FIRST_MISSION_MOVE_AFTER_SKIP_WAIT="${CLASH95_FIRST_MISSION_MOVE_AFTER_SKIP_WAIT:-0.2}"
export CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET="${CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET:-route,world-click,playable-turn,end-turn,post-end-turn}"
export CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES:-1}"
export CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES:-1}"
export CLASH95_FIRST_MISSION_MOVE_SECOND_ACTION="${CLASH95_FIRST_MISSION_MOVE_SECOND_ACTION:-1}"
export CLASH95_FIRST_MISSION_MOVE_END_TURN="${CLASH95_FIRST_MISSION_MOVE_END_TURN:-1}"
export CLASH95_FIRST_MISSION_MOVE_END_TURN_KEY="${CLASH95_FIRST_MISSION_MOVE_END_TURN_KEY:-}"
export CLASH95_FIRST_MISSION_MOVE_POST_END_TURN_SKIPS="${CLASH95_FIRST_MISSION_MOVE_POST_END_TURN_SKIPS:-4}"
export CLASH95_FIRST_MISSION_MOVE_TIMEOUT_SECONDS="${CLASH95_FIRST_MISSION_MOVE_TIMEOUT_SECONDS:-105}"
export CLASH95_KEEP_SMOKE_ARTIFACTS="${CLASH95_KEEP_SMOKE_ARTIFACTS:-1}"

exec bash "${script_dir}/verify_first_mission_real_input_move_smoke.sh" "$1"
