#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 /path/to/clash95_bootstrap" >&2
  exit 2
fi

export CLASH95_ENABLE_REAL_INPUT_SMOKES="${CLASH95_ENABLE_REAL_INPUT_SMOKES:-1}"
export CLASH95_TRACE_WORLD_CLICK="${CLASH95_TRACE_WORLD_CLICK:-1}"
export CLASH95_FIRST_MISSION_MOVE_PRE_ROUTE_WAIT="${CLASH95_FIRST_MISSION_MOVE_PRE_ROUTE_WAIT:-1.0}"
export CLASH95_FIRST_MISSION_MOVE_SKIP_COUNT="${CLASH95_FIRST_MISSION_MOVE_SKIP_COUNT:-6}"
export CLASH95_FIRST_MISSION_MOVE_AFTER_SKIP_WAIT="${CLASH95_FIRST_MISSION_MOVE_AFTER_SKIP_WAIT:-0.2}"
export CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET="${CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET:-route,world-click,playable-turn}"
export CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES:-1}"
export CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES:-1}"
export CLASH95_KEEP_SMOKE_ARTIFACTS="${CLASH95_KEEP_SMOKE_ARTIFACTS:-1}"

exec bash "$(dirname "$0")/verify_first_mission_real_input_move_smoke.sh" "$1"
