#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 /path/to/clash95_bootstrap" >&2
  exit 2
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export CLASH95_ENABLE_REAL_INPUT_SMOKES="${CLASH95_ENABLE_REAL_INPUT_SMOKES:-1}"
export CLASH95_TRACE_WORLD_CLICK="${CLASH95_TRACE_WORLD_CLICK:-1}"
export CLASH95_TRACE_HOST_CLICK_PULSES="${CLASH95_TRACE_HOST_CLICK_PULSES:-0}"
export CLASH95_FIRST_MISSION_MOVE_PRE_ROUTE_WAIT="${CLASH95_FIRST_MISSION_MOVE_PRE_ROUTE_WAIT:-1.0}"
export CLASH95_FIRST_MISSION_MOVE_SKIP_COUNT="${CLASH95_FIRST_MISSION_MOVE_SKIP_COUNT:-6}"
export CLASH95_FIRST_MISSION_MOVE_AFTER_SKIP_WAIT="${CLASH95_FIRST_MISSION_MOVE_AFTER_SKIP_WAIT:-0.2}"
export CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET="${CLASH95_FIRST_MISSION_MOVE_EXPECT_PRESET:-route,world-click,playable-turn}"
export CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REQUIRE_FRAMES:-1}"
export CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES="${CLASH95_FIRST_MISSION_MOVE_REJECT_BLANK_FRAMES:-1}"
export CLASH95_FIRST_MISSION_MOVE_SECOND_ACTION="${CLASH95_FIRST_MISSION_MOVE_SECOND_ACTION:-1}"
export CLASH95_SECOND_ACTION_CLICK_NEXT_UNIT="${CLASH95_SECOND_ACTION_CLICK_NEXT_UNIT:-1}"
export CLASH95_SECOND_ACTION_WAIT_FOR_NEXT_UNIT="${CLASH95_SECOND_ACTION_WAIT_FOR_NEXT_UNIT:-1}"
export CLASH95_SECOND_ACTION_NEXT_UNIT_PATTERN="${CLASH95_SECOND_ACTION_NEXT_UNIT_PATTERN:-next_unit_selected selected=2 a=32 b=44}"
export CLASH95_SECOND_ACTION_CLICK_UNIT_SLOT="${CLASH95_SECOND_ACTION_CLICK_UNIT_SLOT:-1}"
export CLASH95_CLICK_SECOND_UNIT_SLOT_X="${CLASH95_CLICK_SECOND_UNIT_SLOT_X:-569}"
export CLASH95_CLICK_SECOND_UNIT_SLOT_Y="${CLASH95_CLICK_SECOND_UNIT_SLOT_Y:-187}"
export CLASH95_CLICK_SECOND_MOVE_TARGET_X="${CLASH95_CLICK_SECOND_MOVE_TARGET_X:-384}"
export CLASH95_CLICK_SECOND_MOVE_TARGET_Y="${CLASH95_CLICK_SECOND_MOVE_TARGET_Y:-368}"
export CLASH95_CLICK_SECOND_MOVE_TARGET_HOLD="${CLASH95_CLICK_SECOND_MOVE_TARGET_HOLD:-0.85}"
export CLASH95_CLICK_SECOND_MOVE_TARGET_GAP="${CLASH95_CLICK_SECOND_MOVE_TARGET_GAP:-4.0}"
export CLASH95_FIRST_MISSION_MOVE_WAIT_FOR_ENEMY_ATTACK="${CLASH95_FIRST_MISSION_MOVE_WAIT_FOR_ENEMY_ATTACK:-1}"
export CLASH95_FIRST_MISSION_MOVE_ENEMY_ATTACK_PATTERN="${CLASH95_FIRST_MISSION_MOVE_ENEMY_ATTACK_PATTERN:-enemy_attack_call selected=2 a=3 b=46 c=45}"
export CLASH95_FIRST_MISSION_MOVE_ENEMY_ATTACK_RETRY_COUNT="${CLASH95_FIRST_MISSION_MOVE_ENEMY_ATTACK_RETRY_COUNT:-3}"
export CLASH95_SECOND_ACTION_CLICK_BATTLE_PROMPT="${CLASH95_SECOND_ACTION_CLICK_BATTLE_PROMPT:-1}"
export CLASH95_SECOND_ACTION_BATTLE_RESULT_PATTERN="${CLASH95_SECOND_ACTION_BATTLE_RESULT_PATTERN:-unit_attack_autoresolve_done selected=2 a=3}"
export CLASH95_SECOND_ACTION_BATTLE_RETURN_PATTERN="${CLASH95_SECOND_ACTION_BATTLE_RETURN_PATTERN:-unit_attack_autoresolve_return selected=2 a=3}"
if [ -z "${CLASH95_FIRST_MISSION_MOVE_EXPECT_LOGS+x}" ]; then
  export CLASH95_FIRST_MISSION_MOVE_EXPECT_LOGS=$'enemy_attack_call selected=2 a=3 b=46 c=45\nunit_attack_enter selected=2 a=3 b=46 c=45\nunit_attack_track selected=2 a=3 b=46 c=45\nunit_attack_after_track selected=2 a=3 b=45 c=45\nunit_attack_autoresolve_done selected=2 a=3\nunit_attack_autoresolve_return selected=2 a=3'
fi
export CLASH95_FIRST_MISSION_MOVE_END_TURN="${CLASH95_FIRST_MISSION_MOVE_END_TURN:-0}"
export CLASH95_FIRST_MISSION_MOVE_TIMEOUT_SECONDS="${CLASH95_FIRST_MISSION_MOVE_TIMEOUT_SECONDS:-105}"
export CLASH95_KEEP_SMOKE_ARTIFACTS="${CLASH95_KEEP_SMOKE_ARTIFACTS:-1}"

exec bash "${script_dir}/verify_first_mission_real_input_move_smoke.sh" "$1"
