/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'battle' (59); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_BATTLE_SHARED_STATE_H
#define CLASH95_BATTLE_SHARED_STATE_H

#include "../recovered_types.h"

extern int Map_NeighborDX[64];
extern int Map_NeighborDY[63];
extern char a1[3];
extern char a2[3];
extern int g_ActiveCursorDescriptor;
extern int g_ActiveCursorDescriptorPtr;
extern int g_ActiveUiSpriteSet;
extern int g_ActiveUnitAnimSpriteSet;
extern int g_ActiveUnitMoveTileIndex;
extern int g_AttackerStartsOnLeft;
extern int g_BattleButtonsSpriteSet;
extern int g_BattleShotAnimFrameIndex;
extern int g_BattleTargetTileCol;
extern int g_BattleWallGateLastSpriteChar;
extern int g_Battle_ShootModeEnabled;
extern int g_BuildingGarrisonDialogActiveBuilding;
extern int g_BuildingGarrisonDialogPendingExitCountdown;
extern int g_BuildingGarrisonDialogResourceHandle;
extern int g_BuildingGarrisonDialogSelectedSlotIndex;
extern int g_BuildingGarrisonDialogSelectedSlots[12];
extern int g_BuildingGarrisonDialogSelectedUnitSpriteSet;
extern int g_BuildingGarrisonDialogSlotAnimFrames[12];
extern int g_BuildingGarrisonDialogSlotSpriteSets[12];
extern int g_BuildingGarrisonDialogUiSpriteSet;
extern int g_CurrentPlayerIndex;
extern char g_CursorCoordShift;
extern int g_CursorDesc_ActionBusy[10];
extern int g_CursorDesc_Attack[10];
extern int g_CursorDesc_Default[10];
extern int g_CursorOverlayPresented;
extern int g_DefenderStartsOnLeft;
extern int g_GarrisonUnitCellSurface;
extern char g_LanguageIndex;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_MapData;
extern int g_MapPalettePtr;
extern int g_MarksSpriteSet;
extern int g_PrimaryRenderSurface;
extern _UNKNOWN *g_RenderDevice;
extern int (*g_RenderHook)(int a1, char a2, DWORD a3);
extern _DWORD g_RenderState[286];
extern int g_SelectedUnitIndex;
extern char g_TilePassabilityMask[1023];
extern int g_UnitAnimFrameIndex;
extern _BYTE g_UnitBattleActionWidgetTable[WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * (UNIT_BATTLE_ACTION_WIDGET_COUNT + 1)] __attribute__((aligned(4)));
extern int g_UnitBattleAnimFrameCount;
extern int g_UnitBattleAnimatingUnitIndex;
extern int g_UnitBattleAnimatingUnitSpriteSet;
extern int g_UnitBattleChargeModeActive_532060;
extern int g_UnitBattleHitAnimFrame;
extern int g_UnitBattleProjectileSpriteSet;
extern int g_UnitBattleShotProjectileTileX;
extern int g_UnitBattleShotProjectileTileY;
extern int g_UnitFadeAnimCurrentOffset;
extern int g_UnitMoveAnimOffsetX;
extern int g_UnitMoveAnimOffsetY;
extern CLASH95_INTERNAL const UnitTypeRuntimeCoreMetadataRecord g_UnitTypeRuntimeCoreMetadata[UNIT_TYPE_METADATA_CAPACITY];
extern int g_WorldMapBackgroundSpriteSet;
extern int gameData;

#endif /* CLASH95_BATTLE_SHARED_STATE_H */
