/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* State-TU globals whose only consuming subsystem is 'battle' (84). */
#ifndef CLASH95_BATTLE_STATE_H
#define CLASH95_BATTLE_STATE_H

#include "../recovered_types.h"

extern char aBattleActiveTi[35];
extern char aBattleBat_bkg1[20];
extern char aBattleBat_bkg2[20];
extern char aBattleBat_bkg3[20];
extern char aBattleButtons_[19];
extern char aBattleFr_anim_[20];
extern char aBattleFrame_s3[18];
extern char aBattleSzarza[14];
extern char aBattleTrupki_s[19];
extern char aBattle_0[10];
extern char aBattle_1[7];
extern char aBattle_placeun[34];
extern char aD_34[3];
extern char aD_35[3];
extern char aD_48[3];
extern char aD_49[3];
extern char aD_50[3];
extern char aD_51[3];
extern char aD_52[3];
extern char aD_53[3];
extern char aD_54[3];
extern char aD_55[3];
extern char aD_56[3];
extern char aD_57[3];
extern char aD_58[3];
extern char aD_59[3];
extern char aD_60[3];
extern char aD_61[3];
extern char aD_62[3];
extern char aD_63[3];
extern char aD_64[3];
extern char aD_65[3];
extern char aD_66[3];
extern char aD_67[3];
extern char aEndOfBattle[14];
extern char aHandlebattle_0[32];
extern char aHandlebattlere[42];
extern char aMainmap_3[8];
extern char aNewBattle_0[19];
extern char aNotEnoughMe_10[21];
extern char aNotEnoughMem_9[21];
extern char aSetrhS08x_8[14];
extern char aSetrhS08x_9[14];
extern char aStart_0[6];
extern char aUnsetrh08x_8[13];
extern char aUnsetrh08x_9[13];
extern int g_BattleCasualtySpriteSet;
extern char *g_BattleForcedRetreatOutcomeTexts[3];
extern int g_BattleHudSprites;
extern int g_BattleLoopExitCode;
extern int g_BattlePanelUnitFatiguePercent;
extern char g_BattleSavedActionPointsBySlot[24];
extern _BYTE g_BattleUnitOrderBitsBackup[92];
extern int g_BattleUnitPanelIconSpriteSet;
extern char *g_BattleYourTurnBannerTexts[6];
extern int g_BuildingGarrisonDialogExitCountdownLastTickMs;
extern int g_BuildingGarrisonDialogSelectedUnitAnimFrame;
extern int g_BuildingGarrisonDialogSelectedUnitAnimLastTickMs;
extern int g_CursorDesc_Blocked[10];
extern _UNKNOWN g_GarrisonDialogExitScratch;
extern int g_UnitActionTooltipLastShownAction;
extern char *g_UnitActionTooltipTexts[24];
extern int g_UnitBattleActionLoopExitRequested;
extern int g_UnitBattleChargeModeStartTick_532074;
extern char g_UnitBattlePanelAttackIconChar;
extern char g_UnitBattlePanelDefenseIconChar;
extern char g_UnitBattlePanelMoraleIconChar;
extern char g_UnitBattlePanelQuantityIconCharBase[1];
extern char g_UnitBattlePanelStatAnimCounters[];
extern __int16 g_UnitBattlePanelStatIconX[1];
extern __int16 g_UnitBattlePanelStatIconY[1];
extern char g_UnitBattlePanelVolleyIconChar;
extern char *g_UnitBattlePlayerLabelStrings[3];
extern _UNKNOWN g_UnitBattlePlayerPromptDialogTemplate;
extern char *g_UnitBattlePlayerPromptLabelStrings[2];
extern char *g_UnitBattlePrepareDefenceMessageStrings[3];
extern int g_UnitBattlePromptDialogResult;
extern char *g_UnitBattleRetreatMessageStrings[6];
extern int g_UnitFadeAnimLastUpdateTime;
extern int g_UnitFadeAnimStepRate;
extern int g_UnitFadeAnimTargetOffset;
extern int g_UnitFadeAnimUnitIndex;
extern char g_UnitPanelRow3FallbackIconChar;
extern char *g_WallInfoPopupLabelTexts[2];

#endif /* CLASH95_BATTLE_STATE_H */
