/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Home-only functions of 'battle' (20); private to the subsystem. */
#ifndef CLASH95_BATTLE_INTERNAL_H
#define CLASH95_BATTLE_INTERNAL_H

#include "battle_api.h"

__int16 UnitBattle_HandleBattlefieldInteraction(void);
int UnitBattle_RefreshSelectedActionButtons(void);
int  UnitBattleDialog_SelectAffirmativeResponse(int widget, int unitIndex);
int  UnitBattleDialog_SelectNegativeResponse(int widget, int unitIndex);
int  UnitBattle_ShowCurrentPlayerPromptDialog(int messageStrings, char spriteName, DWORD a3);
int  UnitBattle_AnimateSelectedUnitPanel(int aiMode, int a2, int a3);
__int16  UnitBattle_UpdateActionTooltip(char a1, int a2, int a3);
signed int  UnitBattle_RunTurnLoop(int a1, DWORD a2);
void  HandleBattleResults(int attackerFormation, int defenderFormation, int a3, unsigned __int8 *buildingRecord, DWORD battleOutcome);
int  UnitBattle_OverrideControllerOrderBits(int playerAIndex, int overrideA, int overrideB, int playerBIndex);
int UnitBattle_RestoreControllerOrderBits(void);
int *UnitBattle_InitBattleScreenFrame(void);
int  UnitBattle_DrawUnitSprite(int unitIndex, int screenX, int screenY, int yOffset);
int  UnitBattle_DrawMovingUnitInAdjacentTile(int result, int tileCol, int screenY, int screenX);
int  UnitBattle_DrawTileContents(int tileRow, int tileCol);
int  UnitBattle_ShowWallInfoPopup(int popupX, int popupY, int a3, int spriteName, DWORD a5);
int  BuildingGarrisonDialog_HandleExitButtonPress(int widget, int unitIndex);
__int16  Battle_PlaceReservedUnitSlotAtTile(int unitRecord, int tileRow, int tileCol);
int Battle_ClearReservedUnitSlot(void);
signed int Battle_RestoreSavedActionPointsBeforeResultCopy(void);

#endif /* CLASH95_BATTLE_INTERNAL_H */
