/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'battle': functions defined here and referenced from another subsystem (31). */
#ifndef CLASH95_BATTLE_API_H
#define CLASH95_BATTLE_API_H

#include "../recovered_types.h"

__int16 UnitBattle_EnableSelectedChargeMode(void);
__int16 UnitBattle_RefreshSelectedUnitUI(void);
int  UnitBattle_SelectNextControllableUnit(int widget, int a2, char a3);
int UnitBattle_ToggleSelectedShootingMode(uintptr_t widget, int a2, DWORD a3, char a4, double a5);
int  UnitBattle_HandleRetreatAction(int widget, int unitIndex, char promptSpriteName, DWORD a4);
int UnitBattle_ToggleSelectedChargeMode(uintptr_t widget, int a2, DWORD a3, char a4, double a5);
int  UnitBattle_HandlePrepareDefenceAction(int widget, int a2, DWORD a3, char a4, char a5);
int UnitBattle_RequestActionLoopExit(uintptr_t widget, int a2, DWORD a3, char a4, double a5);
int  UnitBattle_ShowPlayerMessageBanner(int messageText, int playerIndex, int doFlipWait, DWORD a4);
void  HandleBattleResults(int attackerFormation, int defenderFormation, int a3, unsigned __int8 *buildingRecord, DWORD battleOutcome);
int UnitBattle_TemporarilyClearGateBlocker(void);
char UnitBattle_RestoreGateBlocker(void);
DWORD  Battle_RunTacticalCombat(__int16 *attackerGroupArg, __int16 *defenderGroupArg, int attackerControlArg, unsigned __int8 *buildingRecordArg, DWORD logCtx, int defenderControlFlag);
int  UnitBattle_GetSpriteVerticalOffsetPx(int unitIndex);
int  UnitBattle_InitUnitFadeAnimation(int unitIndex, int startOffset, int stepRate, int targetOffset);
int  UnitBattle_RedrawTile(int tileRow, int tileCol);
int UnitBattle_RedrawVisibleGrid(void);
int  UnitBattle_DrawSelectedUnitPanel(int result, int restoreFlag, int a3, int a4);
__int16 UnitBattle_UpdateIdleAnimatedUnits(void);
__int16  UnitBattle_RedrawUnitFootprint(int unitIndex);
unsigned int  UnitBattle_RedrawUnitNeighborhood(int unitIndex);
signed int  Battle_PlaceUnit(unsigned __int8 *unitRecord, int tileRow, char facing, int tileCol);
int BuildingGarrisonDialog_CountSelectedSlots(void);
void * BuildingGarrisonDialog_DrawSlotGrid(int targetSlot);
int  BuildingGarrisonDialog_ReloadSlotSprite(int result, int a2, int a3, DWORD a4);
void * BuildingGarrisonDialog_RebuildSlotSprites(int a1, DWORD a2);
void * BuildingGarrisonDialog_TickExitCountdown(int a1, double a2);
void *BuildingGarrisonDialog_DrawSelectedUnitPanel(void);
void  BuildingGarrisonDialog_RebuildSelectedUnitPanelAssets(int a1, char a2, DWORD a3);
void *__thiscall BuildingGarrisonDialog_AnimateSelectedUnit(void *this);
int BuildingGarrisonDialog_HitTestSlotGrid(void);

#endif /* CLASH95_BATTLE_API_H */
