/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/strategic/004589C0_004602F0_strategic_004.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_004589C0_004602F0_STRATEGIC_004_LOCAL_H
#define CLASH95_TU_004589C0_004602F0_STRATEGIC_004_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE void Mission_TraceObjectiveBlocked (int mission_index, int detail_a, int detail_b, int detail_c) CLASH95_LOCAL_SYMBOL(Mission_TraceObjectiveBlocked);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_004589C0_004602F0_STRATEGIC_004_LOCAL_H */
