/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/strategic/00460950_004612E0_strategic_006.cpp' (2); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00460950_004612E0_STRATEGIC_006_LOCAL_H
#define CLASH95_TU_00460950_004612E0_STRATEGIC_006_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE uintptr_t Compat_RenderStateMethodPointer (int render_state, unsigned int table_offset) CLASH95_LOCAL_SYMBOL(Compat_RenderStateMethodPointer);
CLASH95_LOCAL int Compat_RenderClearPresentedRect(int render_state) CLASH95_LOCAL_SYMBOL(Compat_RenderClearPresentedRect);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00460950_004612E0_STRATEGIC_006_LOCAL_H */
