/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/strategic/00460360_00460910_strategic_005.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00460360_00460910_STRATEGIC_005_LOCAL_H
#define CLASH95_TU_00460360_00460910_STRATEGIC_005_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE int Compat_MenuProbeTraceEnabled (void) CLASH95_LOCAL_SYMBOL(Compat_MenuProbeTraceEnabled);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00460360_00460910_STRATEGIC_005_LOCAL_H */
