/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'strategic': functions defined here and referenced from another subsystem (70). */
#ifndef CLASH95_STRATEGIC_API_H
#define CLASH95_STRATEGIC_API_H

#include "../recovered_types.h"

int  Queen_NewTurn(int, int, char, double);
int  Player_Surrender(int player_index, int a2, DWORD a3, double a4);
int  AI_ComputeNationStrengthPercent(signed int player_index, int a2, DWORD a3, double a4);
int  Player_CheckForDefeatAndHandleElimination(int player_index, DWORD a2);
signed int  UI_CheckEndTurnHotkey(int player_index);
void Cheat_FillSelectedSquadWithCannons(void);
int  UI_ReadCheatString(char a1);
signed int Rules_ShowBanner_StrategicClash(void);
int Rules_ResetEngineOnLoad(void);
signed int Rules_RegisterAllHostFunctions(void);
int Rules_LogMissionSetupInfo(void);
signed int Rules_ExecuteAITurn(void);
_DWORD * Rules_RetractArmyFact(_DWORD *result, int a2, int a3, double a4);
signed int  Rules_LinkArmyFact(__int16 *stack, int army_id, int a3, double a4, char a5, DWORD a6);
signed int  Rules_SyncArmyFactStrength(__int16 *army_stack, int army_id, int a3, char a4, DWORD a5, double a6);
signed int  Rules_SyncArmyFactOwner(__int16 *stack_record, char a2, DWORD a3, double a4);
signed int  Rules_SyncCastleFactOwner(int castle_record, int a2, double a3);
_DWORD * Rules_LogTrapFact(int tile_x, int tile_y);
_DWORD * Rules_RetractTrapFact(int tile_x, int tile_y);
_DWORD * Rules_LogTempleFact(int tile_x, int tile_y);
_DWORD * Rules_LogTreasureFact(int tile_x, int tile_y);
_DWORD * Rules_RetractTempleFact(int tile_x, int tile_y, char a3, DWORD a4);
int  Rules_AssertCastleFact(unsigned __int8 *castle_record, int building_index);
_DWORD * Rules_RetractCastleFact(unsigned __int8 *castle_record, double a2);
_DWORD * Rules_LogCastleSiteFact(int tile_x, int tile_y);
_DWORD * Rules_LogBuildingTransferFact(int a1, int a2, int a3);
_DWORD * Rules_LogNewCastleFact(int a1, int a2);
_DWORD * Rules_LogBuildingCapturedFact(int a1, int a2, int a3);
_DWORD * Rules_LogCastleUnderConstructionFact(int castle_id);
_DWORD *__fastcall Rules_LogCastleBuiltFactAndScheme(int a1, int castle_id);
int  Building_OnGarrisonChange(int building_index, int instance_record, double a3);
signed int  createUnit(double a1, int tile_x, int tile_y, int player_index, unit_type first_unit_type, unit_type second_unit_type, ...);
int  createCastle(double st7_0, int tile_x, int tile_y, int player_index, int building_type, char *castle_name, unit_type first_unit_type, unit_type second_unit_type, ...);
int  WorldMap_DrawMission01ShrineMarker(int result, int tile_y, int screen_y, int screen_x);
int  Mission05_MarkFailureOnFriendlyAttack(int result, int target_owner_index);
int  WorldMap_DrawMission07TreasureMarker(int result, int tile_y);
int  WorldMap_DrawMission11ShrineMarker(int result, int tile_y, int screen_y, int screen_x);
int  Mission_MarkObjective15CompleteOnAttack(int result, int target_owner_index);
int  WorldMap_DrawMission17TreasureMarker(int result, int tile_y);
BOOL  Mission_CheckObjectiveComplete(DWORD a1, double a2);
int Mission_CheckFailureCondition(void);
int  Scenario_LoadMissionByIndexAndPlay(char *mission_index_arg, int a2, DWORD a3, double a4);
CLASH95_INTERNAL CompatRenderStateTail *Compat_RenderStateTailFields (int render_state);
int  RenderState_ReleaseCursorResources(int render_state);
unsigned int  DD_Pump(int render_state, int a2, ...);
void  RenderState_SetMouseSpeed(int render_state, int mouse_speed, DWORD a3);
BOOL  DD_IsFlipping(int render_state);
BOOL  DD_IsLost(int render_state);
BOOL  Input_PollEventsUntil(int render_state, char a2);
BOOL  RenderState_IsCursorFlipStillActive(int render_state);
BOOL  Render_Begin(int a1, void (*a2)(void), ...);
BOOL  Render_FlipRect(int render_state, char a2);
int  RenderState_PollInputAndClampCursor(int render_state, int a2);
unsigned int  RenderState_WarpCursorAndPump(_DWORD *render_state, unsigned __int16 cursor_x, unsigned __int16 cursor_y);
_DWORD * RenderState_RecalculateCursorBoundsForRect(_DWORD *result, __int16 rect_left, __int16 rect_right, __int16 rect_top, __int16 rect_bottom);
_DWORD * RenderState_PumpIfRectInViewBounds(_DWORD *result, unsigned __int16 rect_left, unsigned __int16 rect_right, unsigned __int16 rect_top, unsigned __int16 rect_bottom);
_DWORD * RenderState_LoadDefaultCursorSprite(int render_state);
_DWORD * RenderState_LoadOrRenderCursorLabelSprite(int render_state, int label_text, int a3, DWORD a4);
CLASH95_INTERNAL void Compat_PresentPrimaryIndexedSurfaceToPlatform(void);
__int16  RenderState_SelectCursorDescriptor(int render_state, int new_descriptor);
int  Render_Present(int render_state);
int Render_Pump(void);
void Input_Flush(void);
int  RenderState_DrawCursorSpriteToPrimarySurface(int render_state);
int  Device_DoOp(int render_state, int a2, DWORD a3);
__int16  Device_GetParamB(int render_state, DWORD a2, int a3, int a4);
int  Device_SetParamA(int render_state, DWORD a2);
int  Device_UpdateRect(_DWORD *render_state, int a2, int a3);

/* Deliberate unprototyped residue: recovered call sites depend on K&R semantics
 * (varying arity) or the slot type is unrecovered; kept verbatim as provenance. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
unsigned int  Rules_CreateArmyFact();
_DWORD * Rules_RetractTreasureFact();
#pragma GCC diagnostic pop

#endif /* CLASH95_STRATEGIC_API_H */
