/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'strategic' (29); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_STRATEGIC_SHARED_STATE_H
#define CLASH95_STRATEGIC_SHARED_STATE_H

#include "../recovered_types.h"

extern char a1[3];
extern char a2[3];
extern char aArama1[7];
extern char aGfx[5];
extern char aKon_por1[9];
extern char aMap_pal_1[8];
extern int g_ActiveCursorDescriptorPtr;
extern int g_CurrentPlayerIndex;
extern char g_CursorCoordShift;
extern int g_CursorDesc_Busy[10];
extern int g_CursorOverlayPresented;
extern int g_FileSystemMountTable[11];
extern InputBackendState g_InputBackendState;
extern char g_LanguageIndex;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_MapPalettePtr;
extern unsigned char g_Mission17ScriptedTreasureEventData[];
extern unsigned char g_Mission7ScriptedTreasureEventData[];
extern int g_PrimaryRenderSurface;
extern _UNKNOWN *g_RenderDevice;
extern int (*g_RenderHook)(int a1, char a2, DWORD a3);
extern _DWORD g_RenderState[286];
extern _UNKNOWN g_Runtime_PaletteArrayCtorDescriptor;
extern int g_SelectedUnitIndex;
extern unsigned char g_TreasureDigOutcomeTable_TempleActive[];
extern unsigned char g_TreasureDigOutcomeTable_TempleInactive[];
extern CLASH95_INTERNAL const UnitTypeRuntimeCoreMetadataRecord g_UnitTypeRuntimeCoreMetadata[UNIT_TYPE_METADATA_CAPACITY];
extern int g_WorldMapBackgroundSpriteSet;
extern int gameData;

#endif /* CLASH95_STRATEGIC_SHARED_STATE_H */
