/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/buildings/0042A910_0042C4E0_buildings_009.cpp' (2); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0042A910_0042C4E0_BUILDINGS_009_LOCAL_H
#define CLASH95_TU_0042A910_0042C4E0_BUILDINGS_009_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL void BuildingEconomyDialog_InitWidget(
        unsigned char *record,
        int left,
        int top,
        int normal_sprite,
        int hover_sprite,
        int (*transition_callback)(unsigned __int16 *, int, DWORD),
        void *action_callback,
        const char *text_pl,
        const char *text_en,
        const char *text_de,
        unsigned char tooltip_mode,
        const char *sound) CLASH95_LOCAL_SYMBOL(BuildingEconomyDialog_InitWidget);
CLASH95_LOCAL void BuildingEconomyDialog_EnsureWidgets(void) CLASH95_LOCAL_SYMBOL(BuildingEconomyDialog_EnsureWidgets);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0042A910_0042C4E0_BUILDINGS_009_LOCAL_H */
