/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/buildings/00422100_00422AC0_buildings_004.cpp' (11); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00422100_00422AC0_BUILDINGS_004_LOCAL_H
#define CLASH95_TU_00422100_00422AC0_BUILDINGS_004_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE int Castle_InvokePrisonerPanel (int building_record, int callback_context, DWORD runtime_context) CLASH95_LOCAL_SYMBOL(Castle_InvokePrisonerPanel);
CLASH95_TEST_VISIBLE int Castle_InvokeEconomyPanel (int building_record, int callback_context, DWORD runtime_context) CLASH95_LOCAL_SYMBOL(Castle_InvokeEconomyPanel);
CLASH95_TEST_VISIBLE void BuildingGarrisonDialog_WriteActionWidgetRecord (unsigned char *record, int left, int top, int flags, int sprite_index_base, int sprite_index_selected_base, void *action_callback, const char *text_pl, const char *text_en, const char *text_de, const char *sound) CLASH95_LOCAL_SYMBOL(BuildingGarrisonDialog_WriteActionWidgetRecord);
CLASH95_LOCAL int BuildingGarrisonDialog_Run(int building_record, int callback_context, DWORD runtime_context) CLASH95_LOCAL_SYMBOL(BuildingGarrisonDialog_Run);
CLASH95_LOCAL void Diagnostics_ResetFrameDumpOnCastleReturn(void) CLASH95_LOCAL_SYMBOL(Diagnostics_ResetFrameDumpOnCastleReturn);
CLASH95_LOCAL void Diagnostics_ResetFrameDumpOnCastleEnter(void) CLASH95_LOCAL_SYMBOL(Diagnostics_ResetFrameDumpOnCastleEnter);
CLASH95_LOCAL void Diagnostics_ResetFrameDumpOnBarracksEnter(void) CLASH95_LOCAL_SYMBOL(Diagnostics_ResetFrameDumpOnBarracksEnter);
CLASH95_LOCAL void Diagnostics_ResetFrameDumpOnBarracksDetail(void) CLASH95_LOCAL_SYMBOL(Diagnostics_ResetFrameDumpOnBarracksDetail);
CLASH95_TEST_VISIBLE int Diagnostics_IsWorldMapActionVerbose (void) CLASH95_LOCAL_SYMBOL(Diagnostics_IsWorldMapActionVerbose);
CLASH95_TEST_VISIBLE int Diagnostics_ShouldTraceWorldMapActionStage (const char *stage) CLASH95_LOCAL_SYMBOL(Diagnostics_ShouldTraceWorldMapActionStage);
CLASH95_TEST_VISIBLE void Diagnostics_TraceCastleHotspots (int surface_handle) CLASH95_LOCAL_SYMBOL(Diagnostics_TraceCastleHotspots);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00422100_00422AC0_BUILDINGS_004_LOCAL_H */
