/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/buildings/0043CD00_0043E4B0_buildings_005.cpp' (3); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0043CD00_0043E4B0_BUILDINGS_005_LOCAL_H
#define CLASH95_TU_0043CD00_0043E4B0_BUILDINGS_005_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE WCCompatListBase *WCCompat_ListFromBase (WCIsvListBase *this_) CLASH95_LOCAL_SYMBOL(WCCompat_ListFromBase);
CLASH95_TEST_VISIBLE WCCompatListBase *WCCompat_ListFromHandle (int list_handle) CLASH95_LOCAL_SYMBOL(WCCompat_ListFromHandle);
CLASH95_TEST_VISIBLE WCCompatLink *WCCompat_LinkFromHandle (int link_handle) CLASH95_LOCAL_SYMBOL(WCCompat_LinkFromHandle);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0043CD00_0043E4B0_BUILDINGS_005_LOCAL_H */
