/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'buildings': functions defined here and referenced from another subsystem (158). */
#ifndef CLASH95_BUILDINGS_API_H
#define CLASH95_BUILDINGS_API_H

#include "../recovered_types.h"

CLASH95_INTERNAL BOOL Building_NewAt (int row, int column, int building_type, DWORD stack_index, double st7_0, char *name, int force);
_DWORD * Building_LogBuiltCastleFacts(unsigned __int8 *buildingPtr);
BOOL  MapTile_IsCastleFoundationTile(int row, signed int column, int checkMode);
BOOL  MapTile_IsCastleFoundationAnchorTile(int row, signed int column, int checkMode);
int Rules_RebuildCastleSiteFacts(void);
int  Unit_UpdatePerTurn(int buildingPtr, int a2);
void  Building_DebugDump(unsigned __int8 *buildingPtr, char a2, DWORD a3);
void  LogAllBuildings(int a1, char a2, DWORD a3);
unsigned __int8 * Building_NewTurn(int a1, unsigned __int8 *buildingPtr, DWORD a3, double a4);
char  Building_GetInto(int buildingIndex, char a2, DWORD a3);
signed int  Building_BuildSchool(char *, char, DWORD);
signed int  Building_BuildWorkshop(int buildingRecord, char a1, DWORD a2);
signed int  Building_BuildBarracks(int a1, char a2, DWORD a3);
signed int  Building_BuildHospital(int buildingRecord, char a1, DWORD a2);
signed int  Building_BuildSmiths(int buildingRecord, char a1, DWORD a2);
signed int  Building_Transfer(int buildingIndex, int targetStackIndex, int transferGold, int transferAmount, double a5);
BOOL  Building_CanStartUpgrade(unsigned __int8 *buildingPtr);
BOOL  Building_TryStartUpgrade(unsigned __int8 *buildingPtr);
_DWORD * Unit_CaptureBuilding(int capturingStackIndex, DWORD buildingIndex, int a3, signed int j, double a5);
_DWORD * Building_Destroy(int a1, char a2, DWORD a3, double a4);
extern int Unit_FindById (int a1);
void * Building_ShowHoverInfoPopup(unsigned __int8 *buildingPtr, char spriteSetId, int a3);
int  Building_ShowConstructionProgressDialog(DWORD buildingRecord, char spriteSetId, DWORD a3, double a4);
int __fastcall Time_Now(int a1, int a2);
unsigned int  Timer_BusyWaitWithCallback(int durationTicks, int callbackAddr, int a3);
CLASH95_INTERNAL void Diagnostics_ResetFrameDumpOnBattleEnter (void);
CLASH95_INTERNAL void Diagnostics_PrimeBattleSafeCursorOnTurnLoop (void);
CLASH95_INTERNAL int Diagnostics_CountBattleUnitsForOwner (int owner);
CLASH95_INTERNAL int Diagnostics_CountBattleUnitsTotal (void);
CLASH95_INTERNAL void Diagnostics_TraceBattleUnitSnapshot(const char *stage);
CLASH95_INTERNAL int Diagnostics_IsBattleTileDrawTraceEnabled (void);
CLASH95_INTERNAL int Diagnostics_IsWorldMapClickTraceEnabled(void);
CLASH95_INTERNAL void Diagnostics_TraceWorldMapClickEvent(
        const char *stage,
        int tile_x,
        int tile_y,
        int left,
        int top,
        int selected_unit_index);
CLASH95_INTERNAL void Diagnostics_TraceBattlefieldClickEvent (const char *stage, int local_x, int local_y, int tile_x, int tile_y, int occupant_slot);
CLASH95_INTERNAL void Diagnostics_TraceWorldMapActionEvent(
        const char *stage,
        int selected_unit_index,
        int detail_a,
        int detail_b,
        int detail_c);
CLASH95_INTERNAL int Diagnostics_UnitStackIndexFromRecord(int stack_record);
CLASH95_INTERNAL void Diagnostics_TraceBootstrapEvent(const char *stage);
CLASH95_INTERNAL void Diagnostics_TraceWorldMapUnitSnapshot(const char *stage);
CLASH95_INTERNAL void Diagnostics_TraceWorldMapCursorSample(
        int tile_x,
        int tile_y,
        int left,
        int top,
        int selected_unit_index);
int  Tooltip_CaptureBackdrop(int top, int bottom, int resourceHandle, int rightX, int regionMarkerId);
int Tooltip_ReleaseBackdropSurface(void);
void * Tooltip_ShowText(int a1, char *format, ...);
int Tooltip_RestoreBackdrop(void);
int  Tooltip_RestoreIfTextMatches(int a1, int a2);
int  Tooltip_SetResourceHandle(int result);
signed int  UnitStack_HasOnlyFlyingUnits(int stackPtr);
int  Unit_AddToGroup(unsigned int a1, int a2, int a3, DWORD a4, double a5);
BOOL  Unit_MoveSelectionFromGroupToTile(int a1, _DWORD *a2, int a3, int a4, double a5, int a6);
_DWORD * UI_LoadCurrentPlayerInfoSpriteSet(int playerIndex, int a2, char a3, DWORD a4);
int UI_FreeCurrentPlayerInfoSpriteSet(void);
int  UnitStack_ShowSelectionDialog(int unitIndex, int a2);
signed int  UnitStackSelection_HandleInput(DWORD a1, double a2);
signed int UnitStackSelection_HasSelectedSlots(void);
int  UnitStackSelection_BeginForSelectedStack(DWORD a1);
int __thiscall UnitStackSelection_End(void *this);
int __thiscall UnitStackSelection_ClearMask(void *this);
int  UnitStackSelection_RefreshForSelectedStack(DWORD a1);
signed int  Map_GetBridgeCrossingCostOrZero(int row, int column);
signed int  Road_Build(int unitIndex, int direction, char a3, DWORD a4, double a5);
signed int  UnitStack_MoveOneTileInDirection(int unitIndex, int direction, double a3);
BOOL  Map_TileHasOwner(int row, int column);
int Map_AutoUpgradeVillages(void);
signed int  Builder_StartRoadBuildMode(DWORD a1, double a2);
int UnitBattle_InitPathingTables(void);
int * UnitBattle_MoveTrack(int unitIndex, int targetRow, int a3, int targetColumn, DWORD a5);
int * UnitBattle_MoveTrackNear(int unit_index, int row, int col, DWORD a4);
int * UnitBattle_MoveTrackNearWall(int unit_index, int row, int col, DWORD a4);
__int16  UnitBattle_Move(int a1, int a2, __int16 a3, DWORD a4);
int  UnitBattle_CenterViewOnUnit(int unit_index);
int  UnitBattle_CountAdjacentEnemies(int unit_record);
signed int  UnitBattle_Attack(int attacker_index, int defender_index, int charge_mode);
BOOL  UnitBattle_IsTileWithinRange(int unit_index, int target_row, int target_col);
BOOL  UnitBattle_IsUnitWithinRange(int unit_index, int target_unit_index);
int  UnitBattle_Shot(int shooter_index, int target_index); // weak
int  UnitBattle_AttackWall(int unitSlot, DWORD wallRow, int a3, int wallCol);
int  UnitBattle_ShotWall(int unitSlot, int targetRow); // weak
signed int  UnitBattle_Defence(int unitSlot, char a2, DWORD a3);
int  BuildBuilding(int, int, char, double);
signed int  Trap_New(DWORD, int, int, int, double);
__int16 * Trap_HurtStack(__int16 *stack, char a2, DWORD a3, double a4);
int  Trap_GetTileOwnerMask(int tileX, int tileY, int playerIndex);
signed int  Trap_TriggerAtStackTile(int stackIndex, DWORD a2, double a3);
int  Trap_ShowPitfallDiscoveryDialog(int tileX, int tileY, char spritePath, DWORD a4);
int  Battle_LoadWallSegmentsFromBuildingRecord(int buildingRecord);
char  Battle_SaveWallSegmentsToBuildingRecord(int buildingRecord);
BOOL  UnitBattle_IsTileInViewport(int tileRow, int tileCol);
void  Battle_LogAllUnits(int a1, char a2, DWORD a3);
int  GodAnger(DWORD playerIndex, int a2, char a3);
int  Battle_NewTurn(int a1, char a2, DWORD a3);
BOOL Battle_HasUnitsForBothSides(void);
int  Battle_ApplyPeriodicDamageToSideUnits(int sideOwner);
_BOOL2 UnitBattle_HandleManualRotateAndMoveInput(void);
int __thiscall UnitBattle_UpdateViewportFromInputAndGetHoveredSlot(int this);
int  Palette_LoadOrBuildBlendLookupTable(CHAR *themeName, int palettePtr, int a3, DWORD fileContext);
signed int  UnitBattle_RunAiTurnForSide(unsigned __int8 side);
int  WCIsvListBase_dtorRoot(int result, char dtorFlags);
int __cdecl WCIsvListBase_vtblFree(void);
int  WCIsvListBase_dtorVariant124(WCIsvListBase *a1, char dtorFlags);
int  WCIsvListBase_dtorVariant134(WCIsvListBase *a1, char dtorFlags);
_DWORD *WCIsvListBase_vtblDtor(WCIsvListBase *this);
_DWORD WCIsvListBase_dtor(WCIsvListBase *this);
int  WCIsvListBase_DestroyElementsAndDtor(WCIsvListBase *this, int listHandle);
int  Battle_DeploySideUnitsByRoleBuckets(char *ownUnits, int ownCount, char *enemyUnits, int placementSide, int enemyCount);
BOOL  Building_HasFreeAdjacentExitTile(unsigned __int8 *building);
signed int  Building_UnitsLeave(unsigned __int8 *building, int *exitSlots, double gameTime);
int  Building_CountFreeGarrisonSlots(int buildingId);
signed int  Building_UnitGetInto(int unitStackId, int buildingId, char a3, signed int i, double gameTime);
signed int  Building_CanAcceptUnitStack(int stackIndex, int buildingId);
signed int  Building_HasUnitLicence(int building, unit_type unitType);
BOOL  Building_BuyUnitLicence(int building, unit_type unitType, int a3, DWORD gameContext);
int  Building_RemoveUnitLicence(int building, unit_type unitType, DWORD gameContext);
int  Building_SetUnitProduction(int building, char licenceSlot, DWORD gameContext);
_BYTE * Building_TrainUnit(int building, char garrisonSlot, DWORD gameContext);
int  Building_ClearGarrisonTrainingTimer(int result, int building);
__int16  Building_RepairUnit(int building, int slotIndex, DWORD gameContext);
int  Building_ClearGarrisonRepairTimer(int result, int building);
int  Building_CountGarrison(int building);
int  Building_CountNonCombatGarrisonEntries(int building);
signed int  Building_HasSpecialPersonageGarrisonEntries(int building);
int  Building_CompactGarrison(unsigned __int8 *building, unsigned __int8 *a2, double gameTime);
BOOL  Building_IsUnitLicenceEligible(char *building, unit_type unitType);
int  Building_AdjustAllGarrisonMoraleByDelta(int building, int moraleDelta);
int  Building_CycleAllGarrisonOrdersOnce(int building);
int  Building_GetTotalValue(int building);
int  AI_TickNationPostTurn(int playerIndex);
int  Player_CalcAvailableStrongholdFunds(int playerIndex);
int  Player_SpendStrongholdFundsEvenly(int playerIndex, signed int remaining);
int BuildingSpriteCache_Reset(void);
int  BuildingSpriteCache_GetOrLoadEntry(DWORD buildingKind, int variantIndex, signed int orientation, int assetSet, int frameIndex);
int BuildingSpriteCache_Clear(void);
int BuildingSpriteCache_CountEntries(void);
int Rules_RebuildTempleFacts(void);
signed int  MapTile_GetReligiousSiteCategory(int tileX, int tileY);
int * Temple_GenerateApproachTrack(int stackIndex, int tileX, int a3, int tileY);
int  Temple_ShowOutcomePopup(int messageTextPtr, int iconChar, int a3, int a4, DWORD gameContext);
void  Temple_ProcessGift(DWORD giftType, __int16 *unitStack, int tileY, char tileX, double gameTime);
int  Temple_UnitGetInto(int stack_index, int tile_x, int tile_y, DWORD gameContext, double gameTime);
void  BattleMapFileName(char *outPath, int tileX, int tileY);
char  BattleMap_GetOutcomeVariantFileName(char *outPath, int tileX, int tileY);
int  BattleMap_GetMoveSoundSurfaceClass(int tileRow, int tileCol);
int  Sound_PlayNamedSfxFile(char *soundName, int volume);
int  Music_PlayMainMapTrack(int result, int a2, int a3, DWORD gameContext);
int  Audio_PauseMusicAndPlayLoopedSound(char *trackName, int trackNumber);
int  Audio_ResumeMusicAndStopLoopedSound(int result);
int Audio_StopMainMusic(void);
int  Audio_StopMusicWithFade(int result);
void Audio_DuckMusicVolume(void);
void Audio_RestoreMusicVolume(void);
int  Audio_StartMainMusicIfStopped(int a1, DWORD gameContext);
int Audio_StopMainMusicIfPlaying(void);
void Audio_SetMusicActiveFlag(void);
void Audio_ClearMusicActiveFlag(void);
void Audio_EnableUnitSounds(void);
void Audio_DisableUnitSounds(void);
int  Audio_PlayUnitActivateSound(int result);
int  Audio_PlayUnitMoveOrderSound(int result);

/* Deliberate unprototyped residue: recovered call sites depend on K&R semantics
 * (varying arity) or the slot type is unrecovered; kept verbatim as provenance. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
BOOL  Building_New();
_DWORD * Temple_Random();
#pragma GCC diagnostic pop

#endif /* CLASH95_BUILDINGS_API_H */
