/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Home-only functions of 'render' (25); private to the subsystem. */
#ifndef CLASH95_RENDER_INTERNAL_H
#define CLASH95_RENDER_INTERNAL_H

#include "render_api.h"

__int16 Render_LoadResourceBackbuffer(void);
int  Palette_ExpandRGBTripletsToTable(int palette_table, int query_handle, int context);
int  LoadPalPCX(int palette_table, const char *palette_name, DWORD context);
int  Palette_BuildGrayscaleIdentityTable(int palette_table);
_BYTE * Str_CompactSkippingZeroBytes(_BYTE *result, _BYTE *src, unsigned int count);
_DWORD * Render_ConstructSurfaceObject(int surface_addr, __int16 width, __int16 height);
_DWORD * Render_ConstructScratchSurface(int surface_addr, unsigned __int16 width, DWORD companion_flag, __int16 height);
int  Surface_ConstructBackbufferInstance(int surface_addr);
extern int Surface_SwapDirtyTrackingFlag (int surface, int new_flag);
int * Palette_CrossfadeToTarget(int *result, unsigned __int8 *target_palette, signed int step_count);
_DWORD * RenderSurface_ConstructNullBlitCursor(_DWORD *result);
int __thiscall RenderSurface_CloneInternalArray(void *this);
_BYTE * RenderSurface_CopyFourByteFields(_BYTE *result, _BYTE *source);
_DWORD * RenderSurface_ConstructFullScreenBuffer(int surface_addr);
int * DLXSpriteSet_Destroy(int *sprite_set, char flags, int a3);
int  DLXSpriteSet_ConstructCopy(int *sprite_set, DWORD *source_set, signed int entry_count);
int * DLXSpriteSet_CopyEntriesFrom(int *sprite_set, DWORD *source_set, int a3, signed int entry_count);
int  DLXSprite_ConstructFromBuffer(int result, int source_buffer, int data_size);
int  DLXSprite_ConstructOwningCopy(int sprite, DWORD source_sprite);
int  DLXSprite_Destroy(int result);
int  DLXSprite_CopyFrom(int sprite, DWORD source_sprite);
int  DLXSprite_Save(int sprite, int file_handle);
char  DLXSprite_RemapPalette(int sprite, const unsigned __int8 *remap_table);
extern int Menu_DrawFrameBackdrop();
int Render_RestoreLostSurfaces(void);

#endif /* CLASH95_RENDER_INTERNAL_H */
