/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'render' (30); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_RENDER_SHARED_STATE_H
#define CLASH95_RENDER_SHARED_STATE_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern char a1[3];
extern char a10[3];
extern char a11[3];
extern char a12[3];
extern char a2[3];
extern char aGfx[5];
extern char aIOCouldnTOpenF[29];
extern int g_ActiveUiSpriteSet;
extern char g_CursorCoordShift;
extern int g_CursorOverlayPresented;
extern int g_FileSystemMountTable[11];
extern char g_LanguageIndex;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_MapPalettePtr;
extern int g_Palette_BlendRatio;
extern int g_PrimaryRenderSurface;
extern _UNKNOWN *g_RenderDevice;
extern _DWORD g_RenderState[286];
extern unsigned short g_Render_AnimatedFrameTable[1038];
extern char g_Render_BackgroundColorIndex;
extern int g_SelectedUnitIndex;
extern RenderSpriteRemapEntry g_SpriteCodeRemapTable[1024];
extern RenderSpriteRemapEntry g_TerrainAnimationRemapTable[1024];
extern char g_TextSprite_StyleFlag;
extern int g_UnitStackSelectionActiveUnitIndex;
extern _DWORD g_UnitStackSlotSelectedFlags[10];
extern int g_WorldMapViewportScrolledFlag;
extern int g_WorldMap_KeyboardInputDisabled;
extern int gameData;
extern HWND hWnd;

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_RENDER_SHARED_STATE_H */
