/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* State-TU globals whose only consuming subsystem is 'render' (85). */
#ifndef CLASH95_RENDER_STATE_H
#define CLASH95_RENDER_STATE_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern CHAR Caption[];
extern CHAR Text[128];
extern char aCannotConform2[43];
extern char aConvertsprUnsu[39];
extern char aDlxmemscreenDr[76];
extern char aDlxmemscreen_0[76];
extern char aDlxspritesetDl[33];
extern char aDlxspritesetSa[23];
extern char aDlxvscreenDraw[87];
extern char aDotboxZapisNaE[44];
extern char aDrawboxZapisNa[45];
extern char aDrawlineZapisN[46];
extern char aDrawpixZapisNa[45];
extern char aDrawrectZapisN[46];
extern char aGetpixZapisNaE[44];
extern char aGetreadincrZap[49];
extern char aGetwriteincrZa[50];
extern char aGfx_0[5];
extern char aGfx_1[5];
extern char aGfx_2[5];
extern char aGfx_3[5];
extern char aGfx_4[5];
extern char aGfx_7[5];
extern char aGfx_8[5];
extern char aNotEnoughFreeM[23];
extern char aNotEnoughMe_15[21];
extern char aNotEnoughMe_16[21];
extern char aNotEnoughMem_0[21];
extern char aNotEnoughMem_1[21];
extern char aNotEnoughMem_2[21];
extern char aNotEnoughMem_7[21];
extern char aNotEnoughMem_8[21];
extern char aNotEnoughMemor[21];
extern char aPal_grey_pcx[13];
extern char aRb_0[3];
extern char aRemsc[6];
extern char aRestorescreenc[18];
extern char aS[9];
extern char aWb[3];
extern char a_loadpalcolS0x[25];
extern char a_loadpalpcxS0x[25];
extern char a_loadpcxS0x08x[31];
extern char asc_4EC5AC[57];
extern int g_ActiveBlitCursor;
extern _UNKNOWN g_BlitCursor_DtorArrayTag;
extern __int16 g_ColorCycleDelayLookupIndex;
extern _UNKNOWN g_DLXSpriteSet_DtorArrayTag;
extern _BYTE g_DefaultPaletteTable[1024];
extern int g_DlxDirEntryEndOffsetTable[1022];
extern int g_DlxDirTotalDataOffset;
extern int g_DlxDirectoryEntryEndOffsets[1024];
extern int g_DlxDirectoryEntryStartOffsets[];
extern int g_DlxSpriteSetOffsetTable[];
extern _UNKNOWN g_LinkedBlitCursor_DtorArrayTag;
extern int g_MousePresentAtStartup;
extern uintptr_t g_NullBlitCursor_Vtable[5];
extern int g_PaletteCrossfadeNextStepTime;
extern _BYTE g_PaletteCrossfadeSourceBuffer[0x408];
extern _BYTE g_PaletteScratchSurfaceBuffer[1024];
extern char g_PaletteShadowRemapTableMinus1[];
extern _UNKNOWN g_RenderBackbufferScanlineBuffer;
extern RenderSurfaceStorage g_RenderDeviceStorage;
extern _UNKNOWN g_RenderPaletteRemapBuffer;
extern uintptr_t g_RenderSurface_BlitCursorVtable[5];
extern _UNKNOWN g_RenderSurface_DtorArrayTag;
extern uintptr_t g_RenderSurface_LinkedBlitCursorVtable[5];
extern _UNKNOWN g_ScratchSurface_DtorArrayTag;
extern int g_ScratchSurface_Vtable[17];
extern unsigned char g_SpecialTileAnimFrameDuration;
extern _UNKNOWN g_SurfaceCursor_DtorArrayTag;
extern _UNKNOWN g_SurfaceRawBuffer_DtorArrayTag;
extern int g_Surface_BaseVtable[17];
extern _UNKNOWN g_Surface_DtorArrayTag;
extern int g_Surface_RawBuffer8Vtable[17];
extern int g_Surface_Vtable[21];
extern char *g_Text_LowMorale[3];
extern char g_Video_LowColorRemapTable[32];
extern __int16 g_WorldMapAmbientAnimFramesSetA[7];
extern __int16 g_WorldMapAmbientAnimFramesSetB[2];
extern __int16 g_WorldMapAmbientAnimFramesSetC[5];
extern int g_WorldMapKeyScrollRepeatTime;
extern int g_WorldMap_NextPaletteAnimTime;
extern int g_WorldMap_NextTileStateAnimTime;
extern int g_WorldMap_PaletteFlashStep;

/* Deliberate unprototyped residue: recovered call sites depend on K&R semantics
 * (varying arity) or the slot type is unrecovered; kept verbatim as provenance. */
#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
#endif
extern int (*g_DLXSpriteSet_Vtable)();
#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))
#pragma GCC diagnostic pop
#endif

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_RENDER_STATE_H */
