/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/world/0040A0E0_0040B020_world_002.cpp' (3); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0040A0E0_0040B020_WORLD_002_LOCAL_H
#define CLASH95_TU_0040A0E0_0040B020_WORLD_002_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL void WorldMap_WriteActionWidgetRecord(
        unsigned char *record,
        int left,
        int top,
        int flags,
        int sprite_index_base,
        int sprite_index_selected_base,
        int action_callback,
        const char *polish_label,
        const char *english_label,
        const char *german_label,
        const char *sound_name) CLASH95_LOCAL_SYMBOL(WorldMap_WriteActionWidgetRecord);
CLASH95_TEST_VISIBLE int WorldMap_DeferBuildingActionCallback (uintptr_t widget) CLASH95_LOCAL_SYMBOL(WorldMap_DeferBuildingActionCallback);
CLASH95_LOCAL void UnitBattle_WriteActionWidgetRecord(
        unsigned char *record,
        int left,
        int top,
        int flags,
        int sprite_index_base,
        int sprite_index_selected_base,
        int overlay_sprite_index,
        int action_callback,
        const char *polish_label,
        const char *english_label,
        const char *german_label,
        const char *sound_name) CLASH95_LOCAL_SYMBOL(UnitBattle_WriteActionWidgetRecord);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0040A0E0_0040B020_WORLD_002_LOCAL_H */
