/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/world/0040B0A0_0040D560_world_003.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0040B0A0_0040D560_WORLD_003_LOCAL_H
#define CLASH95_TU_0040B0A0_0040D560_WORLD_003_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL TextSpriteResourceSlotRecord *TextSprite_GetActiveResourceSlot(void) CLASH95_LOCAL_SYMBOL(TextSprite_GetActiveResourceSlot);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0040B0A0_0040D560_WORLD_003_LOCAL_H */
