/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'world' (48); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_WORLD_SHARED_STATE_H
#define CLASH95_WORLD_SHARED_STATE_H

#include "../recovered_types.h"

extern int Map_NeighborDX[64];
extern int Map_NeighborDY[63];
extern char a1[3];
extern char a2[3];
extern char aArama1[7];
extern char aKon_por1[9];
extern char aStdrh_3[6];
extern int g_ActiveCursorDescriptor;
extern int g_ActiveCursorDescriptorPtr;
extern int g_ActiveTextSpriteSlot;
extern int g_ActiveUiSpriteSet;
extern int g_BattleButtonsSpriteSet;
extern int g_CurrentPlayerIndex;
extern char g_CursorCoordShift;
extern int g_CursorDesc_ActionBusy[10];
extern int g_CursorDesc_Attack[10];
extern int g_CursorDesc_Busy[10];
extern int g_CursorDesc_Default[10];
extern int g_FlagSpriteSet;
extern int g_FogOverlaySpriteSet;
extern char g_LanguageIndex;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_MapPalettePtr;
extern int g_MapPanelSpriteSet;
extern int g_MarksSpriteSet;
extern int g_MissionDefeatVideoPlayedGuard;
extern int g_MovePathStepSpriteSet;
extern int g_PrimaryRenderSurface;
extern _UNKNOWN *g_RenderDevice;
extern int (*g_RenderHook)(int a1, char a2, DWORD a3);
extern _DWORD g_RenderState[286];
extern unsigned short g_Render_AnimatedFrameTable[1038];
extern int g_SavedCursorDescriptor;
extern int g_SelectedUnitIndex;
extern RenderSpriteRemapEntry g_SpriteCodeRemapTable[1024];
extern RenderSpriteRemapEntry g_TerrainAnimationRemapTable[1024];
extern char g_TextSprite_StyleFlag;
extern int g_TreeSpriteSet;
extern _BYTE g_UnitBattleActionWidgetTable[WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * (UNIT_BATTLE_ACTION_WIDGET_COUNT + 1)] __attribute__((aligned(4)));
extern int g_UnitStackSelectionActiveUnitIndex;
extern _DWORD g_UnitStackSlotSelectedFlags[10];
extern CLASH95_INTERNAL const UnitTypeRuntimeCoreMetadataRecord g_UnitTypeRuntimeCoreMetadata[UNIT_TYPE_METADATA_CAPACITY];
extern int g_WhirlSpriteSet;
extern _BYTE g_WorldMapActionButtonWidgetTable[WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * (WORLD_MAP_ACTION_WIDGET_COUNT + 1)] __attribute__((aligned(4)));
extern int g_WorldMapBackgroundSpriteSet;
extern int g_WorldMapTargetSurface;
extern int g_WorldMap_KeyboardInputDisabled;
extern int gameData;

#endif /* CLASH95_WORLD_SHARED_STATE_H */
