/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* State-TU globals whose only consuming subsystem is 'world' (135). */
#ifndef CLASH95_WORLD_STATE_H
#define CLASH95_WORLD_STATE_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern char aAutoMovesBegin[17];
extern char aAutoMovesEnd[15];
extern char aBagno7pa[12];
extern char aBaum[5];
extern char aBerge[6];
extern char aBlad[5];
extern char aBuildingsCache[28];
extern char aClipsMemoryD[17];
extern char aComputerplay[15];
extern char aD[3];
extern char aDD[6];
extern char aDesert5ap[13];
extern char aDroga3pa[12];
extern char aEbene[6];
extern char aError[6];
extern char aError_0[6];
extern char aForest6ap[13];
extern char aGraczSTwojaTur[22];
extern char aGvryNiskie8pa[18];
extern char aGvryWysokie[13];
extern char aHbgel[6];
extern char aHills8ap[12];
extern char aKoniecGryPoDTu[24];
extern char aLas6pa[10];
extern char aMainmap[8];
extern char aMenuDraw[11];
extern char aMenuHide[11];
extern char aMountains[10];
extern char aNextPlayer[12];
extern char aNextTurnD[14];
extern char aPlain4ap[12];
extern char aPlayerD[10];
extern char aPlayerSYourTur[22];
extern char aPlaygame[11];
extern char aPlaygameEnd[17];
extern char aPustynia5pa[15];
extern char aRoad3ap[11];
extern char aRvwnina4pa[14];
extern char aSetrhS08x[14];
extern char aSetrhS08x_0[14];
extern char aSetrhS08x_1[14];
extern char aSetrhS08x_2[14];
extern char aSpielerS[11];
extern char aStart[7];
extern char aStrase[7];
extern char aStruktur[9];
extern char aStruktur_0[9];
extern char aStruktur_1[9];
extern char aSumpf[6];
extern char aSwamp7ap[12];
extern char aTerenNieodkryt[17];
extern char aTuraD[8];
extern char aUnerforschtesT[22];
extern char aUnexploredTerr[19];
extern char aUnitsCacheEntr[24];
extern char aUnsetrh08x[13];
extern char aUnsetrh08x_0[13];
extern char aUnsetrh08x_1[13];
extern char aUnsetrh08x_2[13];
extern char aUsedmemD_3[12];
extern char aWasser[7];
extern char aWater[6];
extern char aWbste[6];
extern char aWoda[5];
extern char aWrong_2[6];
extern char aWrong_3[6];
extern char aWrong_4[6];
extern char aWrong_5[6];
extern char aWrong_6[6];
extern char aZwy02[6];
extern char a_conformfont2p[21];
extern char a_end[5];
extern int g_AdvanceToNextPlayerFlag;
extern CLASH95_INTERNAL FILE *g_BattleInputScriptFile;
extern CLASH95_INTERNAL int g_BattleInputScriptInitialized;
extern CLASH95_INTERNAL int g_BattleInputScriptTraceChecked;
extern CLASH95_INTERNAL int g_BattleInputScriptTraceEnabled;
extern CLASH95_INTERNAL int g_BattleInputScriptWaitReads;
extern CLASH95_INTERNAL int g_BuilderRoadWidgetsInitialized;
extern _UNKNOWN g_Building_FootprintTemplate_Type0;
extern _UNKNOWN g_Building_FootprintTemplate_Type1;
extern _UNKNOWN g_Building_FootprintTemplate_Type2;
extern char *g_CastleFoundationTexts[9];
extern char *g_CultPlaceTexts[15];
extern int g_CursorDesc_CannotAttack[10];
extern int g_CursorDesc_CannotEnter[10];
extern int g_CursorDesc_CannotSelect[10];
extern int g_CursorDesc_DeliverCargo[10];
extern int g_CursorDesc_EnterSite[10];
extern int g_CursorDesc_GoTo[10];
extern int g_CursorDesc_SelectedUnitHover[10];
extern int g_CursorDesc_VisitBuilding[10];
extern char *g_EmptyCultPlaceTexts[12];
extern char *g_EmptyShrineTexts[18];
extern _WORD g_FontGlyphFallbackTable3[1528];
extern char *g_HiddenTreasureTexts[6];
extern int g_LastSelectedUnitIndex;
extern char g_MiniMapBuildingOwnerColorTable[1];
extern int g_MiniMapDrawMask;
extern char g_MiniMapPixelsPerTile;
extern __int16 g_MiniMapRectHeight;
extern __int16 g_MiniMapRectLeft;
extern __int16 g_MiniMapRectTop;
extern __int16 g_MiniMapRectWidth;
extern int g_MiniMapSurface;
extern int g_MiniMapTerrainColorTable;
extern unsigned char g_MiniMapTerrainColorTableVariant1[0x400];
extern unsigned char g_MiniMapTerrainColorTableVariant2[0x400];
extern unsigned char g_MiniMapTileColorTableTheme0[0x400];
extern int g_PendingLoadGameSlotIndex;
extern char *g_ShrineTexts[21];
extern int g_TextSpriteLastActivatedSlotIndex;
extern CLASH95_INTERNAL TextSpriteResourceSlotRecord g_TextSpriteResourceSlots[24];
extern char *g_Text_NoBuilder[3];
extern char *g_Text_QuitConfirm[3];
extern char *g_Text_SurrenderConfirm[3];
extern int g_TurnEndedByCompletionFlag;
extern int g_UITextCursorGlyphIndex;
extern _BYTE g_UI_YesNoDims[BUILDER_ACTION_WIDGET_TABLE_BYTES] __attribute__((aligned(4)));
extern unsigned __int8 g_UiDrawTextBuffer[512];
extern unsigned __int8 g_UiDrawTextFmtBuffer[516];
extern int g_UnitSearchCursor;
extern int g_WorldMapActionHoverActive;
extern CLASH95_INTERNAL int g_WorldMapActionWidgetsInitialized;
extern int g_WorldMapBuilderMenuAction;
extern int g_WorldMapFrameRedrawDisabled;
extern int g_WorldMapGameLostExitFlag;
extern int g_WorldMapJoinUnitsModeActive;
extern CLASH95_INTERNAL const WorldMapTopMenuHitRecord g_WorldMapTopMenuHitRecords[2];
extern int g_WorldMapTurnBannerSpriteSet;
extern int g_WorldMapTurnLoopExitFlag;
extern int g_WorldMap_CursorTileEnterTime;
extern int g_WorldMap_HoverTooltipActiveFlag;
extern int g_WorldMap_LastCursorTileX;
extern int g_WorldMap_LastCursorTileY;

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_WORLD_STATE_H */
