/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'world': functions defined here and referenced from another subsystem (53). */
#ifndef CLASH95_WORLD_API_H
#define CLASH95_WORLD_API_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

BOOL UI_TrySelectFriendlyStackUnderCursor(void);
BOOL  MapTile_HasOwnUnitStack(int tileX, int tileY);
BOOL  MapTile_HasVisibleEnemyUnitStack(int tileX, int tileY);
BOOL  MapTile_HasOwnBuilding(int tileX, int tileY);
BOOL  MapTile_HasEnemyBuilding(int tileX, int tileY);
BOOL  MapTile_HasBuilding(int tileX, int tileY);
BOOL  Port_IsInsideFootprint(int tileX, int tileY);
CLASH95_INTERNAL void WorldMap_EnsureActionButtonWidgetTable (void);
CLASH95_INTERNAL int UnitBattle_IsActionButtonWidgetAddress(uintptr_t widget);
CLASH95_INTERNAL void UnitBattle_EnsureActionButtonWidgetTable(void);
void  WorldMap_SyncSelectionForHumanPlayer(DWORD a1);
int  UI_LoadTurnBannerGfx(char a1, DWORD a2);
int * WorldMap_RenderHook(DWORD a1);
int  WorldMap_RedrawFrame(int a1, ...);
int  WorldMap_RedrawFrameForAIWhenEnabled(int a1);
void WorldMap_DisableFrameRedraw(void);
CLASH95_INTERNAL void WorldMap_RunInputScriptStep(void);
CLASH95_INTERNAL void Battle_ResetInputScriptReader (void);
CLASH95_INTERNAL void Battle_RunInputScriptStep(void);
unsigned int  WorldMap_Initialize(char a1, DWORD loadContext);
int  PlayGame(int a1, char a2, DWORD allocContext, char a4, double st0_runtime, ...);
int  Render_ReleaseSurface(int slotIndex, DWORD allocContext);
char  TextSprite_ActivateResourceSlot(int slotIndex, char styleFlag, DWORD allocContext);
char  TextSprite_SetStyleFlag(char result);
_BYTE * TextSprite_FindWordWrapBreak(_BYTE *text, int maxWidth);
int __cdecl UI_DrawText(int penX, int penY, int format, ...);
int  UI_DrawTextFmt(int penX, int left, int right, int y, int alignMode, const char *format, ...);
int  UI_DrawTextFmtV(int left, int right, int alignMode, int y, const char *format, va_list args);
int  UI_GetTextXOffset(int slotIndex);
int  UI_EndDraw(int slotIndex);
int TextSprite_ReleaseAllResourceSlots(void);
int  UI_SetTextCursorPosition(int result);
char  Str_TitleCase(_BYTE *result, int a2, int a3);
int  MiniMap_CreateSurface(DWORD allocContext);
int  MiniMap_BlitDirtyRectAndDrawViewportBox(int result, unsigned __int16 top, unsigned __int16 bottom, unsigned __int16 right);
int  MiniMap_RedrawTileRect(int x0, signed int y0, int y1, int x1);
BOOL  MiniMap_IsSpanWithinViewportBounds(unsigned __int16 left, unsigned __int16 bottom);
void Locale_DrawInteger(void);
void * MiniMap_DrawTileCell(void *result, signed int tileColumn);
signed int  Map_GetTileSurfaceClassOrUnexplored(int tileX, signed int tileY);
int MiniMap_ToggleVisibility(void);
BOOL MiniMap_IsCursorInside(void);
int  UI_RunMenu(_WORD *menu, DWORD a2);
int  UI_MenuEntry_Enable(int menuBase, int entryIndex);
int  UI_MenuEntry_Disable(int menuBase, int entryIndex);
void  Map_RevealAllTilesForPlayer(int playerIndex);
signed int  Map_RevealTileWithPropagation(int tileX, signed int tileY, int playerIndex);
BOOL  Map_IsTileVisibleToPlayer(int tileX, signed int tileY, int playerIndex);
signed int  Map_ClassifyFogOfWarOverlayForPlayer(int tileX, signed int tileY, int playerIndex);
signed int  UnitStack_IsIndexOnMap(int stackIndex);
int  UnitSlot_InitFromType(int result, unit_type unitType, char ownerIndex);
char  UnitStack_ResetRecord(int stackPtr, unit_type unitType, char ownerIndex);
CLASH95_INTERNAL void WorldMap_EnsureBuilderWidgetTables(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_WORLD_API_H */
