/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Home-only functions of 'world' (48); private to the subsystem. */
#ifndef CLASH95_WORLD_INTERNAL_H
#define CLASH95_WORLD_INTERNAL_H

#include "world_api.h"

BOOL  MapTile_HasOwnOrVisibleEnemyUnitStack(int tileX, int tileY);
void  WorldMap_HandleTileHoverAndClick(double);
int  WorldMap_ShowQuitConfirmDialog(int a1, char a2, DWORD a3);
int  WorldMap_HandleSaveGameAction(char a1, DWORD a2, double a3);
int  WorldMap_HandleLoadGameAction(DWORD a1, char a2, double a3);
int  WorldMap_HandleSurrenderAction(int a1, char a2, DWORD a3, double a4);
int  WorldMap_HandleDeselectUnitAction(uintptr_t widget, DWORD a2);
void  WorldMap_SelectNextActiveUnitStack(uintptr_t widget, int a2, DWORD statusPanelContext);
int  WorldMap_CenterViewOnNextOwnedBuildingWithUnit(int widget, int a2);
int  WorldMap_HandleHideUnitAction(int widget, int a2, unsigned __int16 a3, DWORD a4, double a5);
char *WorldMap_ToggleSelectedUnitModeFlag(void);
int  WorldMap_ComputeBuildMenuActionFromCursor(int widget, int a2);
int  WorldMap_HandleBuilderActionMenu(int widget, int a2, int a3, DWORD a4, double a5);
int __thiscall WorldMap_RefreshActionButtonBarState(void *this);
int  WorldMap_LoadActionButtonSprites(int a1, char a2, DWORD a3);
int __fastcall WorldMap_UnloadActionButtonSprites(int a1, int a2);
int  WorldMap_PollActionButtonWidgets(DWORD a1);
void  UnitStackSelection_SyncForCurrentSelection(void *a1, DWORD a2);
void * WorldMap_DrawTurnBannerReveal(int animate);
extern int WorldMap_RenderPlayerTurnIntroScreen (char a1, DWORD a2);
int  Game_AdvanceToNextPlayerTurn(int a1, char a2, DWORD a3, double a4);
_DWORD * WorldMap_LoadResources(char a1, DWORD loadContext);
int  WorldMap_UnloadResources(DWORD allocContext);
void  WorldMap_RunHumanTurnLoop(
        int entry_resource_handle,
        int ( *entry_render_hook)(int a1, char a2, DWORD a3),
        DWORD runtime_context,
        double st0_runtime);
extern TextSpriteResourceSlotRecord *TextSprite_GetResourceSlot (int slot_index);
int  TextSprite_DrawGlyphAndAdvance(int penX, int penY, unsigned __int8 charCode);
int  TextSprite_DrawStringWithOrientation(int penX, int penY, char vertical, unsigned __int8 *text);
extern int TextSprite_MeasureStringExtent (_BYTE *text);
int  Str_CountSpaces(char *text);
int  UI_RenderAlignedTextWithCursor(int left, int right, int alignMode, int y, int penX, unsigned __int8 *text);
extern void TextSprite_BuildOrLoadCachedFont (int slotIndex, _BYTE *fontData, int a3, char a4, DWORD allocContext);
_WORD * Font_ResetGlyphFallbackTable(_WORD *result);
int  Font_SetGlyphFallbackEntry(int tableBase, unsigned __int16 glyphId, char flagByte, __int16 fallbackValue);
int __cdecl Font_BuildGlyphFallbackChain(int tableBase, char flagByte, unsigned __int16 firstGlyphId, ...);
int  MiniMap_BuildTileColorTables(unsigned int themeIndex, int a2);
int __thiscall MiniMap_DestroySurface(void *this);
int MiniMap_UpdateViewportFromCursor(void);
int MiniMap_ShowAllLayers(void);
int MiniMap_ShowUnitsOnly(void);
int MiniMap_ShowBuildingsOnly(void);
int MiniMap_Hide(void);
signed int  UI_MenuHitTestEntry(_WORD *menu);
BOOL  WorldMap_HandleTopMenuBar(char a1, int a2);
_DWORD * WorldMapTopMenu_LoadSpriteSet(void);
int WorldMapTopMenu_FreeSpriteSet(void);

/* Deliberate unprototyped residue: recovered call sites depend on K&R semantics
 * (varying arity) or the slot type is unrecovered; kept verbatim as provenance. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
extern void WorldMap_EnableFrameRedraw();
extern int Font_InitGlyphFallbackTablesForLanguage();
extern void MiniMap_RedrawAllTiles();
#pragma GCC diagnostic pop

#endif /* CLASH95_WORLD_INTERNAL_H */
