/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/persistence/00446230_00447840_persistence_003.cpp' (6); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00446230_00447840_PERSISTENCE_003_LOCAL_H
#define CLASH95_TU_00446230_00447840_PERSISTENCE_003_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE void QueenMarriageProposal_WriteButtonWidgetRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, _DWORD **sprite_set_holder, const char *sound_name) CLASH95_LOCAL_SYMBOL(QueenMarriageProposal_WriteButtonWidgetRecord);
CLASH95_TEST_VISIBLE void QueenMarriageProposal_RebuildButtonWidgets (unsigned char *widgets, _DWORD **sprite_set_holder, int confirm_left, int top, int cancel_left) CLASH95_LOCAL_SYMBOL(QueenMarriageProposal_RebuildButtonWidgets);
CLASH95_TEST_VISIBLE void YesNoWindow_WriteButtonWidgetRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback) CLASH95_LOCAL_SYMBOL(YesNoWindow_WriteButtonWidgetRecord);
CLASH95_TEST_VISIBLE void YesNoWindow_RebuildButtonWidgets (unsigned char *widgets, int confirm_left, int top, int cancel_left) CLASH95_LOCAL_SYMBOL(YesNoWindow_RebuildButtonWidgets);
CLASH95_TEST_VISIBLE void MainMenu_WriteButtonWidgetTemplateRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, const char *sound_name) CLASH95_LOCAL_SYMBOL(MainMenu_WriteButtonWidgetTemplateRecord);
CLASH95_TEST_VISIBLE void CampaignMenu_WriteButtonWidgetTemplateRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, const char *sound_name) CLASH95_LOCAL_SYMBOL(CampaignMenu_WriteButtonWidgetTemplateRecord);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00446230_00447840_PERSISTENCE_003_LOCAL_H */
