/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'persistence': functions defined here and referenced from another subsystem (54). */
#ifndef CLASH95_PERSISTENCE_API_H
#define CLASH95_PERSISTENCE_API_H

#include "../recovered_types.h"

int  Audio_PlayUnitMeleeAttackSound(int result);
int  Audio_PlayUnitShotSound(int result);
void  Audio_PlayWorldMapUnitMoveSound(int tileRow, int tileColumn, signed int moveStepCounter, unsigned int unitTypeId);
void  Audio_PlayBattleMapUnitMoveSound(int tileRow, int tileColumn, signed int moveStepCounter, unsigned int unitTypeId);
void Audio_StopUnitMoveSound(void);
char * Audio_PlayButtonSound(char *result);
int  Audio_PlayArtifactSound(int result);
int  Audio_PlaySoundEffectByName(char *soundName, int volume);
int  IO_QueryVTableStreamSize(int streamObject);
int  FileSystem_ResolveReadPath(char *relativePath, int quitOnFailFlag);
char  FileSystem_SetInstallRootPath(char *sourcePath);
char *FileSystem_GetInstallRootPath(void);
int  loadFileSusp(char *sourcePath, const CHAR *destPath);
int  Port_NewTurn(DWORD logContext);
int Port_IsReinforcementReady(void);
int * Port_GenerateApproachTrack(int unitStackIndex);
int  Port_CollectReinforcementShipment(int, char, DWORD, double);
void * UI_DrawPortStatusPanel(char a1, DWORD a2);
BOOL  MapTile_HasHiddenTreasure(int tileRow, int tileColumn);
signed int  Treasure_TryDigHere(int, char, DWORD, char, char *, double);
signed int  UnitStack_TryHide(int unitStackIndex, unsigned __int16 neighborStackIndex, DWORD a3, double a4);
signed int  UnitStack_RevealHiddenEnemiesAndAttackAdjacent(unsigned int attackingStackIndex, double a2);
signed int  saveGame(int slotIndex, DWORD headerBuffer, double a3);
signed int  SaveSlot_LoadGame(int slotIndex, DWORD a2, double a3);
int  SaveSlotDialog_Run(int a1, char a2, DWORD a3, double a4);
int  UI_ShowInfoWindow(const char *a1, unsigned int windowStyle, int a3, DWORD a4, int windowLeft, int windowTop);
int  WorldMap_NotifyPlagueOutbreak(int a1, const char *a2, DWORD a3);
int  UI_ShowTechnologyLevelUpIfChanged(int a1, DWORD a2);
char  Building_ShowConstructionFinishedDialog(int building, int a2, char spriteSetName, DWORD a4);
int  Demo_ShowNumberedTextScreen(char spriteSetName, DWORD a2);
int  Queen_ShowWhimDecisionDialog(int a1, int requiredAmount, int a3, int a4, DWORD a5);
int  YesNoWindow(int a1, _BYTE *imageData, int a3, char a4, DWORD a5);
int  UI_ShowSimpleTextInfoWindow(int a1, int a2, char a3, DWORD a4);
int  Queen_ShowMarriageProposalDialog(int a1, char a2, DWORD a3);
int  Queen_ShowMessageDialog(int a1, int a2, char a3, DWORD a4);
int  UI_ShowMissionStatusPanel(int a1, DWORD a2);
int Debug_GetUsedMemoryCount(void);
signed int  UI_WaitForKeyOrTimeout(int timeoutMs, int a2);
signed int  UI_WaitForAnyKeyOrClick(int deadlineTime, int a2);
unsigned __int16 * Options_DrawAllSliderThumbs(unsigned __int16 *result, int a2, DWORD a3);
_DWORD * Options_AnimateAllSliderThumbs(_DWORD *result);
_DWORD * Options_DestroySliderThumbList(_DWORD *result);
void  Options_ApplyRecordSettings(int configRecord, int a2, DWORD a3);
char  Game_ResetPlayerRuntimeStateByIndex(int playerIndex);
int  Map_LoadFromFile(uintptr_t mapName);
signed int Game_InitPlayerViewState(void);
BOOL  UI_RunHoverTooltipZones(__int16 *tooltipZoneTable);
signed int  Prisoner_QueueCapturedUnit(char capturedUnitType, int capturedUnitOwner, __int16 a3, int playerIndex, DWORD a5, __int16 a6);
signed int  Prisoner_SetInCastles(int a1, char a2, DWORD a3);
int  Prisoner_Kill(int buildingRecord, char prisonerSlot, DWORD a3);
int  Building_CreateSpecialPersonageGarrisonUnit(DWORD buildingRecord, unit_type unitType, int a3, char prisonerSlot, double a5);
char  Prisoner_NewTurn(DWORD buildingRecord, int a2, char a3, double a4);
int  Building_CountPrisoners(int buildingRecord);
int  Building_ShowPrisonerManagementPanel(int buildingRecord, void *a2, DWORD a3);

#endif /* CLASH95_PERSISTENCE_API_H */
