/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Home-only functions of 'persistence' (77); private to the subsystem. */
#ifndef CLASH95_PERSISTENCE_INTERNAL_H
#define CLASH95_PERSISTENCE_INTERNAL_H

#include "persistence_api.h"

int  FileSystem_InitRootMount(int a1, char a2, DWORD a3);
int  FileSystem_MountArchiveAtIndex(int mountPrefix, const CHAR *archiveFileName, DWORD mountFlags);
int __thiscall ResourceArchives_MountStartupArchives(int this);
int Port_FindAndInit(void);
_DWORD *Rules_LogPortLocation(void);
int Port_UpdateShorelineVariantTiles(void);
int Rules_RebuildTreasureFacts(void);
int  SaveSlot_FormatDataFilePath(int slotIndex, char *outPath);
int  SaveSlot_FormatFactsFilePath(int slotIndex, char *outPath);
signed int  saveGame(int slotIndex, DWORD headerBuffer, double a3);
char  SaveSlot_LoadLabelOrPlaceholder(int slotIndex, char *outLabelBuffer, DWORD a3);
int  SaveSlot_HasDataFile(int slotIndex, DWORD a2);
int  SaveSlotDialog_RepaintRow(int a1);
int  SaveSlotDialog_HandleCancel(int result, int delay);
signed int  SaveSlotDialog_HandleConfirm(int widgetHandle, int delay, DWORD a3, double a4);
int  UI_CheatEditRepaint(DWORD backdropSurface, int a2);
int  DecisionDialog_ConfirmIfAllowed(uintptr_t a1, int a2);
int  DecisionDialog_Cancel(uintptr_t a1, int a2);
int __thiscall Object_ConstructInt256Array(void *this);
int  MainMenu_RequestExit(uintptr_t widget);
void MainMenu_RebuildButtonWidgetTemplate(void);
void CampaignMenu_RebuildButtonWidgetTemplate(void);
void LoadMenu_RebuildButtonWidgetTemplate(void);
void Options_RebuildMainMenuWidgetTemplates(void);
int  MainMenu_RequestCampaignMenu(uintptr_t widget);
int  MainMenu_RequestMultiplayerMenu(uintptr_t widget);
int  MainMenu_RequestCreditsCinematic(uintptr_t widget);
int  MainMenu_RequestOptionsMenu(uintptr_t widget);
int  MainMenu_RequestLoadGameMenu(uintptr_t widget);
DWORD  UI_StartAnims(int a1, char a2, DWORD a3);
int  PlayGame_Dispatch(int a1, signed int a2, char *a3, double a4);
int  MultiplayerSetup_HandleConfirmButtonRelease(uintptr_t widgetRecord);
int  MultiplayerSetup_HandleCancelButtonRelease(uintptr_t widgetRecord);
int  MultiplayerSetup_RepaintPlayerSlotRow(int slotRow, int a2, int a3);
signed int  MultiplayerSetup_HandleStartButtonRelease(int widgetRecord);
int  MultiplayerSetup_HandleBackButtonRelease(int widgetRecord);
int MultiplayerSetup_RedrawPlayerSlotIcons(void);
int MultiplayerSetup_RedrawOpponentNameList(void);
int  MultiplayerSetup_HandleScrollListDownButton(int widgetRecord);
int  PlayGameMenu_HandleScrollButtonRelease(int widgetRecord);
void  Options_ApplyMainMenuSliders(int a1, DWORD a2);
int  PlayGameMenu_HandleCloseButton(uintptr_t widgetRecord);
unsigned __int16 * Options_InitMainMenuSlidersAndWidgets(uintptr_t widgetRecord, int a2, DWORD a3);
BOOL  Options_ToggleCheckboxMainMenu(uintptr_t widgetRecord);
int  LoadMenu_HandleSlotConfirmButtonRelease(int widgetRecord, DWORD a2);
void * LoadMenu_RedrawSaveSlotRow(int slotRow, DWORD a2);
int  Options_DrawSliderThumb(unsigned __int16 *sliderRecord, char a2, DWORD a3);
unsigned int  Options_AnimateSliderThumbDrag(int sliderRecord);
void  lodaOptionsCfg(DWORD a1);
int  Options_SaveConfigToFile(int a1, DWORD a2);
char  PlayerRuntimeState_ResetDefaults(uintptr_t playerState);
char Scenario_SetupSirArthurRosterVariantA(void);
char Scenario_SetupSirArthurRosterVariantB(void);
_DWORD * Scenario_SeedCantbellyAndKopegonCastles(int this, DWORD a2, double a3);
signed int  SaveSlot_LoadReservedSlot10(DWORD a1, double a2);
signed int  Scenario_LoadAllAiMultiplayerMapAndInitView(int mapIndex);
DWORD  Battle_RunPresetScenarioByIndex(int scenarioIndex, DWORD a2, double a3);
signed int  Scenario_LoadMultiplayerMapAndSeedPlayers(int mapIndex, uintptr_t playerStatesSource);
char  Player_AssignRandomUniqueRulerNames(int requestedNameCount, int *nameSlotPtrs);
signed int  Building_FindFreePrisonerSlot(int buildingRecord);
int  BuildingPrisoner_RecalculateRansomValue(int prisonerRecord);
int  BuildingPrisoner_SetAction(int a1, char actionCode, DWORD a3);
int  BuildingPrisoner_GetAction(int buildingRecord, int prisonerSlot);
int  Prisoner_Behead(int buildingRecord, int prisonerRecord, char slotIndex, DWORD a4);
BOOL  Building_IsVisibleToPlayer(unsigned __int8 *buildingCoords, int playerIndex);
int  Prisoner_FindRichestHiddenEnemyCastle(int enemyPlayerIndex, int viewerPlayerIndex);
int  Prisoner_FindAnyHiddenEnemyCastle(int enemyPlayerIndex, int viewerPlayerIndex);
int  Prisoner_FindAnyHiddenEnemyUnitStack(int enemyPlayerIndex, int viewerPlayerIndex);
void  Map_RevealTilesInRadius2ForPlayer(int centerRow, int centerColumn, int playerIndex);
unsigned int  Prisoner_Torture(int buildingRecord, int prisonerSlot, int prisonerRecord, char slotIndex, DWORD a5);
unsigned int  Prisoner_Pay(int a1, int prisonerSlot, DWORD a3, double a4);
BOOL  BuildingPrisonerActionWidget_HasPrisoner(int widgetRecord);
char * BuildingPrisonerActionButton_SelectBehead(int widgetRecord);
char * BuildingPrisonerActionButton_SelectTorture(int widgetRecord);
char * BuildingPrisonerActionButton_SelectBribery(int widgetRecord);
int  BuildingPrisonerPanel_BackButton(int widgetRecord);
int  Building_DrawPrisonerRows(DWORD a1);
int  Queen_DrawRelationshipPanel(DWORD a1, int a2);

#endif /* CLASH95_PERSISTENCE_INTERNAL_H */
