/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'persistence' (33); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_PERSISTENCE_SHARED_STATE_H
#define CLASH95_PERSISTENCE_SHARED_STATE_H

#include "../recovered_types.h"

extern int Map_NeighborDX[64];
extern int Map_NeighborDY[63];
extern char a1[3];
extern char a2[3];
extern char aIOCouldnTOpenF[29];
extern int g_ActiveCursorDescriptor;
extern int g_ActiveCursorDescriptorPtr;
extern int g_ActiveTextSpriteSlot;
extern int g_CurrentPlayerIndex;
extern char g_CursorCoordShift;
extern int g_CursorDesc_Default[10];
extern int g_CursorOverlayPresented;
extern int g_FileSystemMountOpenMode;
extern int g_FileSystemMountTable[11];
extern InputBackendState g_InputBackendState;
extern char g_LanguageIndex;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_MapPalettePtr;
extern unsigned char g_Mission17ScriptedTreasureEventData[];
extern unsigned char g_Mission7ScriptedTreasureEventData[];
extern int g_PrimaryRenderSurface;
extern CLASH95_INTERNAL uintptr_t g_QueenMarriageProposalWidgetTableBase;
extern _UNKNOWN *g_RenderDevice;
extern int (*g_RenderHook)(int a1, char a2, DWORD a3);
extern _DWORD g_RenderState[286];
extern _UNKNOWN g_Runtime_PaletteArrayCtorDescriptor;
extern int g_SelectedUnitIndex;
extern unsigned char g_TreasureDigOutcomeTable_AI[];
extern unsigned char g_TreasureDigOutcomeTable_Human[];
extern int g_UnitSoundsEnabled;
extern CLASH95_INTERNAL const UnitTypeRuntimeCoreMetadataRecord g_UnitTypeRuntimeCoreMetadata[UNIT_TYPE_METADATA_CAPACITY];
extern CLASH95_INTERNAL const UnitTypeRuntimePointerRecord g_UnitTypeRuntimePointers[UNIT_TYPE_METADATA_CAPACITY];
extern int gameData;

#endif /* CLASH95_PERSISTENCE_SHARED_STATE_H */
