/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/units/0041A960_0041C8B0_units_007.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0041A960_0041C8B0_UNITS_007_LOCAL_H
#define CLASH95_TU_0041A960_0041C8B0_UNITS_007_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL int Diagnostics_ForceAutoresolveEnabled(void) CLASH95_LOCAL_SYMBOL(Diagnostics_ForceAutoresolveEnabled);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0041A960_0041C8B0_UNITS_007_LOCAL_H */
