/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/units/004191F0_0041A690_units_006.cpp' (4); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_004191F0_0041A690_UNITS_006_LOCAL_H
#define CLASH95_TU_004191F0_0041A690_UNITS_006_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE int UI_InvokeWidgetTransitionCallback (uintptr_t widget, int callback_arg) CLASH95_LOCAL_SYMBOL(UI_InvokeWidgetTransitionCallback);
CLASH95_TEST_VISIBLE int UI_InvokeWidgetActionCallback (uintptr_t widget) CLASH95_LOCAL_SYMBOL(UI_InvokeWidgetActionCallback);
CLASH95_TEST_VISIBLE unsigned int Compat_WidgetPackedField (uintptr_t widget, unsigned int field_offset) CLASH95_LOCAL_SYMBOL(Compat_WidgetPackedField);
CLASH95_TEST_VISIBLE unsigned int Compat_WidgetSpriteSetHandle (uintptr_t widget) CLASH95_LOCAL_SYMBOL(Compat_WidgetSpriteSetHandle);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_004191F0_0041A690_UNITS_006_LOCAL_H */
