/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/units/00412C00_00414350_units_003.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00412C00_00414350_UNITS_003_LOCAL_H
#define CLASH95_TU_00412C00_00414350_UNITS_003_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE const char *UnitType_GetResourceKey (int unit_type) CLASH95_LOCAL_SYMBOL(UnitType_GetResourceKey);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00412C00_00414350_UNITS_003_LOCAL_H */
