/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Home-only functions of 'units' (71); private to the subsystem. */
#ifndef CLASH95_UNITS_INTERNAL_H
#define CLASH95_UNITS_INTERNAL_H

#include "units_api.h"

extern short int *UnitStack_RemoveFromTile (short int *stack, double a2);
extern short int *UnitStack_UnlinkIfEmpty (short int *result, double a2);
signed int  UnitStack_HasReadyUnits(int stackPtr);
__int16 * UnitStack_ClearReadyFlags(int stackPtr);
int  UnitSlot_CalcActionPointsFromFatigue(__int16 *slotPtr);
int  UnitSlot_GetBaseActionPoints(__int16 *slotPtr);
signed int WorldMap_HandleViewportScrollKeys(void);
signed int  UnitStack_HasPlagueFlag(int stackPtr);
int  UnitStack_SpendActionPointsUnchecked(int stackPtr, char spendAmount);
signed int  UnitStack_SubtractActionPointsFloorZero(__int16 *stackPtr, int subtractAmount, DWORD a3, double a4);
signed int  UnitStack_CanReachQueuedPathTileWithFogOverlay(__int16 *stackPtr, int animate);
int  UnitStats_CalcEffectiveMeleeAttack(char *slotPtr, int forceMaxLevel);
int  UnitStats_GetMeleeIconIndex(__int16 *slotPtr);
int  UnitStats_CalcEffectiveDefensePower(char *slotPtr, int forceMaxLevel);
int  UnitStats_GetDefenseIconIndex(__int16 *slotPtr);
int  UnitStats_CalcEffectiveShotPower(__int16 *slotPtr);
int  UnitStats_GetBaseShotPower(__int16 *slotPtr);
int  UnitStats_CalcEffectiveWallAttack(char *slotPtr, int forceMaxLevel);
extern int Debug_LogUnitSquadDetails (int stackPtr, DWORD a2);
extern int Unit_DebugDumpFormationSizesForStackIndex (int stackIndex, DWORD a2);
_WORD * UnitSlots_RemoveGaps(_WORD *result, int slotCount);
void  Unit_CheckLowMorale(_BYTE *stackPtr, double a2);
signed int  UnitStack_ApplyPlagueAttritionToPeasantCargo(__int16 *stackPtr, DWORD a2, double a3);
BOOL  UnitSlot_ShouldGainFatigueFromLowActionPoints(int slotPtr);
BOOL  UnitSlot_CanRecoverFatigue(int slotPtr);
BOOL  UnitSlot_HasSevereFatigue(int slotPtr);
__int16  Map_RedrawUnitFootprintByIndex(int stackIndex);
int  Unit_GetSpriteVerticalOffsetPx(int stackIndex);
void * UnitSlots_ExtractSpecialEntries(char *slotArray, int slotCount, char *extractedOut);
extern void *UnitSlots_ExtractSpecialEntriesForBuildingAttack (char *slotArray, int slotCount, char *extractedOut);
int  UnitSlots_AppendEntries(char *destSlots, char *srcSlots);
extern int UnitSlots_AppendEntriesForBuildingAttack (char *destSlots, char *srcSlots);
signed int  UnitStack_NormalizePeasantCargo(__int16 *stackPtr, DWORD a2, double a3);
__int16 * UnitStack_SetSpentTurnFlag(int stackPtr);
__int16 * UnitStack_ClearSpentTurnFlag(int stackPtr);
int  UnitSlots_CalcCombatStrengthScoreWithSpecialPersonageCheck(char *slotArray, int slotCount, int wallDefenseBonus);
int  UnitStack_CalcMilitaryStrength(int stackPtr);
int  Building_CalcGarrisonStrength(int buildingRecord, signed int playerIndex);
_DWORD * UnitTrackElementStack_BuildBlank(_DWORD *result);
int  UnitStack_CopyFromTemplate(int destStack, int srcStack, int a3);
extern int BattleUnitEntry_CopyMergingPackedFlags (int result, int srcEntry);
int  UnitTrackElementStack_CopyFromTemplate(_DWORD *destStack, _DWORD *srcStack, int a3);
int  UnitTrackElement_CopyFromTemplate(int result, int srcElement);
extern int UnitSpriteCache_GetOrLoadEntry (short unsigned int unitType, char ownerColor, unsigned char animFrame, unsigned char facing, DWORD a5, int a6);
int  Unit_SetFlag(unsigned __int16 unitType, char ownerColor, unsigned __int8 animFrame, unsigned __int8 facing, DWORD a5, signed int a6);
signed int  UnitStack_BuildMergedTerrainMoveProfile(intptr_t profileRecord, intptr_t stackRecord);
signed int  UnitStack_GetTileMoveCostFromMergedProfileOrZero(__int16 *stackPtr, intptr_t mergedProfile, int tileColumn, int tileRow);
signed int  UnitStack_GetMoveCostToTile(int stackIndex, int tileRow, int tileColumn);
signed int  UnitStack_GetMoveCostToTileIgnoringOccupancy(__int16 *stackPtr, int tileRow, int tileColumn);
int * Path_InsertBridgeCornerWaypoints(int stackRecord, char a2, int *pathBuffer);
void  initRandomSeed(char a1, DWORD a2);
__int16  WorldMap_DrawUnitStackOverlayGlyph(int screenX, int screenY, unsigned __int16 *tilePtr);
int  WorldMap_DrawUnitStackWithOverlays(int result, int screenX, int screenY, int animOffsetY, unsigned __int16 *tilePtr);
int  WorldMap_DrawUnitAttentionFlashGlow(int screenX, int screenY, unsigned int buildingPhase);
int  WorldMap_DrawMapTile(unsigned __int16 screenX, unsigned __int16 screenY, unsigned __int16 *tilePtr);
void UI_UpdateWorldMapUnitAttentionFlash(void);
BOOL UI_IsWorldMapUnitAttentionFlashActive(void);
void __fastcall UI_UpdateUnitBlinkFlash(int a1, int a2);
int  UI_DrawTileHighlightOverlay(int tileX, int tileY, int screenLeft, int screenTop);
void  createLogFiles(int a1, int a2, DWORD a3);
int  UI_DrawWidgetIconWithTransition(unsigned __int16 *a1, int animate, int transitionDuration, DWORD allocContext);
BOOL  UIWidget_ShowTextWithFadeTransition(uintptr_t a1, DWORD allocContext);
signed int  UIWidget_PollHitHoverAndClick(uintptr_t widget, DWORD a2);
int  UI_DrawUnitInfoPane(int panelLeftArg, int panelTopArg, int a3, __int16 *slotRecordArg, DWORD allocContext, int drawContext);
int  UI_DrawSpecialUnitInfoPane(int a1, int a2, int a3, unsigned __int8 *unitRecord, DWORD allocContext, int iconSpriteIndex);
int  UnitSlots_CalcCombatStrengthScore(char *slotArray, int slotCount, int statContext, int wallDefenseBonus);
int  UnitSlots_CalcDefenseScore(char *slotArray, int slotCount, int statContext);
int  Building_ApplySiegeDamageToWallSections(int buildingRecord, signed int siegeDamage);
int  Building_CalcWallDefenseBonus(int buildingRecord, signed int weakestSection);
int  CalculateBattleResult(_WORD *, int, _WORD *, int, DWORD, int, int, int, int);
signed int  UI_PromptLeadTroopsPersonally(int attackerSlots, int attackerCount, int defenderCount, int defenderSlots, DWORD a5, int a6, int showThirdOption);

#endif /* CLASH95_UNITS_INTERNAL_H */
