/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'units' (53); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_UNITS_SHARED_STATE_H
#define CLASH95_UNITS_SHARED_STATE_H

#include "../recovered_types.h"

extern _BYTE BuildingGarrisonDialogActions[WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * (BUILDING_GARRISON_DIALOG_WIDGET_COUNT + 1)] __attribute__((aligned(4)));
extern int Map_NeighborDX[64];
extern int Map_NeighborDY[63];
extern char a1[3];
extern char a2[3];
extern int g_ActiveCursorDescriptor;
extern int g_ActiveCursorDescriptorPtr;
extern int (*g_ActiveDialogAnimationTickHook)(void);
extern int g_ActiveTextSpriteSlot;
extern int g_ActiveUiSpriteSet;
extern int g_ActiveUnitAnimSpriteSet;
extern int g_ActiveUnitMoveTileIndex;
extern int g_ActiveWidgetSpriteTableIndex;
extern CLASH95_INTERNAL int g_BuildingNewOverrideActive;
extern CLASH95_INTERNAL int g_BuildingNewOverrideColumn;
extern CLASH95_INTERNAL int g_BuildingNewOverrideRow;
extern __int16 g_BuildingTypeMaxHitPoints[4];
extern int g_CurrentPlayerIndex;
extern char g_CursorCoordShift;
extern int g_CursorDesc_Busy[10];
extern int g_CursorDesc_Default[10];
extern int g_CursorOverlayPresented;
extern int g_FlagSpriteSet;
extern int g_FogOverlaySpriteSet;
extern char g_LanguageIndex;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_MapPalettePtr;
extern int g_MarksSpriteSet;
extern int g_MovePathStepSpriteSet;
extern int g_PrimaryRenderSurface;
extern CLASH95_INTERNAL uintptr_t g_QueenMarriageProposalWidgetTableBase;
extern _UNKNOWN *g_RenderDevice;
extern int (*g_RenderHook)(int a1, char a2, DWORD a3);
extern _DWORD g_RenderState[286];
extern unsigned short g_Render_AnimatedFrameTable[1038];
extern char g_Render_BackgroundColorIndex;
extern int g_SavedCursorDescriptor;
extern int g_SelectedUnitIndex;
extern int g_TreeSpriteSet;
extern int g_UnitAnimFrameIndex;
extern _BYTE g_UnitBattleActionWidgetTable[WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * (UNIT_BATTLE_ACTION_WIDGET_COUNT + 1)] __attribute__((aligned(4)));
extern int g_UnitMoveAnimOffsetX;
extern int g_UnitMoveAnimOffsetY;
extern int g_UnitStackSelectionModeActive;
extern CLASH95_INTERNAL const UnitTypeRuntimeCoreMetadataRecord g_UnitTypeRuntimeCoreMetadata[UNIT_TYPE_METADATA_CAPACITY];
extern CLASH95_INTERNAL const UnitTypeRuntimePointerRecord g_UnitTypeRuntimePointers[UNIT_TYPE_METADATA_CAPACITY];
extern __int16 g_WallKindDefenseFactor[5];
extern int g_WhirlSpriteSet;
extern _BYTE g_WorldMapActionButtonWidgetTable[WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * (WORLD_MAP_ACTION_WIDGET_COUNT + 1)] __attribute__((aligned(4)));
extern int g_WorldMapBackgroundSpriteSet;
extern int (__fastcall *g_WorldMapTileOverlayDrawHook)(_DWORD, _DWORD);
extern int g_WorldMapViewportScrolledFlag;
extern int gameData;

#endif /* CLASH95_UNITS_SHARED_STATE_H */
