/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'units': functions defined here and referenced from another subsystem (116). */
#ifndef CLASH95_UNITS_API_H
#define CLASH95_UNITS_API_H

#include "../recovered_types.h"

signed int  Unit_Create();
unsigned int  UnitStack_LinkArmyFact(__int16 *stackPtr, char a2, DWORD a3);
int  Unit_Kill(int stackRecord, char killReason, DWORD a3, double a4);
int  UnitStack_KillByIndex(int stackIndex, char killReason, DWORD a3, double a4);
__int16 * Rules_UnlinkArmyFact(__int16 *result, double a2);
__int16 * Rules_LinkArmyFinalize(__int16 *result, double a2);
int  UnitStack_GetVisionRadius(int stackPtr);
signed int  UnitStack_UpdateVision(int stackIndex);
__int16 * UnitStack_SetReadyFlags(int stackPtr);
signed int  Facing_DirectionFromDelta8(int deltaRow, int deltaColumn);
int  Camera_CenterOnUnit(int stackIndex);
int  UnitStack_GetMinBaseActionPoints(int stackPtr);
__int16 * UnitStack_ClearRemainingActionPoints(__int16 *result, DWORD a2, double a3);
signed int  UnitStack_GetMinCurrentActionPoints(intptr_t stackPtr);
signed int  UnitStack_GetMaxOrderTier(intptr_t stackPtr);
signed int  UnitStack_SpendActionPointsClamped(__int16 *stackPtr, int spendAmount, DWORD a3, double a4);
signed int  UnitStack_SpendActionPointsByIndexClamped(int stackIndex, int spendAmount, DWORD a3, double a4);
void  UnitStack_ExecuteQueuedPath(unsigned int stackIndexArg, int animateArg, char a3, DWORD a4, double a5);
int  UnitStats_CalcEffectiveMeleeAttack(char *slotPtr, int forceMaxLevel);
int  UnitStats_GetMeleeIconIndex(__int16 *slotPtr);
int  UnitStats_CalcEffectiveDefensePower(char *slotPtr, int forceMaxLevel);
int  UnitStats_GetDefenseIconIndex(__int16 *slotPtr);
int  UnitStats_CalcEffectiveShotPower(__int16 *slotPtr);
int  UnitStats_GetBaseShotPower(__int16 *slotPtr);
int  UnitStats_CalcEffectiveWallAttack(char *slotPtr, int forceMaxLevel);
signed int  Unit_DebugDumpFormationSizes(int stackRecord, DWORD a2);
signed int  Render_DrawSprite_v3(int stackIndex, DWORD a2);
signed int  LogAllUnits(int a1, char a2, DWORD a3);
signed int  Unit_CompactSquad(__int16 *stackPtr, int a2, double a3);
signed int  Unit_NewTurn(int a1, char a2, DWORD a3, double a4);
signed int  UnitStack_HasBuilder(int stackIndex);
int  Map_RedrawUnitNeighborhoodByIndex(int stackIndex);
void Map_UpdateIdleAnimatedUnits(void);
signed int  Unit_AttemptNeighborMove(int stackIndex);
BOOL  UnitStack_CanExecuteQueuedPathNow(int stackIndex);
signed int  UnitStack_HasNormalCombatUnits(intptr_t stackPtr);
signed int  UnitStack_HasGoldCargo(int stackPtr);
signed int  UnitStack_HasPeasantCargo(int stackPtr);
__int16 * UnitStack_CaptureDefeatedStack(__int16 *winnerStack, signed int defeatedStackPtr, int a3, int a4, double a5);
int  Unit_CreateNearbyUnitGroup(int originRow, int originColumn, unsigned __int8 *sourceSlots, double a4);
int  UnitSlot_AdjustFatigueByPredicate(int a1, int a2, BOOL ( *a3)(int a1)); // idb
CLASH95_INTERNAL BOOL UnitSlot_PredicateAlways (int slotPtr);
signed int  UnitStack_AdjustFatigueByPredicate(__int16 *a1, int a2, BOOL ( *a3)(int a1), DWORD a4, double a5);
int  UnitSlot_AdjustMoraleByPredicate(int a1, int a2, BOOL ( *a3)(int a1));
signed int  UnitStack_AdjustMoraleByPredicate(__int16 *a1, int a2, BOOL ( *a3)(int a1), DWORD a4, double a5);
int  UnitSlot_CycleOrderState(int result);
signed int  UnitStack_CycleAllSlotOrders(__int16 *stackPtr, DWORD a2, double a3);
int  UnitStack_SetPlagueFlag(int result);
signed int  UnitStack_HasPlague(int stackPtr);
signed int  UnitStack_HasLowMoraleUnit(int stackPtr);
int  UnitStackSelection_BuildSelectedSlotIndexList(int result, int slotCount, int *selectedOut);
signed int  UnitStack_HasSpecialPersonageUnits(intptr_t stackPtr);
int  Player_CalcMilitaryStrength(signed int playerIndex);
int UnitSpriteCache_ClearAllEntries(void);
int  UnitSpriteCache_FindEntryOrLoad(signed int unitType, char ownerColor, unsigned __int8 animFrame, unsigned __int8 facing);
void  UnitSpriteCache_FreeAllEntries(int a1, DWORD a2);
int UnitSpriteCache_CountActiveEntries(void);
char  Unit_BuildGoSpriteFilePath(char *destPath, unsigned __int8 unitType, char variantDigit);
char  UI_BeginUnitInfo(char *destPath, unsigned __int8 unitType, char variantDigit);
char  Unit_BuildGarrisonSlotIconSpritePath(char *destPath, unsigned __int8 unitType, int a3);
char  Unit_BuildSelectedUnitPanelIconSpritePath(char *destPath, unsigned __int8 unitType, int a3);
char  Unit_BuildSelectedUnitPanelIconPalettePath(char *destPath, unsigned __int8 unitType, int a3);
char  Unit_BuildAttackAnimSpritePath(char *destPath, unsigned __int8 unitType, char variantDigit);
char  Unit_BuildShotAnimSpritePath(char *destPath, unsigned __int8 unitType, char variantDigit);
char  Unit_BuildShotAnimPaletteSpritePath(char *destPath, unsigned __int8 unitType);
void  Unit_BuildBigInfoGraphicPath(char *destPath, unsigned __int8 unitType, int a3);
signed int Map_InitTerrainMoveTableOffsets(void);
int  Map_GetUnitTileMoveCostOrZero(int playerIndex, int unitType, int tileColumn, int tileRow);
signed int  UnitStack_GetTileMoveCostOrZero(__int16 *stackPtr, int tileRow, int a3, int tileColumn);
int * Unit_MoveTrack(int stackIndex, int sourceRow, int targetRow, int sourceColumn, DWORD availableActionPoints, int targetColumn);
_DWORD * Unit_MoveTrackNearTile(int stackIndex, int targetRow, int a3, int targetColumn, DWORD a5);
int * Building_GenerateApproachTrack(int stackIndex, int buildingIndex, int a3, char a4, DWORD a5);
int  Building_GenerateNearApproachTrack(int stackIndex, int buildingIndex, int a3, char a4, DWORD a5);
void  Pathing_EnableBridgeCrossings(int a1, char a2, DWORD a3);
void  Pathing_DisableBridgeCrossings(int a1, char a2, DWORD a3);
BOOL  QueuedPath_StartsAtTile(_DWORD *pathBuffer, int tileRow, int tileColumn);
BOOL  QueuedPath_StartsInBuildingFootprint(_DWORD *pathBuffer, int buildingIndex);
int  Math_SinDegreesQ16(signed int degrees);
unsigned int  Rng_RandRange(int minValue, int maxValue);
signed int  Math_CeilSqrt(signed int value);
unsigned int __thiscall Map_InitBuildingSwayJitterOffsets(void *this);
unsigned __int8 *__thiscall Map_UpdateConstructionSiteSwayAnimation(void *this);
unsigned int __thiscall Map_UpdateIdleAnimatedBuildings(void *this);
int  WorldMap_RedrawViewport(int presentCursorOverlay);
int  WorldMap_RedrawTileIfVisible(int result, int tileColumn);
int  UI_CenterWorldMapViewportOnRectIfFit(int result, int rectColMin, int rectColMax, int rectRowMax);
int  UI_CenterWorldMapViewportOnTile(int tileRow, int tileColumn);
int  UI_StartWorldMapUnitAttentionFlash(int unitIndex, int a2, int a3);
int  UI_StartUnitBlinkFlash(int unitIndex, int a2, int a3);
int  UI_StartTileBlinkFlash(int tileX, int tileY, int a3);
void __fastcall UI_UpdateTileBlinkFlash(int a1, int a2);
signed int  UI_HighlightTile(int tileX, int tileY);
int __thiscall UI_ClearTileHighlight(void *this);
void BattleLog_Disable(void);
void BattleLog_Enable(void);
int  Battle_StoreLastOutcomeValue(int result);
CLASH95_INTERNAL int Compat_CountPrintfArgs32 (const char *format);
void  Debug_Log(int a1, char a2, DWORD a3, int a4, ...);
unsigned __int16 * UI_DrawWidgetIcon(unsigned __int16 *result, int doRefresh);
CLASH95_INTERNAL int Compat_RenderDeviceFillSolidRect(
        unsigned __int16 left,
        unsigned __int16 top,
        unsigned __int16 right,
        unsigned __int16 bottom,
        unsigned char color);
CLASH95_INTERNAL int Compat_RenderSurfaceCopyRect(
        _DWORD *source,
        _DWORD *destination,
        int source_left,
        int source_top,
        int source_right,
        int source_bottom,
        int destination_left,
        int destination_top);
CLASH95_INTERNAL int Compat_RenderDeviceDrawMenuSprite(int left, int top, int sprite_for_char, unsigned char draw_mode);
int  UI_DrawWidgetIconTransitionSlow(unsigned __int16 *a1, int a2, DWORD a3);
int  UI_DrawWidgetIconTransitionFast(unsigned __int16 *a1, int a2, DWORD a3);
CLASH95_INTERNAL const char *Compat_WidgetPackedString(uintptr_t widget, unsigned int field_offset);
int  UI_SetActiveWidgetTable(int result);
int  UIWidget_RefreshActionButtonState(uintptr_t result, int callbackArg);
_DWORD * UIWidgetTable_InitDrawStates(_DWORD *result);
signed int  UIWidgetTable_PollHoverAndActions(_DWORD *widgetTable, DWORD allocContext);
int  UIWidget_PlayPressedReleaseAnimationWithDelay(uintptr_t widget, int a2);
int  UIWidget_PlayPressedReleaseAnimation(uintptr_t widget);
int  UIWidget_ShowPressedState(uintptr_t widget);
int  UIWidget_ShowReleasedState(uintptr_t widget, int a2);
int  Unit_Info(int leftArg, int topArg, int a3, unsigned __int8 *unitRecord, DWORD allocContext, DWORD a6);
void  Unit_Attack(int attackerIndex, int defenderIndex, char a3, DWORD a4, double a5);
void  Unit_AttackBuilding(int attackerIndex, int buildingIndexArg, char a3, DWORD a4, double a5);

#endif /* CLASH95_UNITS_API_H */
