// Generated by tools/migrate_game_class_bodies.py; borrowed state only.
#pragma once
#include "../recovered_types.h"

namespace clash95 {
class CLASH95_INTERNAL UnitTurn final {
  using state_type_0 = char[15];
  using state_type_1 = __int16[4];
  using state_type_2 = int;
  using state_type_3 = int;
  using state_type_4 = int;
 public:
  static UnitTurn borrow() noexcept;
  _BYTE * Unit_NewTurnRegen(_BYTE *arg_0);
  int Unit_UpdatePerTurn(int arg_0, int arg_1);
  signed int Unit_NewTurn(int arg_0, char arg_1, DWORD arg_2, double arg_3);
 private:
  explicit UnitTurn(state_type_0 &arg_0, state_type_1 &arg_1, state_type_2 &arg_2, state_type_3 &arg_3, state_type_4 &arg_4) noexcept : state_field_0_(arg_0), state_field_1_(arg_1), state_field_2_(arg_2), state_field_3_(arg_3), state_field_4_(arg_4) {}
  state_type_0 &state_field_0_;
  state_type_1 &state_field_1_;
  state_type_2 &state_field_2_;
  state_type_3 &state_field_3_;
  state_type_4 &state_field_4_;
};
} // namespace clash95
