/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/state/00000000_00000000_prelude_helpers.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00000000_00000000_PRELUDE_HELPERS_LOCAL_H
#define CLASH95_TU_00000000_00000000_PRELUDE_HELPERS_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE uintptr_t RenderSurface_GetCompactMethodPointer (_DWORD *surface, unsigned int table_offset) CLASH95_LOCAL_SYMBOL(RenderSurface_GetCompactMethodPointer);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00000000_00000000_PRELUDE_HELPERS_LOCAL_H */
