/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'state': functions defined here and referenced from another subsystem (19). */
#ifndef CLASH95_STATE_API_H
#define CLASH95_STATE_API_H

#include "../recovered_types.h"

CLASH95_INTERNAL int Runtime_DescriptorNoop(void);
CLASH95_INTERNAL void Runtime_InitCompactEvalDescriptor(EvalNodeDescriptorCompact descriptor, uintptr_t evaluator);
CLASH95_INTERNAL void Render_InitRecoveredVtableStorage(void);
CLASH95_INTERNAL int RenderSurface_InvokeSlot60(_DWORD *surface);
CLASH95_INTERNAL int RenderSurface_InvokeSlot64(_DWORD *surface);
CLASH95_INTERNAL int RenderSurface_InvokeSlot0(_DWORD *surface, int flags);
CLASH95_INTERNAL int RenderSurface_InvokeSlot36(_DWORD *surface);
CLASH95_INTERNAL int RenderSurface_InvokeSlot48LoadPCX(_DWORD *surface, char *path, int transparent, uintptr_t palette);
CLASH95_INTERNAL int RenderSurface_InvokeSlot56(_DWORD *surface);
CLASH95_INTERNAL int RenderHandle_InvokeCopyDispatch(int source_handle, int destination_handle);
CLASH95_INTERNAL _DWORD *RenderSurface_ResolvePrimaryCompanion(_DWORD *surface);
CLASH95_INTERNAL int RenderSurface_IsLinearSoftware(_DWORD *surface);
CLASH95_INTERNAL int RenderSurface_InvokeSlot16ReadPixel(_DWORD *surface, int x, int y);
CLASH95_INTERNAL void RenderSurface_WriteSoftwarePixel(_DWORD *surface, unsigned int x, unsigned int y, unsigned char color);
CLASH95_INTERNAL void RenderSurface_FillSoftwareRect(
        _DWORD *surface,
        unsigned int x0,
        unsigned int y0,
        unsigned int x1,
        unsigned int y1,
        unsigned char color);
CLASH95_INTERNAL char *UnitType_GetLocalizedName(unit_type unitType);
CLASH95_INTERNAL unsigned char UnitType_GetWorldMoveCost(int unit_type, int profile_offset);
CLASH95_INTERNAL unsigned char UnitType_GetRoadMoveCost(int unit_type);
CLASH95_INTERNAL void Rules_EnsureObjectPatternVTable(void);

#endif /* CLASH95_STATE_API_H */
