/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Home-only functions of 'state' (0); private to the subsystem. */
#ifndef CLASH95_STATE_INTERNAL_H
#define CLASH95_STATE_INTERNAL_H

#include "state_api.h"


#endif /* CLASH95_STATE_INTERNAL_H */
