/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Globals referenced only within the state group itself (74); kept declared so definitions stay decl-checked. */
#ifndef CLASH95_STATE_LOCAL_H
#define CLASH95_STATE_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern _UNKNOWN Audio_MixMonoVoiceDispatch;
extern _UNKNOWN Audio_MixPannedVoiceDispatch;
extern _UNKNOWN Audio_SelectMixFormat1MonoDispatch;
extern _UNKNOWN Audio_SelectMixFormat1StereoDispatch;
extern _UNKNOWN Audio_SelectMixFormat2MonoDispatch;
extern _UNKNOWN Audio_SelectMixFormat2StereoDispatch;
extern _UNKNOWN Audio_SelectMixFormat3MonoDispatch;
extern _UNKNOWN Audio_SelectMixFormat3StereoDispatch;
extern _UNKNOWN Audio_SelectMixFormat4MonoDispatch;
extern _UNKNOWN Audio_SelectMixFormat4StereoDispatch;
extern _UNKNOWN Audio_SelectMixFormat5MonoDispatch;
extern _UNKNOWN Audio_SelectMixFormat5StereoDispatch;
extern char a03d02d02d[16];
extern char aA[2];
extern char aA_1[2];
extern char aBattle_log_0[11];
extern char aBudowaWarsztat[];
extern char aClash_log_0[10];
extern char aCultPlace[];
extern char aEmptyCultPlace[];
extern char aEmptyShrine[];
extern char aFoundations[];
extern char aFundamente[];
extern char aFundamenty[];
extern char aHiddenTreasure[];
extern char aIs_filepathO_0[21];
extern char aIs_filepathOpe[21];
extern char aKultstdtte[];
extern char aLeereKultstdtt[];
extern char aLeererSchrein[];
extern char aMiejsceKultu[];
extern char aPustaSwijtynia[];
extern char aPusteMiejsceKu[];
extern char aRb_3[3];
extern char aRb_4[3];
extern char aResetdefglobal[];
extern char aS_0[4];
extern char aSchrein[];
extern char aShrine[];
extern char aSwijtynia[];
extern char aVersteckterSch[];
extern char aViolationOfFun[47];
extern char aZ[2];
extern char aZakopanySkarb[];
extern char asc_4EDCFF[2];
extern _UNKNOWN g_Audio_DriverModuleTableBase;
extern char g_BattleStateRegionUnusedByte[];
extern _UNKNOWN g_BootstrapCursorDescriptor;
extern char g_BuildingSpriteCacheRegionBuffer13[13];
extern char g_CLIPS_BsaveHeaderMagic[12];
extern _UNKNOWN g_CRTWatcomEHFrameHandler_ScopeTable;
extern _UNKNOWN g_CRTWatcomEHHandleNestedException_ScopeTable;
extern int g_CastleSiteRegionUnusedDwordA;
extern int g_CastleSiteRegionUnusedDwordB;
extern _BYTE g_PaletteRegionUnusedBuffer5[5];
extern char g_PaletteRemapRegionUnusedByte;
extern int g_PortSpawnRingOffsetsOverlapTail[];
extern char g_QueenBirthMessageBuffer[];
extern _UNKNOWN g_QueenMarriageProposalButtonWidgetsTemplate;
extern double g_Rules_AcoshDomainLowerBound;
extern double g_Rules_AcothHalfCoefficient;
extern double g_Rules_AsechDomainLowerBound;
extern double g_Rules_AtanhHalfCoefficient;
extern _UNKNOWN g_Runtime_CompactEvalClipsSignature[10];
extern int g_TerrainMoveProfileOffsetsMinus1;
extern CLASH95_INTERNAL const unsigned char g_UnitTypeWorldMoveCosts[35][9];
extern __int16 g_WorldMapTopMenuHitBottom0[1];
extern __int16 g_WorldMapTopMenuHitLeft0[1];
extern void *g_WorldMapTopMenuHitMenuPtr0;
extern __int16 g_WorldMapTopMenuHitRight0[1];
extern unsigned char g_WorldMapTopMenuHitTargetA;
extern unsigned char g_WorldMapTopMenuHitTargetB;
extern __int16 g_WorldMapTopMenuHitTop0[1];
extern _UNKNOWN g_YesNoDialogButtonWidgetsTemplate;

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_STATE_LOCAL_H */
