/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'core' (9); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_CORE_SHARED_STATE_H
#define CLASH95_CORE_SHARED_STATE_H

#include "../recovered_types.h"

extern char a1[3];
extern char a2[3];
extern int g_CompatStringHolder_Vtable;
extern RenderPrimarySurfaceStorage g_MainRenderDevice;
extern int g_PathEntryArray_Vtable[2];
extern int g_PathEntry_Vtable;
extern _DWORD g_RenderState[286];
extern int g_WorldMapBackgroundSpriteSet;
extern int gameData;

#endif /* CLASH95_CORE_SHARED_STATE_H */
