/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Public surface of 'core': functions defined here and referenced from another subsystem (6). */
#ifndef CLASH95_CORE_API_H
#define CLASH95_CORE_API_H

#include "../recovered_types.h"

int App_Shutdown(void);
int  PathEntryArray_Destruct(_DWORD *array, char dtorFlags);
_DWORD * PathEntryArray_DestructElements(_DWORD *result);
int  PathEntryArray_GrowByDelta(int *array, int delta);
_DWORD * PathEntryArray_RemoveAt(_DWORD *result, int index, int destroyElement);
int  PathEntry_Destruct(int entry, char dtorFlags);

#endif /* CLASH95_CORE_API_H */
