/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/clips/0048773C_0048A4A0_clips_005.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0048773C_0048A4A0_CLIPS_005_LOCAL_H
#define CLASH95_TU_0048773C_0048A4A0_CLIPS_005_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE DWORD Compat_FileTimeToUnixSeconds (DWORD low_part, DWORD high_part) CLASH95_LOCAL_SYMBOL(Compat_FileTimeToUnixSeconds);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0048773C_0048A4A0_CLIPS_005_LOCAL_H */
