/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/clips/004CCEC0_004CEAC0_clips_004.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_004CCEC0_004CEAC0_CLIPS_004_LOCAL_H
#define CLASH95_TU_004CCEC0_004CEAC0_CLIPS_004_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE int Runtime_ExprDescriptorNoop (int value) CLASH95_LOCAL_SYMBOL(Runtime_ExprDescriptorNoop);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_004CCEC0_004CEAC0_CLIPS_004_LOCAL_H */
