/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'clips' (124); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_CLIPS_SHARED_STATE_H
#define CLASH95_CLIPS_SHARED_STATE_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern char IsTable[256];
extern char a1[3];
extern char a2[3];
extern char aActivations[12];
extern char aArgacces[9];
extern char aClass[6];
extern char aCompilations[13];
extern char aExpectedAtLeas[20];
extern char aFacts_0[6];
extern char aFunction[10];
extern char aFunctionParser[60];
extern char aInitSlots[11];
extern DWORD dwTlsIndex;
extern int g_BinaryItemListHead;
extern int g_CLIPS_CurrentRuleSalience;
extern int g_CLIPS_DefclassModuleItemIndex;
extern int g_CLIPS_IntegerZeroValueNode;
extern int g_CRT_EnvVarPointerArray;
extern int (__thiscall *g_CRT_FileHandleLockAcquireHook)(_DWORD);
extern int (__fastcall *g_CRT_FileHandleLockReleaseHook)(_DWORD, _DWORD);
extern int g_CRT_MaxFileDescriptor;
extern int g_CRT_MbcsCodePageActive;
extern int g_CRT_OsHandleTable;
extern _UNKNOWN g_CRT_StdoutStream;
extern int g_CRT_ThreadDataBlockSize;
extern int g_Class_InstanceAddress;
extern int g_Class_InstanceName;
extern int g_ClipsBloadBitmapPointerTable;
extern int g_ClipsBloadSymbolPointerArray;
extern int g_ClipsCodeHeaderFile;
extern int g_ClipsCodeMaxIndicesPerArray;
extern int g_ClipsCommandEvalInProgress;
extern int g_ClipsConstructCompilerData;
extern int g_ClipsCurrentEvaluationDepth;
extern int g_ClipsCurrentExpression;
extern int g_ClipsDefclassConstructType;
extern __int16 g_ClipsDefclassIdCount;
extern int g_ClipsDefclassIdTable;
extern int g_ClipsDeleteMessageSymbol;
extern int g_ClipsEphemeralItemBytes;
extern int g_ClipsEphemeralItemCount;
extern int g_ClipsEvaluationError;
extern int g_ClipsExpressionNodeIndex;
extern int g_ClipsFalseSymbol;
extern int g_ClipsHaltExecution;
extern __int64 g_ClipsHaltExecutionFlag;
extern int g_ClipsMemFreeListTemp;
extern int g_ClipsMemPoolReturnBucketIndex;
extern int g_ClipsMemoryTable;
extern int g_ClipsNotSymbol;
extern int g_ClipsObjectReteCurrentInstance;
extern int g_ClipsPackedExpressionArray;
extern int g_ClipsParseContextSaveStack;
extern int g_ClipsParseReturnContext;
extern int g_ClipsParsedFormAst;
extern int g_ClipsParserTokenValue;
extern int g_ClipsPositiveInfinitySymbol;
extern int g_ClipsPrimitiveTypeClassMap[1];
extern int g_ClipsScanTokenPrintForm;
extern int g_ClipsSymbolEq;
extern int g_ClipsSymbolNeq;
extern int g_ClipsSymbolOr;
extern int g_ClipsTrueSymbol;
extern int g_Clips_CurrentPartialMatch;
extern char g_Clips_DbcsLeadByteTable[255];
extern int g_Clips_DefinstancesModuleItemIndex;
extern int g_Clips_InstanceListHead;
extern int g_Clips_NameSymbol;
extern int g_Clips_NegativeInfinitySymbol;
extern int g_ConstraintHashTable;
extern int g_ConstructsToCImageId;
extern __int64 (__fastcall *g_CrtThreadDataAccessor)(_DWORD, _DWORD);
extern _DWORD g_CrtThreadDataMgmtDisabledFlag;
extern int g_CurrentPatternEntityPtr;
extern int g_DefclassHashTable;
extern int g_Defclass_SlotNameHashTablePtr;
extern int g_DefruleConstructClass;
extern char *g_IO_LogicalNameTable_WDialog[3];
extern char *g_IO_LogicalNameTable_WError[5];
extern char *g_IO_LogicalNameTable_WTrace[4];
extern char *g_IO_LogicalNameTable_WWarning[6];
extern char *g_IO_LogicalName_WDisplay;
extern int g_Instance_DeletedListHead;
extern int g_Instance_PurgeInProgress;
extern int g_InternedSym_Qds;
extern char *g_MessageHandlerTypeNames[4];
extern int g_MessageHandler_SelfSymbol;
extern int g_Module_ChangeGeneration;
extern int g_Module_MainRedefinable;
extern int g_ObjectPatternActiveClassNode;
extern int g_ObjectPatternMarkerListHead;
extern int g_ObjectPatternMatchFieldCount;
extern int g_ParserBreakContextFlag;
extern int g_ParserCurrentTokenType;
extern int g_PatternParserListHead;
extern int g_Print_AddressesToStringsFlag;
extern int g_Print_InstanceAddressesToNamesFlag;
extern int g_Print_PreserveEscapedCharactersFlag;
extern int g_Rules_ActiveInstanceCount;
extern void *g_Rules_BloadFileHeaderID;
extern int g_Rules_BloadFunctionPtrTable;
extern char *g_Rules_BsaveVersionID;
extern int g_Rules_ClearInProgressFlag;
extern int g_Rules_CurrentLogicalJoin;
extern int g_Rules_CurrentlyExecutingRule;
extern int g_Rules_DeclaredAutoFocusFlag;
extern void *g_Rules_DummyFactPtr;
extern int g_Rules_EntityTimeTagCounter;
extern _DWORD g_Rules_FactPatternEntityRecord[15];
extern int g_Rules_GlobalRHSBinds;
extern int g_Rules_InitialObjectSymbol;
extern int g_Rules_JoinOperationInProgress;
extern _DWORD g_Rules_ObjectPatternVTable[15];
extern int g_Rules_ResetInProgressFlag;
extern int g_Rules_WatchActivationsFlag;
extern int g_Rules_WatchFactsFlag;
extern int g_Symbol_IsA;
extern int g_WindowsVersionDword;

/* Deliberate unprototyped residue: recovered call sites depend on K&R semantics
 * (varying arity) or the slot type is unrecovered; kept verbatim as provenance. */
#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
#endif
extern _DWORD (*g_CRT_StaticLock1AcquireHook)();
extern _DWORD (*g_CRT_StaticLock1ReleaseHook)();
extern _DWORD (*g_CRT_StaticLock2AcquireHook)();
extern _DWORD (*g_CRT_StaticLock2ReleaseHook)();
extern _DWORD (*g_CRT_ThreadStartupHook)();
extern _DWORD (*g_CRT_TlsIndexDestroyHook)();
#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))
#pragma GCC diagnostic pop
#endif

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_CLIPS_SHARED_STATE_H */
