#!/usr/bin/env python3
"""Generate the per-subsystem interface headers (P3.3).

Consumes data/recovered_decls.json (verbatim declaration text, P3.2) +
data/recovered_sources.json (function -> subsystem/source) + a usage scan of
the 138 recovered TUs (comment/string-stripped identifier tokenization), and
emits the narrowed header set that replaces the recovered_internal.h umbrella:

  src/<S>/<S>_api.h        functions DEFINED in S referenced from another
                           subsystem (the measured public surface)
  src/<S>/<S>_internal.h   functions defined in S referenced only inside S;
                           includes <S>_api.h
  src/<S>/<S>_state.h      state-owned globals whose only consuming subsystem
                           is S
  src/state/state_shared.h globals consumed by 2+ subsystems
  src/state/state_local.h  globals referenced only by the state group itself
                           (also carries the state group's own consumer slice)
  src/recovered_legacy_imports.h   legacy import decls (no manifest definition)
  src/recovered_test_seams.h       CLASH95_TEST_VISIBLE prototypes, guarded by
                                   #ifdef CLASH95_TESTING
  src/recovered_all.h      aggregate of everything above; for tests/unit ONLY
  data/subsystem_api.json  machine-readable measured surface (feeds the
                           header-surface ratchet)

Determinism: functions are emitted in manifest (original address) order;
globals alphabetically. Declaration text is copied VERBATIM from the decl DB.
Because every recovered TU still compiles against the full umbrella until its
include block is flipped (P3.4), these headers are additive and cannot change
codegen; obj_diff_gate.sh is the oracle at every step.

Support files (platform/compatibility/instrumentation/bootstrap) are excluded
from the usage scan: their hand-maintained access pattern is out of scope.

Usage:
  python3 tools/gen_subsystem_headers.py --write            # regenerate all
  python3 tools/gen_subsystem_headers.py --check            # freshness (CI)
  python3 tools/gen_subsystem_headers.py --write-tu-includes S   # flip one
        subsystem's TU include blocks (P3.4 migration stepper)
  python3 tools/gen_subsystem_headers.py --report FILE      # usage report
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DECLS = REPO / "data" / "recovered_decls.json"
MANIFEST = REPO / "data" / "recovered_sources.json"
SURFACE_OUT = REPO / "data" / "subsystem_api.json"

SUBSYSTEMS = ("core", "render", "world", "units", "buildings", "battle",
              "persistence", "strategic", "clips", "media", "runtime", "state")

BANNER = "/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */"
MARK_BEGIN = "/* CLASH95_GENERATED_INCLUDES_BEGIN -- tools/gen_subsystem_headers.py; do not edit */"
MARK_END = "/* CLASH95_GENERATED_INCLUDES_END */"

IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def strip_code(text: str) -> str:
    """Remove block/line comments and string/char literals."""
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", " ", text)
    text = re.sub(r'"(?:[^"\\\n]|\\.)*"', '""', text)
    text = re.sub(r"'(?:[^'\\\n]|\\.)*'", "''", text)
    return text


def load():
    decls = json.loads(DECLS.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    return decls, manifest


def tu_subsystem(source: str) -> str:
    return source.split("/")[1]


def scan_usage(manifest):
    """PREPROCESSED token set per TU: name -> set of identifiers.

    Raw-text scanning misses macro indirection: accessor macros in
    recovered_types.h expand to globals (e.g. g_UnitTypeMaxRange ->
    g_UnitTypeRuntimeCoreMetadata), so a TU that only names the macro still
    depends on the global. Each TU body (its include lines stripped) is
    preprocessed together with recovered_types.h; identifiers are collected
    only AFTER a scan marker so types.h's own content does not pollute the
    set. Declaration headers are never included, so the only identifiers seen
    are the TU's own references, macro-expanded.

    A function's own defining TU does not count as a user; any other TU does
    (including other TUs of the home subsystem, which distinguishes 'internal
    with cross-TU use' from 'defined-before-use only')."""
    import subprocess
    import tempfile

    marker = "CLASH95_SCAN_MARKER_31415"
    sources = sorted({r["source"] for r in manifest["functions"]}
                     | {manifest["state_owner"]})
    tu_tokens: dict[str, set] = {}
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / "scan.c"
        for rel in sources:
            body = (REPO / rel).read_text(encoding="latin-1")
            body = re.sub(
                re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
                " ", body, flags=re.DOTALL)
            body = re.sub(r'^\s*#\s*include[^\n]*$', " ", body, flags=re.M)
            tmp.write_text(
                '#include "recovered_types.h"\n'
                f"int {marker};\n" + body,
                encoding="latin-1", newline="")
            proc = subprocess.run(
                ["gcc", "-std=gnu17", "-E", "-P",
                 "-I", str(REPO / "src"), "-I", str(REPO), str(tmp)],
                capture_output=True, text=True)
            if proc.returncode != 0:
                raise SystemExit(
                    f"scan preprocess failed for {rel}:\n{proc.stderr[:500]}")
            out = proc.stdout.split(marker, 1)
            payload = out[1] if len(out) == 2 else proc.stdout
            tu_tokens[rel] = set(IDENT.findall(payload))
    return tu_tokens


def expanded_names(fn_db, gl_db):
    """Map each DB entry to its POST-macro-expansion declared name.

    Alias macros in recovered_types.h rewrite address-suffixed declarations to
    clean names (e.g. `extern int g_UnitBattleChargeModeActive_532060;` becomes
    `extern int g_UnitBattleChargeModeActive;` once the `#define suffixed
    clean` macro is in scope — which is exactly how the umbrella worked). The
    usage scan sees post-expansion identifiers, so usage matching must happen
    in the same namespace. One preprocess pass over all decl texts yields
    db_key -> expanded_name."""
    import subprocess
    import tempfile

    marker = "CLASH95_DECL_MARKER_27182"
    keys = [("fn", k) for k in fn_db] + [("gl", k) for k in gl_db]
    parts = ['#include "recovered_types.h"', f"int {marker};"]
    for kind, k in keys:
        decl = (fn_db if kind == "fn" else gl_db)[k]["decl"]
        parts.append(f"/*{marker}*/")
        parts.append(decl)
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / "decls.c"
        tmp.write_text("\n".join(parts), encoding="latin-1", newline="")
        proc = subprocess.run(
            ["gcc", "-std=gnu17", "-E", "-C",
             "-I", str(REPO / "src"), "-I", str(REPO), str(tmp)],
            capture_output=True, text=True)
        if proc.returncode != 0:
            raise SystemExit(f"decl preprocess failed:\n{proc.stderr[:500]}")
    chunks = proc.stdout.split(f"/*{marker}*/")[1:]
    if len(chunks) != len(keys):
        raise SystemExit(
            f"decl marker mismatch: {len(chunks)} chunks vs {len(keys)} keys")
    out = {}
    for (kind, k), chunk in zip(keys, chunks):
        chunk = re.sub(r"^#[^\n]*$", " ", chunk, flags=re.M)
        try:
            _, name = _classify_expanded(chunk)
        except ValueError:
            name = k  # fall back to the raw key
        out[(kind, k)] = name
    return out


def _classify_expanded(decl: str):
    """Name extraction over an expanded declaration (same shapes as the
    extractor's classifier, duplicated here to stay dependency-free)."""
    code = re.sub(r"/\*.*?\*/", " ", decl, flags=re.DOTALL)
    code = re.sub(r"__attribute__\s*\(\((?:[^()]|\([^()]*\))*\)\)", " ", code)
    if "(" in code:
        mptr = re.search(
            r"\(\s*(?:__\w+\s+)?\*\s*([A-Za-z_][A-Za-z0-9_]*)"
            r"\s*(?:\[[^\]]*\])?\s*\)", code)
        if (mptr and re.match(r"\s*extern\b", code.strip())
                and not re.search(r"\b[A-Za-z_][A-Za-z0-9_]*\s*\(",
                                  code[: mptr.start()])):
            return "global", mptr.group(1)
        mret = re.search(
            r"\(\s*(?:__\w+\s+)?\*\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(", code)
        if mret:
            return "function", mret.group(1)
        m = re.search(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(", code)
        if m:
            return "function", m.group(1)
    m = re.search(
        r"\b([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\])*\s*(?:=[^;]*)?;",
        code.strip())
    if m:
        return "global", m.group(1)
    raise ValueError("unclassifiable")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write-tu-includes", metavar="S")
    ap.add_argument("--report", type=Path)
    args = ap.parse_args()

    decls, manifest = load()
    fn_db = decls["functions"]
    gl_db = decls["globals"]
    man_fns = manifest["functions"]
    defining_tu = {r["name"]: r["source"] for r in man_fns}
    man_order = {r["name"]: i for i, r in enumerate(man_fns)}

    tu_tokens = scan_usage(manifest)
    xname = expanded_names(fn_db, gl_db)
    fn_xname = {k: xname[("fn", k)] for k in fn_db}
    gl_xname = {k: xname[("gl", k)] for k in gl_db}

    # reverse maps: expanded name -> db key (prefer identity mapping on
    # collision, i.e. the entry whose raw name IS the expanded name)
    def reverse(xmap):
        rev = {}
        for k, x in xmap.items():
            if x not in rev or k == x:
                rev[x] = k
        return rev
    rev_fn = reverse(fn_xname)
    rev_gl = reverse(gl_xname)

    # ---- classify functions ------------------------------------------------
    fn_users: dict[str, set] = {}
    for rel, toks in tu_tokens.items():
        sub = tu_subsystem(rel)
        for tok in toks:
            key = rev_fn.get(tok)
            if key is not None and defining_tu.get(key) != rel:
                fn_users.setdefault(key, set()).add(sub)

    api: dict[str, list] = {s: [] for s in SUBSYSTEMS}
    internal: dict[str, list] = {s: [] for s in SUBSYSTEMS}
    legacy, seams = [], []
    for name, rec in fn_db.items():
        if rec["class"] == "legacy-import":
            legacy.append(name)
            continue
        if rec["class"] == "test-seam":
            seams.append(name)
            continue
        home = rec["home"]
        if home not in api:      # defensive: manifest subsystem always valid
            continue
        users = fn_users.get(name, set())
        if users - {home}:
            api[home].append(name)
        else:
            internal[home].append(name)
    for s in SUBSYSTEMS:
        api[s].sort(key=lambda n: man_order.get(n, 1 << 30))
        internal[s].sort(key=lambda n: man_order.get(n, 1 << 30))
    legacy.sort()
    seams.sort(key=lambda n: man_order.get(n, 1 << 30))

    # ---- classify globals --------------------------------------------------
    gl_users: dict[str, set] = {}
    for rel, toks in tu_tokens.items():
        sub = tu_subsystem(rel)
        for tok in toks:
            key = rev_gl.get(tok)
            if key is not None:
                gl_users.setdefault(key, set()).add(sub)

    state_slice: dict[str, list] = {s: [] for s in SUBSYSTEMS if s != "state"}
    shared, local = [], []
    for name in sorted(gl_db):
        users = gl_users.get(name, set()) - {"state"}
        if not users:
            local.append(name)
        elif len(users) == 1:
            (only,) = users
            state_slice[only].append(name)
        else:
            shared.append(name)

    # ---- render headers ----------------------------------------------------
    def hdr(guard: str, includes: list[str], body_lines: list[str],
            purpose: str, ifdef_testing: bool = False) -> str:
        out = [BANNER, f"/* {purpose} */",
               f"#ifndef {guard}", f"#define {guard}", ""]
        out += [f'#include "{inc}"' for inc in includes]
        out.append("")
        if ifdef_testing:
            out.append("#ifdef CLASH95_TESTING")
        out += body_lines
        if ifdef_testing:
            out.append("#endif /* CLASH95_TESTING */")
        out += ["", f"#endif /* {guard} */", ""]
        return "\n".join(out)

    files: dict[Path, str] = {}
    for s in SUBSYSTEMS:
        rel_types = "../recovered_types.h"
        files[REPO / "src" / s / f"{s}_api.h"] = hdr(
            f"CLASH95_{s.upper()}_API_H", [rel_types],
            [fn_db[n]["decl"] for n in api[s]],
            f"Public surface of '{s}': functions defined here and referenced "
            f"from another subsystem ({len(api[s])}).")
        files[REPO / "src" / s / f"{s}_internal.h"] = hdr(
            f"CLASH95_{s.upper()}_INTERNAL_H", [f"{s}_api.h"],
            [fn_db[n]["decl"] for n in internal[s]],
            f"Home-only functions of '{s}' ({len(internal[s])}); private to "
            f"the subsystem.")
        if s != "state":
            files[REPO / "src" / s / f"{s}_state.h"] = hdr(
                f"CLASH95_{s.upper()}_STATE_H", [rel_types],
                [gl_db[n]["decl"] for n in state_slice[s]],
                f"State-TU globals whose only consuming subsystem is '{s}' "
                f"({len(state_slice[s])}).")
    files[REPO / "src" / "state" / "state_shared.h"] = hdr(
        "CLASH95_STATE_SHARED_H", ["../recovered_types.h"],
        [gl_db[n]["decl"] for n in shared],
        f"Globals consumed by two or more subsystems ({len(shared)}).")
    files[REPO / "src" / "state" / "state_local.h"] = hdr(
        "CLASH95_STATE_LOCAL_H", ["../recovered_types.h"],
        [gl_db[n]["decl"] for n in local],
        f"Globals referenced only within the state group itself ({len(local)}); "
        f"kept declared so definitions stay decl-checked.")
    files[REPO / "src" / "recovered_legacy_imports.h"] = hdr(
        "CLASH95_RECOVERED_LEGACY_IMPORTS_H", ["recovered_types.h"],
        [fn_db[n]["decl"] for n in legacy],
        f"Legacy CRT/Win32-era import declarations without manifest "
        f"definitions ({len(legacy)}); typed against "
        f"compatibility/decomp_runtime_stubs.c in a later tranche.")
    files[REPO / "src" / "recovered_test_seams.h"] = hdr(
        "CLASH95_RECOVERED_TEST_SEAMS_H", ["recovered_types.h"],
        [fn_db[n]["decl"] for n in seams],
        f"CLASH95_TEST_VISIBLE prototypes ({len(seams)}): static in "
        f"production, external under CLASH95_TESTING.", ifdef_testing=True)
    agg_incs = ["recovered_types.h", "recovered_layout.h",
                "recovered_legacy_imports.h", "recovered_test_seams.h"]
    for s in SUBSYSTEMS:
        agg_incs.append(f"{s}/{s}_api.h")
        agg_incs.append(f"{s}/{s}_internal.h")
        if s != "state":
            agg_incs.append(f"{s}/{s}_state.h")
    agg_incs += ["state/state_shared.h", "state/state_local.h"]
    files[REPO / "src" / "recovered_all.h"] = hdr(
        "CLASH95_RECOVERED_ALL_H", agg_incs, [],
        "Aggregate of the narrowed headers for tests/unit ONLY; forbidden in "
        "production src/** (audited).")

    # ---- surface artifact ---------------------------------------------------
    surface = {
        "schema_version": 1,
        "subsystems": {
            s: {
                "api_functions": api[s],
                "internal_function_count": len(internal[s]),
                "state_globals": len(state_slice.get(s, [])),
            } for s in SUBSYSTEMS
        },
        "shared_globals": shared,
        "state_local_global_count": len(local),
        "legacy_import_count": len(legacy),
        "peer_edges": {},
    }
    # peer edges: for each TU, which OTHER subsystems' api functions it uses
    edges: dict[str, set] = {}
    api_home_x = {fn_xname[n]: (s, n) for s in SUBSYSTEMS for n in api[s]}
    for rel, toks in tu_tokens.items():
        src_sub = tu_subsystem(rel)
        for tok in toks:
            hit = api_home_x.get(tok)
            if hit is None:
                continue
            tgt, key = hit
            if tgt != src_sub and defining_tu.get(key) != rel:
                edges.setdefault(f"{src_sub}->{tgt}", set()).add(key)
    surface["peer_edges"] = {k: len(v) for k, v in sorted(edges.items())}
    surface_text = json.dumps(surface, indent=1, sort_keys=True) + "\n"

    # ---- per-TU include blocks ----------------------------------------------
    def tu_block(rel: str, toks: set) -> str:
        sub = tu_subsystem(rel)
        incs = ["../recovered_layout.h", f"{sub}_internal.h"]
        if sub != "state":
            incs.append(f"{sub}_state.h")
        else:
            incs += ["state_shared.h", "state_local.h"]
            incs += [f"../{t}/{t}_state.h" for t in SUBSYSTEMS if t != "state"]
        if sub != "state" and any(gl_xname[n] in toks for n in shared):
            incs.append("../state/state_shared.h")
        for t in SUBSYSTEMS:
            if t == sub:
                continue
            if any(fn_xname[name] in toks and defining_tu.get(name) != rel
                   for name in api[t]):
                incs.append(f"../{t}/{t}_api.h")
        if any(fn_xname[n] in toks for n in legacy):
            incs.append("../recovered_legacy_imports.h")
        if any(fn_xname[n] in toks and defining_tu.get(n) == rel
               for n in seams):
            incs.append("../recovered_test_seams.h")
        lines = [MARK_BEGIN] + [f'#include "{i}"' for i in incs] + [MARK_END]
        return "\n".join(lines)

    if args.write_tu_includes:
        s = args.write_tu_includes
        if s not in SUBSYSTEMS:
            print(f"unknown subsystem {s!r}")
            return 2
        flipped = 0
        for rel in sorted(tu_tokens):
            if tu_subsystem(rel) != s:
                continue
            p = REPO / rel
            text = p.read_text(encoding="latin-1")
            block = tu_block(rel, tu_tokens[rel])
            if MARK_BEGIN in text:
                new = re.sub(
                    re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
                    block, text, count=1, flags=re.DOTALL)
            else:
                needle = '#include "../recovered_internal.h"'
                if needle not in text:
                    print(f"SKIP {rel}: no umbrella include found")
                    continue
                new = text.replace(needle, block, 1)
            p.write_text(new, encoding="latin-1", newline="")
            flipped += 1
        print(f"flipped {flipped} TUs in subsystem {s!r}")
        return 0

    if args.report:
        args.report.write_text(surface_text, encoding="utf-8")
        print(f"report -> {args.report}")

    summary = ("api: " + " ".join(f"{s}={len(api[s])}" for s in SUBSYSTEMS)
               + f" | internal total={sum(len(v) for v in internal.values())}"
               + f" | state slices total={sum(len(v) for v in state_slice.values())}"
               + f" shared={len(shared)} local={len(local)}"
               + f" | legacy={len(legacy)} seams={len(seams)}")
    print(summary)

    if args.check:
        stale = []
        for path, text in files.items():
            cur = path.read_text(encoding="latin-1") if path.exists() else None
            if cur is None or cur.replace("\r\n", "\n") != text:
                stale.append(str(path.relative_to(REPO)))
        cur_surface = (SURFACE_OUT.read_text(encoding="utf-8")
                       if SURFACE_OUT.exists() else None)
        if cur_surface != surface_text:
            stale.append(str(SURFACE_OUT.relative_to(REPO)))
        if stale:
            print("STALE:", *stale[:10])
            return 1
        print("subsystem headers up to date")
        return 0

    if args.write:
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="latin-1", newline="")
        SURFACE_OUT.write_text(surface_text, encoding="utf-8")
        print(f"wrote {len(files)} headers + {SURFACE_OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
