#!/usr/bin/env python3
"""Generate the private C17 layout guard from recovered foundation constants.

Emits one C17 ``_Static_assert`` per numeric object-like ``#define`` and enum
member in ``recovered_types.h``. The committed header is a compile-time
tripwire for recovered memory-map constants.

Usage:
  python3 tools/gen_constant_guard.py          # rewrite canonical header
  python3 tools/gen_constant_guard.py --check  # verify without writing
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import literal_common as lc

OUT_REL = "src/recovered_layout.h"

HEADER = """\
/* GENERATED by tools/gen_constant_guard.py -- do not edit by hand.
 *
 * Compile-time pins for every numeric object-like #define in
 * recovered_types.h. A mismatch fails the build, so an accidental edit
 * to a recovered memory-map constant cannot slip through compile+link.
 * Regenerate deliberately after intentional constant changes.
 */

#ifndef CLASH95_RECOVERED_LAYOUT_H
#define CLASH95_RECOVERED_LAYOUT_H

#include "recovered_types.h"
#include "recovered_structs.h"
"""

FOOTER = """

#endif
"""


def generated_text():
    macros = lc.parse_prelude_macros()
    lines = [HEADER.rstrip()]
    for name in sorted(macros):
        macro = macros[name]
        value = lc.numeric_macro_value(macro)
        if value is None:
            continue
        spelled = macro["body"].strip()
        lines.append(
            '_Static_assert((%s) == (%s), "%s changed");'
            % (name, spelled, name)
        )
    for name, value in sorted(lc.parse_prelude_enums().items()):
        lines.append(
            '_Static_assert((%s) == (%d), "%s changed");'
            % (name, value, name)
        )
    return "\n".join(lines) + FOOTER


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated_text()
    out = os.path.join(lc.REPO, OUT_REL)
    if args.check:
        try:
            current = open(out, encoding="utf-8").read()
        except OSError as error:
            print("constant guard check failed: %s" % error, file=sys.stderr)
            return 1
        if current != content:
            print("constant guard is stale: %s" % OUT_REL, file=sys.stderr)
            return 1
        print("constant guard check: PASS (%s)" % OUT_REL)
        return 0
    with open(out, "w", newline="\n") as f:
        f.write(content)
    guard_count = content.count("_Static_assert")
    print("wrote %s (%d guards)" % (OUT_REL, guard_count))
    return 0


if __name__ == "__main__":
    sys.exit(main())
