#!/usr/bin/env python3
"""Generate the unit-test declaration wrapper for split recovered objects.

Function identities are validated through ``data/recovered_sources.json``.
The split internal header owns the assembly/call-site-backed declarations; the
unit wrapper no longer scrapes signatures from the unified ``clash95.c`` text.
"""

from __future__ import annotations

import sys
from pathlib import Path

from coverage_source_manifest import (
    CoverageMetadataError,
    PURE_SET,
    load_pure_set,
    split_ranges,
)


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "tests" / "unit" / "clash95_pure_decls.h"


def main() -> int:
    pure_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else PURE_SET
    _, functions = load_pure_set(pure_path, require_manifest=True)
    ranges = split_ranges(functions)
    if len(ranges) != len(functions):
        raise CoverageMetadataError(
            f"resolved {len(ranges)} source identities for {len(functions)} functions"
        )
    output = """/* GENERATED by tools/gen_pure_decls.py. */
#ifndef CLASH95_PURE_DECLS_H
#define CLASH95_PURE_DECLS_H

/* CLASH95_TESTING must be defined by the coverage object-library target so
 * only explicitly frozen helpers marked CLASH95_TEST_VISIBLE lose static
 * linkage in test builds. */
#include "../../src/recovered_internal.h"

#endif
"""
    OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"validated {len(functions)} identities and wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except CoverageMetadataError as error:
        raise SystemExit(str(error)) from error
