#!/usr/bin/env python3
"""Generate the per-subsystem interface headers (P3.3).

Consumes data/recovered_decls.json (verbatim declaration text, P3.2) +
data/recovered_sources.json (function -> subsystem/source) + a usage scan of
the manifest-backed recovered TUs (preprocessed identifier tokenization), and
emits the narrowed header set that replaces the recovered_internal.h umbrella:

  src/<S>/<S>_api.h        functions DEFINED in S referenced from another
                           subsystem (the measured public surface)
  src/<S>/<S>_internal.h   functions defined in S referenced only inside S;
                           includes <S>_api.h
  src/<S>/<S>_state.h      state-owned globals whose only consuming subsystem
                           is S
  src/<S>/<S>_shared_state.h  shared globals actually consumed by S
  src/state/state_shared.h globals consumed by 2+ subsystems; aggregate for
                            the state definition group and tests only
  src/state/state_local.h  globals referenced only by the state group itself
                           (also carries the state group's own consumer slice)
  src/recovered_legacy_imports.h   legacy import decls (no manifest definition)
  src/recovered_test_seams.h       CLASH95_TEST_VISIBLE prototypes, guarded by
                                   #ifdef CLASH95_TESTING
  src/<S>/<TU-stem>_local.h  own-TU static and test-visible declarations only;
                            preserves C linkage for top-level C++ definitions
  src/recovered_all.h      aggregate of everything above; for tests/unit ONLY
  data/subsystem_api.json  measured surface, shared-state consumer identities,
                            and per-TU referenced/visible shared declarations

The declaration DB's optional shared_state_layout setting selects 'aggregate'
(the existing layout, also the default) or 'consumer' (the narrowed slices and
visibility metrics). Set 'consumer' only as part of the Linux regeneration and
validation batch; this keeps the active generated tree consistent until then.

Determinism: functions are emitted in manifest (original address) order;
globals alphabetically. Reconstruction helpers without original addresses use
class 'helper', with an explicit home and an existing manifest-backed source;
they follow manifest functions in name order. Declaration text is copied
verbatim from the decl DB; own-TU headers append the original symbol's
CLASH95_LOCAL_SYMBOL pin without changing its signature or storage class.
Storage remains in the state translation unit. Declaration narrowing does not
move or resize globals; token/object comparisons and builds validate each
rollout. The aggregate remains available for definition checks and unit tests.

Support files (platform/compatibility/instrumentation/bootstrap) are excluded
from the usage scan: their hand-maintained access pattern is out of scope.

Usage:
  python3 tools/gen_subsystem_headers.py --write            # regenerate all
  python3 tools/gen_subsystem_headers.py --check            # freshness (CI)
  python3 tools/gen_subsystem_headers.py --write-tu-includes S   # flip one
        subsystem's TU include blocks, or use 'all' for the whole tree
  python3 tools/gen_subsystem_headers.py --write --write-tu-includes all
        # regenerate headers, surface, and includes from the same usage scan
  python3 tools/gen_subsystem_headers.py --report FILE      # usage report
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DECLS = REPO / "data" / "recovered_decls.json"
MANIFEST = REPO / "data" / "recovered_sources.json"
SURFACE_OUT = REPO / "data" / "subsystem_api.json"

SUBSYSTEMS = ("core", "render", "world", "units", "buildings", "battle",
              "persistence", "strategic", "clips", "media", "runtime", "state")

BANNER = "/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */"
MARK_BEGIN = "/* CLASH95_GENERATED_INCLUDES_BEGIN -- tools/gen_subsystem_headers.py; do not edit */"
MARK_END = "/* CLASH95_GENERATED_INCLUDES_END */"
TENTATIVE_BEGIN = "/* CLASH95_GENERATED_TENTATIVES_BEGIN -- tools/gen_subsystem_headers.py; do not edit */"
TENTATIVE_END = "/* CLASH95_GENERATED_TENTATIVES_END */"

IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def refresh_tentative_state(text: str) -> str:
    """Retain Clang C's late-definition order when the state owner uses C++."""
    declarations = re.findall(r"^CLASH95_TENTATIVE ([^\n]+;)\s*$", text, re.M)
    if not declarations and TENTATIVE_BEGIN not in text:
        return text
    if text.count(TENTATIVE_BEGIN) != 1 or text.count(TENTATIVE_END) != 1:
        raise ValueError("state owner needs exactly one generated tentative block")
    if len(declarations) != len(set(declarations)):
        raise ValueError("duplicate tentative state declaration")
    if any("=" in declaration for declaration in declarations):
        raise ValueError("initialized state must keep its original placement")
    block = "\n".join([TENTATIVE_BEGIN,
                        "#if defined(__cplusplus) && defined(__clang__)",
                        *declarations, "#endif", TENTATIVE_END])
    pattern = re.escape(TENTATIVE_BEGIN) + r".*?" + re.escape(TENTATIVE_END)
    return re.sub(pattern, lambda _: block, text, flags=re.S)


def strip_code(text: str) -> str:
    """Remove block/line comments and string/char literals."""
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", " ", text)
    text = re.sub(r'"(?:[^"\\\n]|\\.)*"', '""', text)
    text = re.sub(r"'(?:[^'\\\n]|\\.)*'", "''", text)
    return text


def load():
    """Load + validate the decl DB against the manifest. The DB is the
    hand-editable canonical declaration home; nothing else checks its derived
    invariants, so a bad edit must fail HERE (this runs in CI via
    audit_header_surface) rather than silently dropping declarations."""
    decls = json.loads(DECLS.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    subsystem_of = {r["name"]: r["subsystem"] for r in manifest["functions"]}
    manifest_by_name = {r["name"]: r for r in manifest["functions"]}
    sources = {r["source"] for r in manifest["functions"]}
    sources.add(manifest["state_owner"])
    problems = []
    layout = decls.get("shared_state_layout", "aggregate")
    if layout not in ("aggregate", "consumer"):
        problems.append(f"unknown shared_state_layout {layout!r}")
    for name, rec in decls["functions"].items():
        cls = rec.get("class")
        if cls not in ("manifest", "test-seam", "legacy-import", "helper", "tu-local"):
            problems.append(f"{name}: unknown declaration class {cls!r}")
        elif cls in ("manifest", "test-seam", "tu-local"):
            want = subsystem_of.get(name)
            if want is None:
                problems.append(f"{name}: class {rec['class']} but not in manifest")
            elif rec["home"] != want:
                problems.append(
                    f"{name}: home {rec['home']!r} != manifest subsystem {want!r}")
            elif want not in SUBSYSTEMS:
                problems.append(f"{name}: unknown subsystem {want!r}")
            if cls == "tu-local":
                original = manifest_by_name.get(name, {})
                if original.get("linkage") != "static":
                    problems.append(f"{name}: tu-local requires manifest static linkage")
                if rec.get("source") != original.get("source"):
                    problems.append(f"{name}: tu-local source differs from manifest")
                if not rec["decl"].lstrip().startswith(("CLASH95_LOCAL ", "static ")):
                    problems.append(f"{name}: tu-local declaration must retain static storage")
        elif cls == "helper":
            # These are existing reconstruction functions, not invented
            # original-address entries or legacy imports. Keep their source
            # inside the same closed TU set that scan_usage preprocesses.
            home, source = rec.get("home"), rec.get("source")
            if name in subsystem_of:
                problems.append(f"{name}: helper is already in manifest")
            if home not in SUBSYSTEMS:
                problems.append(f"{name}: unknown helper subsystem {home!r}")
            if source not in sources:
                problems.append(f"{name}: helper source {source!r} is not a recovered TU")
            elif tu_subsystem(source) != home:
                problems.append(f"{name}: helper source {source!r} does not belong to {home!r}")
            elif not (REPO / source).is_file():
                problems.append(f"{name}: helper source {source!r} is missing")
        if name not in rec["decl"]:
            problems.append(f"{name}: key does not appear in its decl text")
    for name, original in manifest_by_name.items():
        if (original.get("linkage") == "static"
                and decls["functions"].get(name, {}).get("class") != "tu-local"):
            problems.append(f"{name}: static definition needs its TU-local declaration")
    if problems:
        for p in problems[:10]:
            print("DECL-DB INVALID:", p)
        raise SystemExit(f"decl DB failed validation ({len(problems)} problems)")
    return decls, manifest


def tu_subsystem(source: str) -> str:
    return source.split("/")[1]


def is_cpp_source(source: str) -> bool:
    return Path(source).suffix in (".cpp", ".cc", ".cxx")


def replace_tu_include_block(text: str, block: str) -> str:
    """Replace only the generated block, preserving surrounding source bytes.

    Callers decode/encode latin-1 without universal-newline conversion. This
    keeps a header-only rollout separate from line-ending or source edits.
    """
    if text.count(MARK_BEGIN) != 1 or text.count(MARK_END) != 1:
        raise ValueError("expected exactly one begin marker and one end marker")
    pattern = re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END)
    matches = list(re.finditer(pattern, text, flags=re.DOTALL))
    if len(matches) != 1:
        raise ValueError(f"expected one generated include block, found {len(matches)}")
    match = matches[0]
    newline = "\r\n" if "\r\n" in match.group(0) else "\n"
    replacement = block.replace("\r\n", "\n").replace("\n", newline)
    return text[:match.start()] + replacement + text[match.end():]


def scan_usage(manifest):
    """PREPROCESSED token set per TU: name -> set of identifiers.

    Raw-text scanning misses macro indirection: accessor macros in
    recovered_types.h expand to globals (e.g. g_UnitTypeMaxRange ->
    g_UnitTypeRuntimeCoreMetadata), so a TU that only names the macro still
    depends on the global. Each TU body (its include lines stripped) is
    preprocessed together with recovered_types.h; identifiers are collected
    only AFTER a scan marker so types.h's own content does not pollute the
    set. Declaration headers are never included, so the only identifiers seen
    are the TU's own references, macro-expanded.

    A function's own defining TU does not count as a user; any other TU does
    (including other TUs of the home subsystem, which distinguishes 'internal
    with cross-TU use' from 'defined-before-use only')."""
    import subprocess
    import tempfile

    marker = "CLASH95_SCAN_MARKER_31415"
    sources = sorted({r["source"] for r in manifest["functions"]}
                     | {manifest["state_owner"]})
    tu_tokens: dict[str, set] = {}
    with tempfile.TemporaryDirectory() as td:
        for rel in sources:
            cpp = is_cpp_source(rel)
            tmp = Path(td) / ("scan.cpp" if cpp else "scan.c")
            body = (REPO / rel).read_text(encoding="latin-1")
            body = re.sub(
                re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
                " ", body, flags=re.DOTALL)
            body = re.sub(r'^\s*#\s*include[^\n]*$', " ", body, flags=re.M)
            tmp.write_text(
                '#include "recovered_types.h"\n'
                f"int {marker};\n" + body,
                encoding="latin-1", newline="")
            proc = subprocess.run(
                ["g++" if cpp else "gcc",
                 "-std=gnu++20" if cpp else "-std=gnu17"]
                + (["-U_GNU_SOURCE"] if cpp else [])
                + ["-E", "-P",
                 "-I", str(REPO / "src"), "-I", str(REPO), str(tmp)],
                capture_output=True, text=True, encoding="latin-1")
            if proc.returncode != 0:
                raise SystemExit(
                    f"scan preprocess failed for {rel}:\n{proc.stderr[:500]}")
            out = proc.stdout.split(marker, 1)
            payload = out[1] if len(out) == 2 else proc.stdout
            # gcc -E strips comments but NOT string/char literals: a symbol
            # named inside a diagnostic string must not count as usage (it
            # would fabricate coupling edges and trip the surface ratchet on
            # innocent logging changes).
            tu_tokens[rel] = set(IDENT.findall(strip_code(payload)))
    return tu_tokens


def expanded_names(fn_db, gl_db, *, cpp=False):
    """Map each DB entry to its POST-macro-expansion declared name.

    Alias macros in recovered_types.h rewrite address-suffixed declarations to
    clean names (e.g. `extern int g_UnitBattleChargeModeActive_532060;` becomes
    `extern int g_UnitBattleChargeModeActive;` once the `#define suffixed
    clean` macro is in scope — which is exactly how the umbrella worked). The
    usage scan sees post-expansion identifiers, so usage matching must happen
    in the same namespace. One preprocess pass over all decl texts yields
    db_key -> expanded_name."""
    import subprocess
    import tempfile

    marker = "CLASH95_DECL_MARKER_27182"
    keys = [("fn", k) for k in fn_db] + [("gl", k) for k in gl_db]
    parts = ['#include "recovered_types.h"', f"int {marker};"]
    for kind, k in keys:
        decl = (fn_db if kind == "fn" else gl_db)[k]["decl"]
        parts.append(f"/*{marker}*/")
        parts.append(decl)
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / ("decls.cpp" if cpp else "decls.c")
        tmp.write_text("\n".join(parts), encoding="latin-1", newline="")
        proc = subprocess.run(
            ["g++" if cpp else "gcc",
             "-std=gnu++20" if cpp else "-std=gnu17"]
            + (["-U_GNU_SOURCE"] if cpp else [])
            + ["-E", "-C",
             "-I", str(REPO / "src"), "-I", str(REPO), str(tmp)],
            capture_output=True, text=True, encoding="latin-1")
        if proc.returncode != 0:
            raise SystemExit(f"decl preprocess failed:\n{proc.stderr[:500]}")
    chunks = proc.stdout.split(f"/*{marker}*/")[1:]
    if len(chunks) != len(keys):
        raise SystemExit(
            f"decl marker mismatch: {len(chunks)} chunks vs {len(keys)} keys")
    out = {}
    for (kind, k), chunk in zip(keys, chunks):
        chunk = re.sub(r"^#[^\n]*$", " ", chunk, flags=re.M)
        try:
            _, name = _classify_expanded(chunk)
        except ValueError:
            name = k  # fall back to the raw key
        out[(kind, k)] = name
    return out


def _classify_expanded(decl: str):
    """Name extraction over an expanded declaration (same shapes as the
    extractor's classifier, duplicated here to stay dependency-free)."""
    code = re.sub(r"/\*.*?\*/", " ", decl, flags=re.DOTALL)
    code = re.sub(r"__attribute__\s*\(\((?:[^()]|\([^()]*\))*\)\)", " ", code)
    if "(" in code:
        mptr = re.search(
            r"\(\s*(?:__\w+\s+)?\*\s*([A-Za-z_][A-Za-z0-9_]*)"
            r"\s*(?:\[[^\]]*\])?\s*\)", code)
        if (mptr and re.match(r"\s*extern\b", code.strip())
                and not re.search(r"\b[A-Za-z_][A-Za-z0-9_]*\s*\(",
                                  code[: mptr.start()])):
            return "global", mptr.group(1)
        mret = re.search(
            r"\(\s*(?:__\w+\s+)?\*\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(", code)
        if mret:
            return "function", mret.group(1)
        m = re.search(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(", code)
        if m:
            return "function", m.group(1)
    m = re.search(
        r"\b([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\])*\s*(?:=[^;]*)?;",
        code.strip())
    if m:
        return "global", m.group(1)
    raise ValueError("unclassifiable")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write-tu-includes", metavar="S")
    ap.add_argument("--check-tu-includes", action="store_true",
                    help="verify every TU's generated include block matches "
                         "a fresh regeneration (no staleness, no hand edits)")
    ap.add_argument("--report", type=Path)
    args = ap.parse_args()

    decls, manifest = load()
    consumer_layout = decls.get("shared_state_layout", "aggregate") == "consumer"
    fn_db = decls["functions"]
    gl_db = decls["globals"]
    man_fns = manifest["functions"]
    defining_tu = {r["name"]: r["source"] for r in man_fns}
    defining_tu.update({name: rec["source"] for name, rec in fn_db.items()
                        if rec["class"] == "helper"})
    man_order = {r["name"]: i for i, r in enumerate(man_fns)}

    tu_tokens = scan_usage(manifest)
    xname = expanded_names(fn_db, gl_db, cpp=any(
        is_cpp_source(source) for source in tu_tokens))
    fn_xname = {k: xname[("fn", k)] for k in fn_db}
    gl_xname = {k: xname[("gl", k)] for k in gl_db}

    # reverse maps: expanded name -> db key (prefer identity mapping on
    # collision, i.e. the entry whose raw name IS the expanded name)
    def reverse(xmap):
        rev = {}
        for k, x in xmap.items():
            if x not in rev or k == x:
                rev[x] = k
        return rev
    rev_fn = reverse(fn_xname)
    rev_gl = reverse(gl_xname)

    # ---- classify functions ------------------------------------------------
    fn_users: dict[str, set] = {}
    for rel, toks in tu_tokens.items():
        sub = tu_subsystem(rel)
        for tok in toks:
            key = rev_fn.get(tok)
            if key is not None and defining_tu.get(key) != rel:
                fn_users.setdefault(key, set()).add(sub)

    api: dict[str, list] = {s: [] for s in SUBSYSTEMS}
    internal: dict[str, list] = {s: [] for s in SUBSYSTEMS}
    legacy, seams = [], []
    tu_locals: dict[str, list] = {}
    for name, rec in fn_db.items():
        if rec["class"] == "legacy-import":
            legacy.append(name)
            continue
        if rec["class"] == "test-seam":
            seams.append(name)
            tu_locals.setdefault(defining_tu[name], []).append(name)
            continue
        if rec["class"] == "tu-local":
            tu_locals.setdefault(defining_tu[name], []).append(name)
            continue
        home = rec["home"]
        if home not in api:      # defensive: manifest subsystem always valid
            continue
        users = fn_users.get(name, set())
        if users - {home}:
            api[home].append(name)
        else:
            internal[home].append(name)
    for s in SUBSYSTEMS:
        api[s].sort(key=lambda n: (man_order.get(n, 1 << 30), n))
        internal[s].sort(key=lambda n: (man_order.get(n, 1 << 30), n))
    legacy.sort()
    seams.sort(key=lambda n: man_order.get(n, 1 << 30))

    # ---- classify globals --------------------------------------------------
    gl_users: dict[str, set] = {}
    for rel, toks in tu_tokens.items():
        sub = tu_subsystem(rel)
        for tok in toks:
            key = rev_gl.get(tok)
            if key is not None:
                gl_users.setdefault(key, set()).add(sub)

    state_slice: dict[str, list] = {s: [] for s in SUBSYSTEMS if s != "state"}
    shared, local = [], []
    for name in sorted(gl_db):
        users = gl_users.get(name, set()) - {"state"}
        if not users:
            local.append(name)
        elif len(users) == 1:
            (only,) = users
            state_slice[only].append(name)
        else:
            shared.append(name)

    # Consumer slices change declaration visibility, not storage ownership or
    # measured coupling. Keep DB keys and verbatim declarations here: matching
    # is against the same macro-expanded names used by the existing scan.
    shared_consumers = {
        s: [name for name in shared if s in gl_users.get(name, set())]
        for s in SUBSYSTEMS if s != "state"
    }
    shared_visibility = {}
    for rel, toks in sorted(tu_tokens.items()):
        sub = tu_subsystem(rel)
        if sub == "state":
            continue
        referenced = [name for name in shared if gl_xname[name] in toks]
        shared_visibility[rel] = {
            "referenced": referenced,
            "visible": shared_consumers[sub] if referenced else [],
        }

    # ---- render headers ----------------------------------------------------
    knr_re = re.compile(r"\(\s*\)")

    def hdr(guard: str, includes: list[str], body_lines: list[str],
            purpose: str, ifdef_testing: bool = False) -> str:
        out = [BANNER, f"/* {purpose} */",
               f"#ifndef {guard}", f"#define {guard}", ""]
        out += [f'#include "{inc}"' for inc in includes]
        out.append("")
        if ifdef_testing:
            out.append("#ifdef CLASH95_TESTING")
        # A prior C-linkage declaration also governs an ordinary top-level
        # C++ definition. Keep includes outside this block: system headers
        # may contain C++ templates, and linkage must not leak into a TU.
        if body_lines:
            out += ["#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
        # Deliberate K&R residue (empty-paren decls: call-site-arity-dependent
        # legacy imports and untyped recovered vtable slots) is quarantined
        # from -Wstrict-prototypes: the spelling is load-bearing provenance,
        # the diagnostic adds no information, and the quarantine keeps a
        # future -Werror=strict-prototypes promotion binding everywhere else.
        clean = [l for l in body_lines if not knr_re.search(l)]
        knr = [l for l in body_lines if knr_re.search(l)]
        out += clean
        if knr:
            out += ["",
                    "/* Deliberate unprototyped residue: recovered call sites"
                    " depend on K&R semantics",
                    " * (varying arity) or the slot type is unrecovered;"
                    " kept verbatim as provenance. */",
                    "#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))",
                    "#pragma GCC diagnostic push",
                    '#pragma GCC diagnostic ignored "-Wstrict-prototypes"',
                    "#endif"]
            out += knr
            out += ["#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))",
                    "#pragma GCC diagnostic pop", "#endif"]
        if body_lines:
            out += ["", "#ifdef __cplusplus", '} // extern "C"', "#endif"]
        if ifdef_testing:
            out.append("#endif /* CLASH95_TESTING */")
        out += ["", f"#endif /* {guard} */", ""]
        return "\n".join(out)

    files: dict[Path, str] = {}
    tu_local_headers = {}
    for source, names in sorted(tu_locals.items()):
        local_path = Path(source).with_name(Path(source).stem + "_local.h")
        tu_local_headers[source] = local_path.name
        files[REPO / local_path] = hdr(
            "CLASH95_TU_" + local_path.stem.upper() + "_H",
            ["../recovered_types.h"],
            [fn_db[name]["decl"].rstrip().removesuffix(";")
             + f" CLASH95_LOCAL_SYMBOL({name});" for name in sorted(
                 names, key=lambda name: man_order.get(name, 1 << 30))],
            f"Own-TU declarations for '{source}' ({len(names)}); "
            "never included by another TU or the aggregate.")
    for s in SUBSYSTEMS:
        rel_types = "../recovered_types.h"
        files[REPO / "src" / s / f"{s}_api.h"] = hdr(
            f"CLASH95_{s.upper()}_API_H", [rel_types],
            [fn_db[n]["decl"] for n in api[s]],
            f"Public surface of '{s}': functions defined here and referenced "
            f"from another subsystem ({len(api[s])}).")
        files[REPO / "src" / s / f"{s}_internal.h"] = hdr(
            f"CLASH95_{s.upper()}_INTERNAL_H", [f"{s}_api.h"],
            [fn_db[n]["decl"] for n in internal[s]],
            f"Home-only functions of '{s}' ({len(internal[s])}); private to "
            f"the subsystem.")
        if s != "state":
            files[REPO / "src" / s / f"{s}_state.h"] = hdr(
                f"CLASH95_{s.upper()}_STATE_H", [rel_types],
                [gl_db[n]["decl"] for n in state_slice[s]],
                f"State-TU globals whose only consuming subsystem is '{s}' "
                f"({len(state_slice[s])}).")
            if consumer_layout:
                files[REPO / "src" / s / f"{s}_shared_state.h"] = hdr(
                    f"CLASH95_{s.upper()}_SHARED_STATE_H", [rel_types],
                    [gl_db[n]["decl"] for n in shared_consumers[s]],
                    f"Shared state-TU globals consumed by '{s}' "
                    f"({len(shared_consumers[s])}); declarations only, "
                    "private to this consuming subsystem.")
    files[REPO / "src" / "state" / "state_shared.h"] = hdr(
        "CLASH95_STATE_SHARED_H", ["../recovered_types.h"],
        [gl_db[n]["decl"] for n in shared],
        f"Globals consumed by two or more subsystems ({len(shared)}).")
    files[REPO / "src" / "state" / "state_local.h"] = hdr(
        "CLASH95_STATE_LOCAL_H", ["../recovered_types.h"],
        [gl_db[n]["decl"] for n in local],
        f"Globals referenced only within the state group itself ({len(local)}); "
        f"kept declared so definitions stay decl-checked.")
    files[REPO / "src" / "recovered_legacy_imports.h"] = hdr(
        "CLASH95_RECOVERED_LEGACY_IMPORTS_H", ["recovered_types.h"],
        [fn_db[n]["decl"] for n in legacy],
        f"Legacy CRT/Win32-era import declarations without manifest "
        f"definitions ({len(legacy)}); typed against "
        f"compatibility/decomp_runtime_stubs.cpp or explicit native call contracts.")
    files[REPO / "src" / "recovered_test_seams.h"] = hdr(
        "CLASH95_RECOVERED_TEST_SEAMS_H", ["recovered_types.h"],
        [fn_db[n]["decl"] for n in seams],
        f"CLASH95_TEST_VISIBLE prototypes ({len(seams)}): static in "
        f"production, external under CLASH95_TESTING.", ifdef_testing=True)
    agg_incs = ["recovered_types.h", "recovered_layout.h",
                "recovered_legacy_imports.h", "recovered_test_seams.h"]
    for s in SUBSYSTEMS:
        agg_incs.append(f"{s}/{s}_api.h")
        agg_incs.append(f"{s}/{s}_internal.h")
        if s != "state":
            agg_incs.append(f"{s}/{s}_state.h")
    agg_incs += ["state/state_shared.h", "state/state_local.h"]
    files[REPO / "src" / "recovered_all.h"] = hdr(
        "CLASH95_RECOVERED_ALL_H", agg_incs, [],
        "Aggregate of the narrowed headers for tests/unit ONLY; forbidden in "
        "production src/** (audited).")

    # ---- surface artifact ---------------------------------------------------
    surface = {
        "schema_version": 1,
        "subsystems": {
            s: {
                "api_functions": api[s],
                "internal_function_count": len(internal[s]),
                "state_globals": len(state_slice.get(s, [])),
            } for s in SUBSYSTEMS
        },
        "shared_globals": shared,
        "state_local_global_count": len(local),
        "legacy_import_count": len(legacy),
        "peer_edges": {},
    }
    if consumer_layout:
        surface["shared_state_consumers"] = shared_consumers
        surface["tu_shared_state_visibility"] = shared_visibility
    # peer edges: for each TU, which OTHER subsystems' api functions it uses
    edges: dict[str, set] = {}
    api_home_x = {fn_xname[n]: (s, n) for s in SUBSYSTEMS for n in api[s]}
    for rel, toks in tu_tokens.items():
        src_sub = tu_subsystem(rel)
        for tok in toks:
            hit = api_home_x.get(tok)
            if hit is None:
                continue
            tgt, key = hit
            if tgt != src_sub and defining_tu.get(key) != rel:
                edges.setdefault(f"{src_sub}->{tgt}", set()).add(key)
    surface["peer_edges"] = {k: len(v) for k, v in sorted(edges.items())}
    surface_text = json.dumps(surface, indent=1, sort_keys=True) + "\n"

    # ---- per-TU include blocks ----------------------------------------------
    def tu_block(rel: str, toks: set) -> str:
        sub = tu_subsystem(rel)
        incs = ["../recovered_layout.h"]
        if rel in tu_local_headers:
            incs.append(tu_local_headers[rel])
        incs.append(f"{sub}_internal.h")
        if sub != "state":
            incs.append(f"{sub}_state.h")
        else:
            incs += ["state_shared.h", "state_local.h"]
            incs += [f"../{t}/{t}_state.h" for t in SUBSYSTEMS if t != "state"]
        if sub != "state" and shared_visibility[rel]["referenced"]:
            incs.append(f"{sub}_shared_state.h" if consumer_layout
                        else "../state/state_shared.h")
        for t in SUBSYSTEMS:
            if t == sub:
                continue
            if any(fn_xname[name] in toks and defining_tu.get(name) != rel
                   for name in api[t]):
                incs.append(f"../{t}/{t}_api.h")
        if any(fn_xname[n] in toks for n in legacy):
            incs.append("../recovered_legacy_imports.h")
        if any(fn_xname[n] in toks and defining_tu.get(n) == rel
               for n in seams):
            incs.append("../recovered_test_seams.h")
        lines = [MARK_BEGIN] + [f'#include "{i}"' for i in incs] + [MARK_END]
        return "\n".join(lines)

    if args.check_tu_includes:
        stale = []
        for rel in sorted(tu_tokens):
            text = (REPO / rel).read_text(encoding="latin-1")
            m = re.search(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
                          text, flags=re.DOTALL)
            if not m:
                stale.append(f"{rel}: missing generated include block")
                continue
            want = tu_block(rel, tu_tokens[rel])
            if m.group(0).replace("\r\n", "\n") != want:
                stale.append(f"{rel}: include block differs from regeneration")
        for s_ in stale[:10]:
            print("STALE:", s_)
        print(f"tu-include check: {'PASS' if not stale else 'FAIL'} "
              f"({len(tu_tokens)} TUs, {len(stale)} stale)")
        return 0 if not stale else 1

    if args.write_tu_includes:
        s = args.write_tu_includes
        if s not in (*SUBSYSTEMS, "all"):
            print(f"unknown subsystem {s!r}")
            return 2
        replacements = {}
        for rel in sorted(tu_tokens):
            if s != "all" and tu_subsystem(rel) != s:
                continue
            p = REPO / rel
            text = p.read_bytes().decode("latin-1")
            block = tu_block(rel, tu_tokens[rel])
            try:
                new = replace_tu_include_block(text, block)
            except ValueError as exc:
                print(f"INVALID {rel}: {exc}")
                return 1
            if new != text:
                replacements[p] = new.encode("latin-1")
        # Validate every selected block before writing any source file.
        for path, content in replacements.items():
            path.write_bytes(content)
        print(f"updated {len(replacements)} TU include blocks in {s!r}")
        if not args.write:
            return 0

    state_path = REPO / manifest["state_owner"]
    state_text = state_path.read_text(encoding="latin-1")
    if TENTATIVE_BEGIN in state_text or re.search(r"^CLASH95_TENTATIVE ", state_text, re.M):
        try:
            files[state_path] = refresh_tentative_state(state_text)
        except ValueError as exc:
            print(f"INVALID {manifest['state_owner']}: {exc}")
            return 1

    if args.report:
        args.report.write_text(surface_text, encoding="utf-8")
        print(f"report -> {args.report}")

    summary = ("api: " + " ".join(f"{s}={len(api[s])}" for s in SUBSYSTEMS)
               + f" | internal total={sum(len(v) for v in internal.values())}"
               + f" | state slices total={sum(len(v) for v in state_slice.values())}"
               + f" shared={len(shared)} local={len(local)}"
               + f" | legacy={len(legacy)} seams={len(seams)}")
    if consumer_layout:
        summary += " | shared declarations visible=" + str(
            sum(len(v["visible"]) for v in shared_visibility.values()))
    print(summary)

    if args.check:
        stale = []
        for path, text in files.items():
            cur = path.read_text(encoding="latin-1") if path.exists() else None
            if cur is None or cur.replace("\r\n", "\n") != text:
                stale.append(str(path.relative_to(REPO)))
        cur_surface = (SURFACE_OUT.read_text(encoding="utf-8")
                       if SURFACE_OUT.exists() else None)
        if cur_surface != surface_text:
            stale.append(str(SURFACE_OUT.relative_to(REPO)))
        if stale:
            print("STALE:", *stale[:10])
            return 1
        print("subsystem headers up to date")
        return 0

    if args.write:
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="latin-1", newline="")
        SURFACE_OUT.write_text(surface_text, encoding="utf-8")
        print(f"wrote {len(files)} generated files + {SURFACE_OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
