#!/usr/bin/env python3
"""Generate packed struct overlays for the recovered game records.

Emits, from the `typed_eligible` + `canonical` records in
``RECOVERED_STRUCTURES.json``, a `typedef struct __attribute__((packed))` per
record with explicit gap members for every unrecovered span (so `sizeof` equals
the recovered stride) plus a `CLASH95_STATIC_ASSERT` on `sizeof` and each
recovered field's `offsetof`. The header is additive (types + assertions only, no code
or data) so the build stays byte-identical; a layout error fails a static_assert.

Pointers are 4-byte `low32_ptr` handles because the reconstruction runs the
original 32-bit memory model but is compiled under LP64 (native pointers would be
8 bytes and blow the pins).

Usage:
  python3 tools/gen_recovered_structs.py          # rewrite src/recovered_structs.h
  python3 tools/gen_recovered_structs.py --check   # verify without writing
"""
import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import literal_common as lc

CATALOG = os.path.join(lc.REPO, "RECOVERED_STRUCTURES.json")
TYPES_H = os.path.join(lc.REPO, "src/recovered_types.h")
OUT_REL = "src/recovered_structs.h"

WIDTH = {
    "int8_t": 1, "uint8_t": 1, "char": 1, "int16_t": 2, "uint16_t": 2,
    "short": 2, "int32_t": 4, "uint32_t": 4, "int": 4, "low32_ptr": 4,
    "int64_t": 8, "uint64_t": 8,
}

HEADER = """\
/* GENERATED by tools/gen_recovered_structs.py -- do not edit by hand.
 *
 * Packed struct overlays for the recovered game records, with explicit gap
 * members for unrecovered spans and compile-time pins on sizeof/offsetof.
 * A layout mismatch fails the build. Regenerate after editing
 * RECOVERED_STRUCTURES.json. Pointers are 4-byte low32_ptr handles (the
 * reconstruction's 32-bit memory model compiled under LP64).
 */

#ifndef CLASH95_RECOVERED_STRUCTS_H
#define CLASH95_RECOVERED_STRUCTS_H

#include <stddef.h>
#include "recovered_types.h"

typedef uint32_t low32_ptr;
"""

FOOTER = "\n#endif\n"


def rec_size(r):
    return r.get("stride") or r.get("size")


def split_ctype(ct):
    """'UnitSlotRecord[10]' -> ('UnitSlotRecord', '[10]', 10)."""
    m = re.match(r"^([A-Za-z_]\w*)((?:\[\d+\])*)$", ct)
    elem, dims = m.group(1), m.group(2)
    count = 1
    for x in re.findall(r"\[(\d+)\]", dims):
        count *= int(x)
    return elem, dims, count


def field_width(f, by_name):
    elem, _dims, count = split_ctype(f["c_type"])
    if elem in WIDTH:
        return WIDTH[elem] * count
    if elem in by_name:
        return rec_size(by_name[elem]) * count
    return None


def derive_skip_set():
    """Struct/enum names already typedef'd in recovered_types.h."""
    txt = open(TYPES_H, encoding="utf-8").read()
    return set(re.findall(r"}\s*([A-Za-z_]\w*)\s*;", txt))


def topo(emit, by_name):
    emit_names = {r["name"] for r in emit}
    order, seen = [], set()

    def visit(r):
        if r["name"] in seen:
            return
        seen.add(r["name"])
        for f in r.get("fields", []):
            elem, _d, _c = split_ctype(f["c_type"])
            if elem in emit_names and elem != r["name"]:
                visit(by_name[elem])
        order.append(r)

    for r in emit:
        visit(r)
    return order


def generated_text():
    recs = json.load(open(CATALOG, encoding="utf-8"))
    by_name = {r["name"]: r for r in recs}
    skip = derive_skip_set()
    emit = [r for r in recs
            if r.get("typed_eligible") and r.get("canonical") is not False
            and r["name"] not in skip]
    lines = [HEADER.rstrip()]
    for r in topo(emit, by_name):
        name, size = r["name"], rec_size(r)
        flds = sorted(r["fields"], key=lambda f: f["offset"])
        lines.append("")
        lines.append("typedef struct __attribute__((packed)) %s {" % name)
        cursor = 0
        for f in flds:
            off = f["offset"]
            if off > cursor:
                lines.append("  unsigned char unrecovered_0x%02X_0x%02X[%d];"
                             % (cursor, off, off - cursor))
            elem, dims, _c = split_ctype(f["c_type"])
            lines.append("  %s %s%s;" % (elem, f["c_name"], dims))
            cursor = off + field_width(f, by_name)
        if cursor < size:
            lines.append("  unsigned char unrecovered_0x%02X_0x%02X[%d];"
                         % (cursor, size, size - cursor))
        lines.append("} %s;" % name)
        lines.append('CLASH95_STATIC_ASSERT(sizeof(%s) == %d, "%s size");'
                     % (name, size, name))
        for f in flds:
            lines.append('CLASH95_STATIC_ASSERT(offsetof(%s, %s) == %d, "%s.%s");'
                         % (name, f["c_name"], f["offset"], name, f["c_name"]))
    return "\n".join(lines) + FOOTER


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated_text()
    out = os.path.join(lc.REPO, OUT_REL)
    if args.check:
        try:
            current = open(out, encoding="utf-8").read()
        except OSError as error:
            print("recovered_structs check failed: %s" % error, file=sys.stderr)
            return 1
        if current != content:
            print("recovered_structs is stale: %s" % OUT_REL, file=sys.stderr)
            return 1
        print("recovered_structs check: PASS (%s)" % OUT_REL)
        return 0
    with open(out, "w", newline="\n") as f:
        f.write(content)
    print("wrote %s (%d structs, %d pins)"
          % (OUT_REL, content.count("typedef struct"),
             content.count("CLASH95_STATIC_ASSERT")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
