#!/usr/bin/env python3
"""Generate extern prototypes for the pure testable function set.

Reads the pure-set JSON (from pure_function_set.py) and extracts each
function's real signature from clash95.c, emitting a header the unit tests
include so calls are type-correct.
"""
import json
import sys

SRC = "clash95.c"


def main():
    pure = json.load(open(sys.argv[1]))
    lines = open(SRC, errors="replace").readlines()
    out = [
        "/* GENERATED by tools/gen_pure_decls.py - extern decls for pure set. */",
        "#ifndef CLASH95_PURE_DECLS_H",
        "#define CLASH95_PURE_DECLS_H",
        '#include "defs.h"',
        "",
    ]
    n = 0
    for f in pure["functions"]:
        start = f["start_line"] - 1
        # accumulate until the '{' that opens the body (depth-0)
        sig = []
        depth = 0
        found = False
        for i in range(start, min(start + 40, len(lines))):
            s = lines[i]
            cut = None
            for j, ch in enumerate(s):
                if ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
                elif ch == "{" and depth <= 0:
                    cut = j
                    break
            if cut is not None:
                sig.append(s[:cut])
                found = True
                break
            sig.append(s)
        if not found:
            continue
        decl = " ".join(x.strip() for x in sig).strip()
        decl = " ".join(decl.split())
        if not decl:
            continue
        out.append("extern " + decl + ";")
        n += 1
    out += ["", "#endif", ""]
    open("tests/unit/clash95_pure_decls.h", "w").write("\n".join(out))
    print(f"wrote {n} extern decls to tests/unit/clash95_pure_decls.h")


if __name__ == "__main__":
    main()
