#!/usr/bin/env python3
"""Generate src/core/005_constant_guard.inc.c from the prelude constant block.

Emits one gnu89 negative-array-size assert per numeric object-like #define in
src/clash95_prelude.inc.c, pinning every named constant to its current value.
The generated file is committed; if a later edit changes a constant's value,
the stale committed guard fails the build until the guard is deliberately
regenerated -- a compile-time tripwire for the memory-map constants that the
magic-number substitution batches depend on (there is no binary-diff gate in
this repo; see docs/BUILD_AND_TEST.md).

Usage: python3 tools/gen_constant_guard.py   (rewrites the fragment in place)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import literal_common as lc

OUT_REL = "src/core/005_constant_guard.inc.c"

HEADER = """\
/* GENERATED by tools/gen_constant_guard.py -- do not edit by hand.
 *
 * Compile-time pins for every numeric object-like #define in
 * src/clash95_prelude.inc.c. A mismatch makes the array size negative and
 * fails the build, so an accidental edit to a memory-map constant cannot
 * slip through compile+link (this repo has no binary-diff gate).
 * Regenerate deliberately after intentional constant changes.
 */
"""


def main():
    macros = lc.parse_prelude_macros()
    lines = [HEADER]
    for name in sorted(macros):
        macro = macros[name]
        value = lc.numeric_macro_value(macro)
        if value is None:
            continue
        spelled = macro["body"].strip()
        lines.append(
            "typedef char clash95_guard_%s[(%s) == (%s) ? 1 : -1];"
            % (name, name, spelled)
        )
    # pin every prelude enum member to its value too, so an accidental edit to
    # an enum block (reorder, missing initializer) fails the build.
    enums = lc.parse_prelude_enums()
    for name in sorted(enums):
        lines.append(
            "typedef char clash95_guard_%s[(%s) == (%d) ? 1 : -1];"
            % (name, name, enums[name])
        )
    out = os.path.join(lc.REPO, OUT_REL)
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d guards)" % (OUT_REL, len(lines) - 1))


if __name__ == "__main__":
    main()
