#!/usr/bin/env python3
"""Regenerate the #include block for coverage test-case files in test_all.c.

Scans tests/unit/cases/test_*.c (skipping *.bad and test_smoke.c) and rewrites the region
between the BEGIN/END markers in tests/unit/test_all.c with one #include per
present case file, in sorted order. test_smoke.c is included explicitly by
test_all.c and is intentionally excluded here. Idempotent.
"""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEST_ALL = os.path.join(ROOT, "tests/unit/test_all.c")
BEGIN = "/* >>> COV CASES BEGIN (generated by tools/wire_cov_cases.py) */"
END = "/* <<< COV CASES END */"


def main():
    # All case files except test_smoke.c (included explicitly by test_all.c)
    # and quarantined *.bad files.
    cases = sorted(
        os.path.basename(p)
        for p in glob.glob(os.path.join(ROOT, "tests/unit/cases/test_*.c"))
        if not p.endswith(".bad") and os.path.basename(p) != "test_smoke.c"
    )
    block = [BEGIN]
    for c in cases:
        block.append('#include "cases/%s"' % c)
    block.append(END)
    text = open(TEST_ALL).read()
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        "\n".join(block),
        text,
        flags=re.S,
    )
    open(TEST_ALL, "w").write(new)
    print("wired %d case files: %s" % (len(cases), ", ".join(cases)))


if __name__ == "__main__":
    main()
