/* Canonical recovered function declarations; validated by the split-source audit. */
#ifndef CLASH95_RECOVERED_FUNCTIONS_H
#define CLASH95_RECOVERED_FUNCTIONS_H

#include "recovered_foundation.h"

/* Legacy imports whose return types are retained from decompiler comments. */
int __fastcall unknown_libname_5();
int _wcpp_4_ctor_array_storage_1s__();
int __fastcall _wcpp_4_dtor_array__();
int __fastcall vsprintf_();
int __fastcall _doclose_();
int __cdecl close_();
__int64 __thiscall _I8D();
_DWORD __stdcall sub_47C181();
_DWORD __stdcall sub_47C1C0();
int plib_malloc__1();
int j_rand_();
int unknown_libname_7();
_DWORD sub_48455B();
int __fastcall stricmp_();
_DWORD __stdcall beginthreadex_();
int __fastcall fputs_();
int __fastcall strncpy_();
int __thiscall unknown_libname_2();
int __fastcall tolower_();
int __cdecl _set_errno_dos_();
int __cdecl _set_errno_nt_();
int _InitRtns();
int __fastcall _FiniRtns();
int __fastcall _wcpp_4_fatal_runtime_error__();
int _allocfp_();
int _freefp_();
int _chktty_();
int __fastcall _flush_();
__int64 __fastcall ftell_();
int __fastcall lseek_();
int _ioalloc_();
int __fastcall sub_488A97();
int __cdecl _SetIOMode_();
__int64 __fastcall fgetc_();
int __fastcall setvbuf_();
int __thiscall findclose_();
int __fastcall findnext_();
int __fastcall getcwd_();
int __fastcall strncmp_();
int __thiscall fflush_();
int unknown_libname_8();
int tell_();
int __fastcall _fatal_runtime_error_();
int sub_4965FF();
int __fastcall sub_496643();
int __fastcall unknown_libname_10();
int __thiscall _wcpp_4_corrupted_stack__();
int __fastcall _wcpp_4_call_terminate__();
__int64 __thiscall _wcpp_4_pgm_thread__();
_DWORD __stdcall _wcpp_4_exc_setup__();
int __thiscall stackavail_();
int _wcpp_4_stab_trav_init__();
int _wcpp_4_stab_trav_next__();
int __fastcall _wcpp_4_stab_trav_move__();
int _NTConsoleOutput_();
int _NTAtMaxFiles_();
int _NTRemoveFileHandle_();
int _NTInitFileHandles_();
int __cdecl _NTGetFakeHandle_();
int _lib_GetModuleFileNameW_(_DWORD module, _WORD *buffer, _DWORD byte_count);
int _init_stack_limits_();
int __fastcall calloc_();
int _GetThreadData_();
int _ReallocThreadData_();
int __fastcall _AddThreadData_();
int _RemoveThreadData_();
int __fastcall _InitThreadData_();
int __fastcall wctomb_();
int __fastcall _clib_ulltoa_();
int __fastcall sub_4B5A33();
int __fastcall isatty_();
int getenv_();
int __fastcall _brktime_();
double __fastcall strtod_();
int __fastcall _NTFindNextFileWithAttr_();
__int64 _nt_filetime_cvt_();
int unknown_libname_13();
double __cdecl IF_ASIN();
double IF_DSINH();
double IF_DCOSH();
double IF_DTANH();
double  IF_DPOW();
int _FDFS();
__int64 __fastcall _I8M();
int __fastcall nrealloc_();
int __fastcall wcslen_();
int __fastcall memcpy_();
void __noreturn endthread_();
int __fastcall wcstombs_();
int mbclen_();
int __fastcall _ccmdline_();
int __thiscall towupper_();
int __fastcall ismbclegal_();
int __stdcall DirectInputCreateA();
int __stdcall DirectSoundCreate();
int __cdecl ICClose();
int __stdcall ICGetDisplayFormat();
int __stdcall ICLocate();
int AVIFileExit();
int __stdcall AVIStreamEndStreaming();
int __cdecl ICDecompress();
UINT __stdcall waveOutGetNumDevs();
MMRESULT __stdcall waveOutPrepareHeader();
MMRESULT __stdcall waveOutUnprepareHeader();
BOOL __stdcall CreateProcessA();
BOOL __stdcall DuplicateHandle();
void __stdcall ExitProcess();
BOOL __stdcall FindClose();
HRSRC __stdcall FindResourceA();
BOOL __stdcall GetCPInfo();
LPWSTR __stdcall GetCommandLineW();
HANDLE __stdcall GetCurrentProcess();
HANDLE __stdcall GetCurrentThread();
LPCH __stdcall GetEnvironmentStrings();
DWORD __stdcall GetFileAttributesA();
DWORD __stdcall GetModuleFileNameA();
UINT __stdcall GetOEMCP();
HGLOBAL __stdcall GlobalFree();
HMODULE __stdcall LoadLibraryA();
LPVOID __stdcall LockResource();
int __stdcall MultiByteToWideChar();
BOOL __stdcall ReadFile();
BOOL __stdcall ResetEvent();
BOOL __stdcall SetEnvironmentVariableA();
BOOL __stdcall SetEvent();
BOOL __stdcall SetThreadPriority();
DWORD __stdcall TlsAlloc();
LPVOID __stdcall TlsGetValue();
LONG __stdcall UnhandledExceptionFilter();
BOOL __stdcall WriteFile();
HFILE __stdcall lopen();

/* Normalized declarations for every recovered function definition. */
CLASH95_INTERNAL void Compat_InvokeNativeComMethod0 (int object_handle, unsigned int x86_vtable_offset);
CLASH95_INTERNAL void Compat_InvokeCompactSurfaceDestructor (int surface_handle, int flags);
CLASH95_INTERNAL int Compat_DirectDrawSurfaceHandleIsLost (int surface_handle);
extern int Surface_SwapDirtyTrackingFlag (int surface, int new_flag);
extern int Menu_DrawFrameBackdrop();
CLASH95_INTERNAL void WorldMap_EnsureActionButtonWidgetTable (void);
extern int WorldMap_RenderPlayerTurnIntroScreen (char a1, DWORD a2);
extern void WorldMap_EnableFrameRedraw();
CLASH95_INTERNAL void Battle_ResetInputScriptReader (void);
extern TextSpriteResourceSlotRecord *TextSprite_GetResourceSlot (int slot_index);
extern int TextSprite_MeasureStringExtent (_BYTE *text);
extern void TextSprite_BuildOrLoadCachedFont (int slotIndex, _BYTE *fontData, int a3, char a4, DWORD allocContext);
extern int Font_InitGlyphFallbackTablesForLanguage();
extern void MiniMap_RedrawAllTiles();
extern short int *UnitStack_RemoveFromTile (short int *stack, double a2);
extern short int *UnitStack_UnlinkIfEmpty (short int *result, double a2);
extern int Debug_LogUnitSquadDetails (int stackPtr, DWORD a2);
extern int Unit_DebugDumpFormationSizesForStackIndex (int stackIndex, DWORD a2);
extern void *UnitSlots_ExtractSpecialEntriesForBuildingAttack (char *slotArray, int slotCount, char *extractedOut);
extern int UnitSlots_AppendEntriesForBuildingAttack (char *destSlots, char *srcSlots);
CLASH95_INTERNAL BOOL UnitSlot_PredicateAlways (int slotPtr);
extern int BattleUnitEntry_CopyMergingPackedFlags (int result, int srcEntry);
extern int UnitSpriteCache_GetOrLoadEntry (short unsigned int unitType, char ownerColor, unsigned char animFrame, unsigned char facing, DWORD a5, int a6);
CLASH95_INTERNAL int Compat_CountPrintfArgs32 (const char *format);
CLASH95_INTERNAL BOOL Building_NewAt (int row, int column, int building_type, DWORD stack_index, double st7_0, char *name, int force);
extern char Building_UpdateGarrisonTrainRepairTimers (unsigned char *buildingPtr, double a2);
extern int Building_CalcGarrisonAverageHealthPercent (int buildingPtr);
extern int Unit_FindById (int a1);
CLASH95_INTERNAL void Castle_EnsureCompositeStatusWidget (void);
CLASH95_INTERNAL void BuildingGarrisonDialog_EnsureActionWidgets (int building_record);
CLASH95_INTERNAL void Diagnostics_ResetFrameDumpOnBattleEnter (void);
CLASH95_INTERNAL void Diagnostics_PrimeBattleSafeCursorOnTurnLoop (void);
CLASH95_INTERNAL int Diagnostics_CountBattleUnitsForOwner (int owner);
CLASH95_INTERNAL int Diagnostics_CountBattleUnitsTotal (void);
CLASH95_INTERNAL int Diagnostics_CountBattleDeploymentBucketEntries (void);
CLASH95_INTERNAL unsigned char *BattleDeploymentBucketReadPointer (int byte_offset);
CLASH95_INTERNAL int Diagnostics_IsBattleTileDrawTraceEnabled (void);
CLASH95_INTERNAL void Diagnostics_TraceBattlefieldClickEvent (const char *stage, int local_x, int local_y, int tile_x, int tile_y, int occupant_slot);
extern int Unit_CountSelectedGroupMembers (int stackPtr);
extern BOOL Unit_CanMoveSelectionFromGroupToTile (int a1, _DWORD *a2, int a3, int a4);
extern int CastleProduction_SetExitSignal (int widget);
extern int Player_CheckSoleSurvivorAndShowVictoryBanner (int player_index);
CLASH95_INTERNAL void Compat_SyncRenderCursorGlobals (const _DWORD *render_state);
CLASH95_INTERNAL CompatRenderStateTail *Compat_RenderStateTailFields (int render_state);
CLASH95_INTERNAL void Compat_MenuProbeTraceRenderInput (const char *phase, int render_state, int arg0, int arg1, int extra0, int extra1);
CLASH95_INTERNAL _DWORD *Compat_RenderStateSurface (int render_state, unsigned int field_offset);
CLASH95_INTERNAL _DWORD *Compat_RenderStateCursorDescriptor (int render_state);
extern int (*CAviDecompressor_FindColorConvertRoutine (int (**a1) (/* ??? */), int (**a2) (/* ??? */))) (/* ??? */);
extern void PlayAvi (char *fileName, IDirectDrawSurface *ddSurface, int x, int y, int (*continueCallback) (void), int openFlags);
extern unsigned int Audio_MapDSoundHResultToErrorCode (unsigned int result);
extern int Audio_ClipMixBufferToPCM16 (int sampleCount, int destBase, int destOffset, int *mixBuffer);
CLASH95_INTERNAL void Compat_StringHolderInitText (_DWORD *holder, const char *source);
CLASH95_INTERNAL const char **Compat_StringHolderBuildParentPath (_DWORD *holder, const char *source_text);
CLASH95_INTERNAL _DWORD *Compat_StringHolderBuildLeafName (_DWORD *holder, const char *source_text);
CLASH95_INTERNAL int Compat_StringHolderDestroyStack (_DWORD *holder, char flags);
CLASH95_INTERNAL int Compat_FileSystemOnMounted (int mounted_file_system, int *root_file_system);
extern _DWORD *Rules_CreateFact (int slot_count);
extern int Mem_SetAllocFlag (int new_alloc_flag, int a2);
extern int Rules_PrintMultifieldRange (int result, int theSegment, int end, int begin, int printParens);
extern int Rules_CheckLiteralSlotValueConstraint (int *exprList, int thePlace);
extern _DWORD *Lexer_FindSlotWithIndex (int theDeftemplate, int slotName, _DWORD *whichOne);
extern char *Rules_SavePPBuffer (char *result);
extern int Rules_BackupPPBuffer();
extern int Rules_SetDynamicConstraintChecking (int newValue, int a2);
extern int (*ProcParam_PushEvaluatedArgumentFrame (_DWORD *a1, int a2, int a3, int a4, double a5, int (*a6) (void))) (void);
extern int Rules_ImportExportConflictMessage (int constructName, int itemName, int causedByConstruct);
CLASH95_INTERNAL double Parser_NumberValueAsComparableDouble (int type, int value);
CLASH95_INTERNAL int sub_4A9430_Impl (int (*callback) (int, intptr_t), int construct_index, intptr_t callback_context, int stop_on_watch);
CLASH95_INTERNAL int sub_4A94D0_Impl (int construct_name, int construct_data, int owner_symbol);
extern int Rules_CEAllocDefaultNode();
extern int Rules_CEFreeNode (int result);
extern int Parser_AddFunctionParser (_BYTE *function_name, int handler);
extern int Rules_ParseModify (int top, int logicalName);
extern int Rules_ParseDuplicate (int top, int logicalName);

#ifdef CLASH95_TESTING
/* Frozen pure helpers exported only by coverage/test builds. */
CLASH95_TEST_VISIBLE uintptr_t RenderSurface_GetCompactMethodPointer (_DWORD *surface, unsigned int table_offset);
CLASH95_TEST_VISIBLE int WorldMap_DeferBuildingActionCallback (uintptr_t widget);
CLASH95_TEST_VISIBLE const char *UnitType_GetResourceKey (int unit_type);
CLASH95_TEST_VISIBLE int UI_InvokeWidgetTransitionCallback (uintptr_t widget, int callback_arg);
CLASH95_TEST_VISIBLE int UI_InvokeWidgetActionCallback (uintptr_t widget);
CLASH95_TEST_VISIBLE unsigned int Compat_WidgetPackedField (uintptr_t widget, unsigned int field_offset);
CLASH95_TEST_VISIBLE unsigned int Compat_WidgetSpriteSetHandle (uintptr_t widget);
CLASH95_TEST_VISIBLE int Castle_InvokePrisonerPanel (int building_record, int callback_context, DWORD runtime_context);
CLASH95_TEST_VISIBLE int Castle_InvokeEconomyPanel (int building_record, int callback_context, DWORD runtime_context);
CLASH95_TEST_VISIBLE void BuildingGarrisonDialog_WriteActionWidgetRecord (unsigned char *record, int left, int top, int flags, int sprite_index_base, int sprite_index_selected_base, void *action_callback, const char *text_pl, const char *text_en, const char *text_de, const char *sound);
CLASH95_TEST_VISIBLE int Diagnostics_IsWorldMapActionVerbose (void);
CLASH95_TEST_VISIBLE int Diagnostics_ShouldTraceWorldMapActionStage (const char *stage);
CLASH95_TEST_VISIBLE void Diagnostics_TraceCastleHotspots (int surface_handle);
CLASH95_TEST_VISIBLE WCCompatListBase *WCCompat_ListFromBase (WCIsvListBase *this);
CLASH95_TEST_VISIBLE WCCompatListBase *WCCompat_ListFromHandle (int list_handle);
CLASH95_TEST_VISIBLE WCCompatLink *WCCompat_LinkFromHandle (int link_handle);
CLASH95_TEST_VISIBLE void QueenMarriageProposal_WriteButtonWidgetRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, _DWORD **sprite_set_holder, const char *sound_name);
CLASH95_TEST_VISIBLE void QueenMarriageProposal_RebuildButtonWidgets (unsigned char *widgets, _DWORD **sprite_set_holder, int confirm_left, int top, int cancel_left);
CLASH95_TEST_VISIBLE void YesNoWindow_WriteButtonWidgetRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback);
CLASH95_TEST_VISIBLE void YesNoWindow_RebuildButtonWidgets (unsigned char *widgets, int confirm_left, int top, int cancel_left);
CLASH95_TEST_VISIBLE void MainMenu_WriteButtonWidgetTemplateRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, const char *sound_name);
CLASH95_TEST_VISIBLE void CampaignMenu_WriteButtonWidgetTemplateRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, const char *sound_name);
CLASH95_TEST_VISIBLE void Mission_TraceObjectiveBlocked (int mission_index, int detail_a, int detail_b, int detail_c);
CLASH95_TEST_VISIBLE int Compat_MenuProbeTraceEnabled (void);
CLASH95_TEST_VISIBLE uintptr_t Compat_RenderStateMethodPointer (int render_state, unsigned int table_offset);
CLASH95_TEST_VISIBLE void Compat_StringHolderAssignJoined (_DWORD *holder, const char *prefix, const char *suffix);
CLASH95_TEST_VISIBLE void Compat_StringHolderInsertText (_DWORD *holder, int index, const char *inserted_text);
CLASH95_TEST_VISIBLE void Compat_FileSystemQueryResultRelease (_DWORD *opened_query);
CLASH95_TEST_VISIBLE DWORD Compat_FileTimeToUnixSeconds (DWORD low_part, DWORD high_part);
CLASH95_TEST_VISIBLE int Runtime_ExprDescriptorNoop (int value);
#endif

#endif
