/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* CLASH95_TEST_VISIBLE prototypes (30): static in production, external under CLASH95_TESTING. */
#ifndef CLASH95_RECOVERED_TEST_SEAMS_H
#define CLASH95_RECOVERED_TEST_SEAMS_H

#include "recovered_types.h"

#ifdef CLASH95_TESTING
#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE int Castle_InvokePrisonerPanel (int building_record, int callback_context, DWORD runtime_context);
CLASH95_TEST_VISIBLE int Castle_InvokeEconomyPanel (int building_record, int callback_context, DWORD runtime_context);
CLASH95_TEST_VISIBLE void BuildingGarrisonDialog_WriteActionWidgetRecord (unsigned char *record, int left, int top, int flags, int sprite_index_base, int sprite_index_selected_base, void *action_callback, const char *text_pl, const char *text_en, const char *text_de, const char *sound);
CLASH95_TEST_VISIBLE int Diagnostics_IsWorldMapActionVerbose (void);
CLASH95_TEST_VISIBLE int Diagnostics_ShouldTraceWorldMapActionStage (const char *stage);
CLASH95_TEST_VISIBLE void Diagnostics_TraceCastleHotspots (int surface_handle);
CLASH95_TEST_VISIBLE WCCompatListBase *WCCompat_ListFromBase (WCIsvListBase *this_);
CLASH95_TEST_VISIBLE WCCompatListBase *WCCompat_ListFromHandle (int list_handle);
CLASH95_TEST_VISIBLE WCCompatLink *WCCompat_LinkFromHandle (int link_handle);
CLASH95_TEST_VISIBLE void Compat_StringHolderAssignJoined (_DWORD *holder, const char *prefix, const char *suffix);
CLASH95_TEST_VISIBLE void Compat_StringHolderInsertText (_DWORD *holder, int index, const char *inserted_text);
CLASH95_TEST_VISIBLE void Compat_FileSystemQueryResultRelease (_DWORD *opened_query);
CLASH95_TEST_VISIBLE uintptr_t RenderSurface_GetCompactMethodPointer (_DWORD *surface, unsigned int table_offset);
CLASH95_TEST_VISIBLE DWORD Compat_FileTimeToUnixSeconds (DWORD low_part, DWORD high_part);
CLASH95_TEST_VISIBLE int Runtime_ExprDescriptorNoop (int value);
CLASH95_TEST_VISIBLE void Mission_TraceObjectiveBlocked (int mission_index, int detail_a, int detail_b, int detail_c);
CLASH95_TEST_VISIBLE int Compat_MenuProbeTraceEnabled (void);
CLASH95_TEST_VISIBLE uintptr_t Compat_RenderStateMethodPointer (int render_state, unsigned int table_offset);
CLASH95_TEST_VISIBLE const char *UnitType_GetResourceKey (int unit_type);
CLASH95_TEST_VISIBLE int UI_InvokeWidgetTransitionCallback (uintptr_t widget, int callback_arg);
CLASH95_TEST_VISIBLE int UI_InvokeWidgetActionCallback (uintptr_t widget);
CLASH95_TEST_VISIBLE unsigned int Compat_WidgetPackedField (uintptr_t widget, unsigned int field_offset);
CLASH95_TEST_VISIBLE unsigned int Compat_WidgetSpriteSetHandle (uintptr_t widget);
CLASH95_TEST_VISIBLE int WorldMap_DeferBuildingActionCallback (uintptr_t widget);
CLASH95_TEST_VISIBLE void QueenMarriageProposal_WriteButtonWidgetRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, _DWORD **sprite_set_holder, const char *sound_name);
CLASH95_TEST_VISIBLE void QueenMarriageProposal_RebuildButtonWidgets (unsigned char *widgets, _DWORD **sprite_set_holder, int confirm_left, int top, int cancel_left);
CLASH95_TEST_VISIBLE void YesNoWindow_WriteButtonWidgetRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback);
CLASH95_TEST_VISIBLE void YesNoWindow_RebuildButtonWidgets (unsigned char *widgets, int confirm_left, int top, int cancel_left);
CLASH95_TEST_VISIBLE void MainMenu_WriteButtonWidgetTemplateRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, const char *sound_name);
CLASH95_TEST_VISIBLE void CampaignMenu_WriteButtonWidgetTemplateRecord (unsigned char *record, int left, int top, int sprite_index_base, int sprite_index_selected_base, int action_callback, const char *sound_name);

#ifdef __cplusplus
} // extern "C"
#endif
#endif /* CLASH95_TESTING */

#endif /* CLASH95_RECOVERED_TEST_SEAMS_H */
