/* Canonical recovered shared types, enums, structs, and memory-map
 * constants; extracted from recovered_foundation.h (original relative
 * order preserved). Validated by the split-source audit and pinned by
 * recovered_layout.h. */
#ifndef CLASH95_RECOVERED_TYPES_H
#define CLASH95_RECOVERED_TYPES_H

#include "recovered_abi.h"
#include <stddef.h>

/* Shared recovered declarations, types, macros, globals, and data.
 * Private recovered declarations shared by split translation units. */

/* This file was generated by the Hex-Rays decompiler version 9.0.0.240925.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/









#define PLAYER_DATA_STRIDE 1423
#define PLAYER_RUNTIME_STATE_OFFSET 140024
/* Size of the gameData state image: allocated, memset, and written/read
 * verbatim by saveGame/SaveSlot_LoadGame (docs/SAVE_DAT_FORMAT.md: 0x8F29E =
 * 586398 bytes; the .dat file adds a 16-byte label). */
#define GAMEDATA_SAVE_IMAGE_BYTES 0x8F29E
#define PLAYER_DISPLAY_NAME_OFFSET 4
#define PLAYER_CAMERA_LEFT_OFFSET 15
#define PLAYER_CAMERA_TOP_OFFSET 19
#define PLAYER_MINIMAP_VISIBLE_OFFSET 23
#define PLAYER_IS_HUMAN_OFFSET 27
#define PLAYER_AI_INTELLIGENCE_OFFSET 31
#define PLAYER_RELIGION_FLAG_OFFSET 39
#define PLAYER_TECH_LEVEL_OFFSET 47
#define PLAYER_LAST_SHOWN_TECH_LEVEL_OFFSET 48
#define PLAYER_BATTLE_IDLE_FLAG_OFFSET 49
#define PLAYER_BATTLE_IDLE_TURN_COUNT_OFFSET 53
#define PLAYER_REVEALED_TILES_OFFSET 57
#define PLAYER_REVEALED_TILE_ROW_BYTES 13
#define PLAYER_QUEEN_RELATIONSHIP_STATE_OFFSET 1419
#define PLAYER_QUEEN_PORTRAIT_INDEX_OFFSET 1420
#define PLAYER_QUEEN_NEXT_RELATIONSHIP_CHECK_TURN_OFFSET 1421
#define MAP_THEME_INDEX_OFFSET 140016
#define ACTIVE_MISSION_INDEX_OFFSET 140017
#define MISSION_FAILURE_FLAG_OFFSET 140021
#define GAME_TURN_COUNTER_OFFSET 140022
#define MAP_WIDTH_TILES_OFFSET 140000
#define MAP_HEIGHT_TILES_OFFSET 140004
#define MAP_VIEW_LEFT_OFFSET 140008
#define MAP_VIEW_TOP_OFFSET 140012
#define PORT_ROW_OFFSET 586374
#define PORT_COLUMN_OFFSET 586378
#define PORT_NEXT_REINFORCEMENT_TURN_OFFSET 586382
#define PORT_REINFORCEMENT_READY_FLAG_OFFSET 586386
#define PORT_REINFORCEMENT_UNIT_COUNT_OFFSET 586390
#define PORT_SHORE_VARIANT_FLAG_OFFSET 586394
#define BUILDING_RECORD_SIZE 467
#define BUILDING_TABLE_OFFSET 509674
#define BUILDING_TRANSFER_TARGET_LIST_CAPACITY 100
#define BUILDING_ECONOMY_DIALOG_WIDGET_COUNT 10
#define BUILDING_GARRISON_DIALOG_WIDGET_COUNT 5
#define BUILDING_GARRISON_SERVICE_STATE_OFFSET 390
#define BUILDING_GARRISON_SERVICE_STATE_COUNT 12
#define BUILDING_GARRISON_TRAINING_TURNS_MASK 0x07
#define BUILDING_GARRISON_REPAIR_TURNS_MASK 0x38
/* Castle add-on bitfield at building record +416. Bit->add-on mapping proven
 * by Rules_AssertCastleFact (100_strategic.inc.c: bit -> szpital/koszary/
 * warsztat/szkola/kuznia), the g_CastleAddon*MissingFlag reads, and the
 * Rules_HostBuy* set paths (060_buildings.inc.c). See RECOVERED_STRUCTURES.json
 * BuildingRecord.castle_addon_flags. */
#define BUILDING_ADDON_FLAGS_OFFSET 416
#define BUILDING_ADDON_FLAG_HOSPITAL 0x01
#define BUILDING_ADDON_FLAG_BARRACKS 0x02
#define BUILDING_ADDON_FLAG_WORKSHOP 0x04
#define BUILDING_ADDON_FLAG_SCHOOL 0x08
#define BUILDING_ADDON_FLAG_SMITHS 0x10
#define TILE_TERRAIN_RECORD_STRIDE 14
#define TILE_TERRAIN_ROW_STRIDE 1400
#define TILE_MAP_OFFSET 556374
/* Occupancy layer (base TILE_MAP_OFFSET) stores a castle/building index biased
 * by +0x8000 so an occupied tile is distinguishable from empty; readers
 * subtract the base then index the building table by BUILDING_RECORD_SIZE.
 * Decoded building index is bounds-checked <= 0x64 (BUILDING table count). */
#define TILE_OCCUPANT_BUILDING_INDEX_BASE 0x8000
#define TILE_ROW_STRIDE 200
#define TILE_TRAP_OWNER_MASK_OFFSET 576374
#define TILE_TRAP_OWNER_MASK_ROW_STRIDE 100
#define TURN_OWNER_PLAYER_INDEX_OFFSET 147139
#define VIEWED_PLAYER_INDEX_OFFSET 147143
#define UNIT_STACK_TABLE_OFFSET 147174
#define UNIT_STACK_STRIDE 725
/* 500 stack records live at UNIT_STACK_TABLE_OFFSET (region 147174..509674 =
 * 500*725, docs/SAVE_DAT_FORMAT.md); the stack array is constructed with this
 * count in the bootstrap allocator. */
#define UNIT_STACK_TABLE_COUNT 500
#define UNIT_STACK_SLOT_BASE_OFFSET 6
#define UNIT_STACK_SLOT_STRIDE 31
#define UNIT_STACK_SLOT_COUNT 10
#define UNIT_STACK_PATH_OFFSET 316
#define UNIT_STACK_PATH_BYTES 0x194
#define UNIT_TYPE_METADATA_STRIDE 88
/* 35 real types followed by five zero records before VA 0x00513328. */
#define UNIT_TYPE_METADATA_CAPACITY 40
#define QUEEN_RELATIONSHIP_STATE_CHILDBIRTH_PENDING 9
#define BUILDING_PRISONER_SLOT_BASE_OFFSET 445
#define BUILDING_PRISONER_SLOT_STRIDE 6
#define BUILDING_PRISONER_SLOT_COUNT 3
#define BUILDING_ACTIVE_PRODUCTION_LICENCE_SLOT_INDEX(building) (*((signed char *)(uintptr_t)(building) + 414))
#define BUILDING_PRODUCTION_TURNS_REMAINING(building) (*((unsigned char *)(uintptr_t)(building) + 415))
#define UNIT_SLOT_FLAG_READY 0x01
#define UNIT_SLOT_FLAG_SPENT_TURN 0x02
#define UNIT_SLOT_FLAG_LOW_MORALE 0x04
#define UNIT_SLOT_FLAG_PLAGUE 0x08
/* Exact-spelling recovered constants: literal_rules/F1..F3 record evidence.
 * TABLE_OFFSET constants are absolute displacements, not typed element indices. */
/* BattleUnitEntry.owner_player_index at game-state base 852 + 2 */
#define BATTLE_UNIT_OWNER_PLAYER_INDEX_TABLE_OFFSET 854
/* BattleUnitEntry.facing_direction at game-state base 852 + 3 */
#define BATTLE_UNIT_FACING_DIRECTION_TABLE_OFFSET 855
/* BattleUnitEntry.grid_x at game-state base 852 + 4 */
#define BATTLE_UNIT_GRID_X_TABLE_OFFSET 856
/* BattleUnitEntry.grid_y at game-state base 852 + 6 */
#define BATTLE_UNIT_GRID_Y_TABLE_OFFSET 858
/* BattleUnitEntry.action_points at game-state base 852 + 8 */
#define BATTLE_UNIT_ACTION_POINTS_TABLE_OFFSET 860
/* BattleUnitEntry.health_percent at game-state base 852 + 9 */
#define BATTLE_UNIT_HEALTH_PERCENT_TABLE_OFFSET 861
/* BattleUnitEntry.stance_bits at game-state base 852 + 12 */
#define BATTLE_UNIT_STANCE_BITS_TABLE_OFFSET 864
/* BattleUnitEntry.anim_frame_and_effect_bits at game-state base 852 + 17 */
#define BATTLE_UNIT_ANIM_FRAME_AND_EFFECT_BITS_TABLE_OFFSET 869
/* BattleUnitEntry.battle_state_bits at game-state base 852 + 22 */
#define BATTLE_UNIT_BATTLE_STATE_BITS_TABLE_OFFSET 874
/* PlayerRuntimeState.display_name at game-state base 140024 + 4 */
#define PLAYER_DISPLAY_NAME_TABLE_OFFSET 140028
/* PlayerRuntimeState.camera_left at game-state base 140024 + 15 */
#define PLAYER_CAMERA_LEFT_TABLE_OFFSET 140039
/* PlayerRuntimeState.camera_top at game-state base 140024 + 19 */
#define PLAYER_CAMERA_TOP_TABLE_OFFSET 140043
/* PlayerRuntimeState.controller_mode at game-state base 140024 + 27 */
#define PLAYER_CONTROLLER_MODE_TABLE_OFFSET 140051
/* PlayerRuntimeState.religion_flag at game-state base 140024 + 39 */
#define PLAYER_RELIGION_FLAG_TABLE_OFFSET 140063
/* PlayerRuntimeState.tech_level at game-state base 140024 + 47 */
#define PLAYER_TECH_LEVEL_TABLE_OFFSET 140071
/* PlayerRuntimeState.battle_action_taken_flag at game-state base 140024 + 49 */
#define PLAYER_BATTLE_ACTION_TAKEN_FLAG_TABLE_OFFSET 140073
/* PlayerRuntimeState.consecutive_idle_battle_turns at game-state base 140024 + 53 */
#define PLAYER_CONSECUTIVE_IDLE_BATTLE_TURNS_TABLE_OFFSET 140077
/* PlayerRuntimeState.queen_relationship_state at game-state base 140024 + 1419 */
#define PLAYER_QUEEN_RELATIONSHIP_STATE_TABLE_OFFSET 141443
/* UnitStackRecord.tile_column at game-state base 147174 + 2 */
#define UNIT_STACK_TILE_COLUMN_TABLE_OFFSET 147176
/* UnitStackRecord.owner_player_index at game-state base 147174 + 4 */
#define UNIT_STACK_OWNER_PLAYER_INDEX_TABLE_OFFSET 147178
/* UnitStackRecord.facing_direction at game-state base 147174 + 5 */
#define UNIT_STACK_FACING_DIRECTION_TABLE_OFFSET 147179
/* UnitStackRecord.unit_slots at game-state base 147174 + 6 */
#define UNIT_STACK_UNIT_SLOTS_TABLE_OFFSET 147180
/* UnitSlotRecord.current_health_percent at game-state base 147180 + 9 */
#define UNIT_STACK_SLOT_CURRENT_HEALTH_PERCENT_TABLE_OFFSET 147189
/* UnitSlotRecord.stance_bits at game-state base 147180 + 12 */
#define UNIT_STACK_SLOT_STANCE_BITS_TABLE_OFFSET 147192
/* UnitSlotRecord.aux_runtime_state at game-state base 147180 + 18 */
#define UNIT_STACK_SLOT_AUX_RUNTIME_STATE_TABLE_OFFSET 147198
/* UnitStackRecord.queued_path at game-state base 147174 + 316 */
#define UNIT_STACK_QUEUED_PATH_TABLE_OFFSET 147490
/* UnitStackRecord.is_hidden_on_world_map at game-state base 147174 + 720 */
#define UNIT_STACK_IS_HIDDEN_ON_WORLD_MAP_TABLE_OFFSET 147894
/* BuildingRecord.tile_column at game-state base 509674 + 1 */
#define BUILDING_TILE_COLUMN_TABLE_OFFSET 509675
/* BuildingRecord.owner_player_index at game-state base 509674 + 2 */
#define BUILDING_OWNER_PLAYER_INDEX_TABLE_OFFSET 509676
/* BuildingRecord.footprint_class at game-state base 509674 + 4 */
#define BUILDING_FOOTPRINT_CLASS_TABLE_OFFSET 509678
/* BuildingRecord.construction_turns_remaining at game-state base 509674 + 16 */
#define BUILDING_CONSTRUCTION_TURNS_REMAINING_TABLE_OFFSET 509690
/* BuildingRecord.garrison_slots at game-state base 509674 + 18 */
#define BUILDING_GARRISON_SLOTS_TABLE_OFFSET 509692
/* BuildingRecord.garrison_service_state at game-state base 509674 + 390 */
#define BUILDING_GARRISON_SERVICE_STATE_TABLE_OFFSET 510064
/* BuildingRecord.unit_licence_type_ids at game-state base 509674 + 402 */
#define BUILDING_UNIT_LICENCE_TYPE_IDS_TABLE_OFFSET 510076
/* BuildingRecord.active_production_licence_slot_index at game-state base 509674 + 414 */
#define BUILDING_ACTIVE_PRODUCTION_LICENCE_SLOT_INDEX_TABLE_OFFSET 510088
/* BuildingRecord.castle_addon_flags at game-state base 509674 + 416 */
#define BUILDING_CASTLE_ADDON_FLAGS_TABLE_OFFSET 510090
/* BuildingRecord.wall_strength at game-state base 509674 + 421 */
#define BUILDING_WALL_STRENGTH_TABLE_OFFSET 510095
/* BuildingRecord.peasant_count at game-state base 509674 + 430 */
#define BUILDING_PEASANT_COUNT_TABLE_OFFSET 510104
/* BuildingRecord.satisfaction at game-state base 509674 + 434 */
#define BUILDING_SATISFACTION_TABLE_OFFSET 510108
/* BuildingRecord.plague_state at game-state base 509674 + 435 */
#define BUILDING_PLAGUE_STATE_TABLE_OFFSET 510109
/* BuildingRecord.tax_rate at game-state base 509674 + 436 */
#define BUILDING_TAX_RATE_TABLE_OFFSET 510110
/* BuildingRecord.stored_money at game-state base 509674 + 438 */
#define BUILDING_STORED_MONEY_TABLE_OFFSET 510112
/* BuildingRecord.tech_level_bits at game-state base 509674 + 444 */
#define BUILDING_TECH_LEVEL_BITS_TABLE_OFFSET 510118
/* BuildingRecord.prisoner_slots at game-state base 509674 + 445 */
#define BUILDING_PRISONER_SLOTS_TABLE_OFFSET 510119
/* BuildingRecord.castle_fact_id at game-state base 509674 + 463 */
#define BUILDING_CASTLE_FACT_ID_TABLE_OFFSET 510137

/* Exact-spelling recovered constants: literal_rules/F1..F3 record evidence.
 * TABLE_OFFSET constants are absolute displacements, not typed element indices. */
/* src/recovered_structs.h:135-160 sizeof(UnitSlotRecord)==31; RECOVERED_STRUCTURES.json:1135 BuildingRecord.garrison_slots[12] uses 31-byte UnitSlot records copied by Building_UnitsLeave. */
#define UNIT_SLOT_RECORD_BYTES 31
/* src/recovered_structs.h:171-178 QueuedPathBuffer is 404 bytes; Unit_MoveTrack 00414390 allocates 404 and stores count plus up to 100 four-byte waypoints, later copied as UNIT_STACK_PATH_BYTES. */
#define UNIT_STACK_PATH_ALLOCATION_BYTES 404
/* RECOVERED_STRUCTURES.json:1476 battle_unit_entries[22] starts at 852 and occupancy begins 1534 (difference682); Battle_PlaceUnit 004327B0 and HandleBattleResults traverse offsets 0..682 by31. */
#define BATTLE_UNIT_ENTRIES_BYTES 682
/* RECOVERED_STRUCTURES.json:4518 BuildingRecord[100] and BuildingRecord size467; Building_New scans records by467 until46700 and the table at509674 ends556374. */
#define BUILDING_TABLE_BYTES 46700
/* RECOVERED_STRUCTURES.json:4510 UnitStackRecord[500] and src/recovered_structs.h sizeof725; gameData stack region147174 ends509674 and AI_TickNationPostTurn traverses362500 bytes by725. */
#define UNIT_STACK_TABLE_BYTES 362500
/* RECOVERED_STRUCTURES.json:1135 garrison_slots[12] begins18, next service state begins390 (difference372); Building_New, Building_NewTurn and Building_CalcGarrisonFactStrength traverse12 slots by31. */
#define BUILDING_GARRISON_SLOTS_BYTES 372
/* src/recovered_structs.h:185 embeds10 UnitSlotRecord entries size31; slots start6 and queued_path begins316 (difference310), with AI_TickNationPostTurn traversing j<310 by31. */
#define UNIT_STACK_SLOTS_BYTES 310
/* RECOVERED_STRUCTURES.json:1476 battle_unit_entries[22]; Battle_RestoreSavedActionPointsBeforeResultCopy advances31 bytes and restores22 saved AP entries, matching Battle_PlaceUnit byte bound682. */
#define BATTLE_UNIT_ENTRY_COUNT 22
/* RECOVERED_STRUCTURES.json:1135 garrison_slots[12] stores31-byte entries; Building_Destroy/Building_CountFreeGarrisonSlots bound slot-index traversal at12 with base+18. */
#define BUILDING_GARRISON_SLOT_COUNT 12
/* src/recovered_structs.h UnitTypeMetadataRecord is88 bytes; g_UnitTypeFlags is int/DWORD-addressed at type_flags offset18, and 22*unit_type selects the same 88-byte table entry. Only g_UnitTypeFlags indexing is matched. */
#define UNIT_TYPE_METADATA_DWORD_STRIDE 22
/* Palette_BuildGrayscaleIdentityTable (0x401D10) constructs and iterates 256 four-byte entries; Palette_ExpandRGBTripletsToTable (0x401B20) expands 768 RGB bytes into 1024 table bytes; Palette_ApplyWithBrightnessOffset (0x404C80) independently copies 0x400u bytes and submits 256 entries. Original sub_401AB0 (clash95.asm:1215) advances four-byte entries to base+400h. */
#define PALETTE_COLOR_COUNT 256
/* Palette_BuildGrayscaleIdentityTable (0x401D10) constructs and iterates 256 four-byte entries; Palette_ExpandRGBTripletsToTable (0x401B20) expands 768 RGB bytes into 1024 table bytes; Palette_ApplyWithBrightnessOffset (0x404C80) independently copies 0x400u bytes and submits 256 entries. Original sub_401AB0 (clash95.asm:1215) advances four-byte entries to base+400h. */
#define PALETTE_TABLE_BYTES 1024
/* Palette_BuildGrayscaleIdentityTable (0x401D10) constructs and iterates 256 four-byte entries; Palette_ExpandRGBTripletsToTable (0x401B20) expands 768 RGB bytes into 1024 table bytes; Palette_ApplyWithBrightnessOffset (0x404C80) independently copies 0x400u bytes and submits 256 entries. Original sub_401AB0 (clash95.asm:1215) advances four-byte entries to base+400h. */
#define PALETTE_TABLE_COPY_BYTES 0x400u
/* Palette_BuildGrayscaleIdentityTable (0x401D10) constructs and iterates 256 four-byte entries; Palette_ExpandRGBTripletsToTable (0x401B20) expands 768 RGB bytes into 1024 table bytes; Palette_ApplyWithBrightnessOffset (0x404C80) independently copies 0x400u bytes and submits 256 entries. Original sub_401AB0 (clash95.asm:1215) advances four-byte entries to base+400h. */
#define PALETTE_RGB_DATA_BYTES 768
/* Palette_BuildGrayscaleIdentityTable (0x401D10) constructs and iterates 256 four-byte entries; Palette_ExpandRGBTripletsToTable (0x401B20) expands 768 RGB bytes into 1024 table bytes; Palette_ApplyWithBrightnessOffset (0x404C80) independently copies 0x400u bytes and submits 256 entries. Original sub_401AB0 (clash95.asm:1215) advances four-byte entries to base+400h. */
#define PALETTE_RGB_READ_BYTES 0x300
/* Palette_BuildGrayscaleIdentityTable (0x401D10) constructs and iterates 256 four-byte entries; Palette_ExpandRGBTripletsToTable (0x401B20) expands 768 RGB bytes into 1024 table bytes; Palette_ApplyWithBrightnessOffset (0x404C80) independently copies 0x400u bytes and submits 256 entries. Original sub_401AB0 (clash95.asm:1215) advances four-byte entries to base+400h. */
#define PALETTE_CHANNEL_MAX 255
/* SCREEN_WIDTH=640 and SCREEN_HEIGHT=480 determine the fullscreen buffer; Video_EnterGreyscaleTransition and Video_ExitGreyscaleTransition independently iterate 307200 pixels on those surfaces. */
#define SCREEN_PIXEL_COUNT 307200
/* DLXSpriteSet_Load (0x405AA0) writes DWORD-indexed data pointer[1024], loaded entry count[1025], queried file byte size[1026] and vtable[1027]; Destroy (0x405C60), CopyEntriesFrom (0x405D20) and Save (0x405DB0) independently consume these slots. Save writes a 4096-byte offset directory and starts data there; Load reads/subtracts 4096. GetLastCharIndex (0x405ED0) reads count at byte offset 4100, distinct from DWORD index 1025. */
#define DLX_DIRECTORY_BYTES 4096
/* DLXSpriteSet_Load (0x405AA0) writes DWORD-indexed data pointer[1024], loaded entry count[1025], queried file byte size[1026] and vtable[1027]; Destroy (0x405C60), CopyEntriesFrom (0x405D20) and Save (0x405DB0) independently consume these slots. Save writes a 4096-byte offset directory and starts data there; Load reads/subtracts 4096. GetLastCharIndex (0x405ED0) reads count at byte offset 4100, distinct from DWORD index 1025. */
#define DLX_SPRITE_SET_DATA_POINTER_DWORD_INDEX 1024
/* DLXSpriteSet_Load (0x405AA0) writes DWORD-indexed data pointer[1024], loaded entry count[1025], queried file byte size[1026] and vtable[1027]; Destroy (0x405C60), CopyEntriesFrom (0x405D20) and Save (0x405DB0) independently consume these slots. Save writes a 4096-byte offset directory and starts data there; Load reads/subtracts 4096. GetLastCharIndex (0x405ED0) reads count at byte offset 4100, distinct from DWORD index 1025. */
#define DLX_SPRITE_SET_ENTRY_COUNT_DWORD_INDEX 1025
/* DLXSpriteSet_Load (0x405AA0) writes DWORD-indexed data pointer[1024], loaded entry count[1025], queried file byte size[1026] and vtable[1027]; Destroy (0x405C60), CopyEntriesFrom (0x405D20) and Save (0x405DB0) independently consume these slots. Save writes a 4096-byte offset directory and starts data there; Load reads/subtracts 4096. GetLastCharIndex (0x405ED0) reads count at byte offset 4100, distinct from DWORD index 1025. */
#define DLX_SPRITE_SET_FILE_SIZE_DWORD_INDEX 1026
/* DLXSpriteSet_Load (0x405AA0) writes DWORD-indexed data pointer[1024], loaded entry count[1025], queried file byte size[1026] and vtable[1027]; Destroy (0x405C60), CopyEntriesFrom (0x405D20) and Save (0x405DB0) independently consume these slots. Save writes a 4096-byte offset directory and starts data there; Load reads/subtracts 4096. GetLastCharIndex (0x405ED0) reads count at byte offset 4100, distinct from DWORD index 1025. */
#define DLX_SPRITE_SET_VTABLE_DWORD_INDEX 1027
/* DLXSpriteSet_Load (0x405AA0) writes DWORD-indexed data pointer[1024], loaded entry count[1025], queried file byte size[1026] and vtable[1027]; Destroy (0x405C60), CopyEntriesFrom (0x405D20) and Save (0x405DB0) independently consume these slots. Save writes a 4096-byte offset directory and starts data there; Load reads/subtracts 4096. GetLastCharIndex (0x405ED0) reads count at byte offset 4100, distinct from DWORD index 1025. */
#define DLX_SPRITE_SET_ENTRY_COUNT_BYTE_OFFSET 4100
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_SYMBOL_BUCKET_COUNT 1013
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_SYMBOL_TABLE_BYTES 4052
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_SYMBOL_ALLOCATION_BYTES 0xFD4u
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_SYMBOL_HASH_RANGE 0x3F5u
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_FLOAT_BUCKET_COUNT 503
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_FLOAT_TABLE_BYTES 2012
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_FLOAT_ALLOCATION_BYTES 0x7DCu
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_FLOAT_HASH_RANGE 0x1F7u
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_INTEGER_BUCKET_COUNT 167
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_INTEGER_TABLE_BYTES 668
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_INTEGER_ALLOCATION_BYTES 0x29Cu
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_BITMAP_BUCKET_COUNT 167
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_BITMAP_TABLE_BYTES 668
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_BITMAP_ALLOCATION_BYTES 0x29Cu
/* Rules_InitAtomTables (0x482260; clash95.asm:206479-206528) allocates and clears symbol/float/integer/bitmap tables of 4052/2012/668/668 bytes in four-byte steps. Rules_RestoreAtomicValueBuckets (0x482EF0) and Rules_ClearAtomInUseMarks (0x4949E0) independently traverse 1013/503/167/167 typed buckets. Str_Intern, Rules_AddDoubleValue, Rules_AddIntegerValue and Rules_AddBitmapValue use corresponding hash ranges. Integer and bitmap are separate domains despite equal counts. */
#define CLIPS_BITMAP_HASH_RANGE 0xA7u
/* Compat_FileStreamRelease (0x477D60) tests bit4 before _wcpp_4_dtor_array_store__ plus j_j__nfree_, and bit2 before j__nfree_; DLXSpriteSet_Destroy (0x405C60) independently uses the same paths. Every included function was checked for this array-helper/release family. These mechanical destructor bits are not ordinary file mode flags. */
#define CRT_DTOR_FLAG_ARRAY_STORAGE 4
/* Compat_FileStreamRelease (0x477D60) tests bit4 before _wcpp_4_dtor_array_store__ plus j_j__nfree_, and bit2 before j__nfree_; DLXSpriteSet_Destroy (0x405C60) independently uses the same paths. Every included function was checked for this array-helper/release family. These mechanical destructor bits are not ordinary file mode flags. */
#define CRT_DTOR_FLAG_RELEASE_STORAGE 2
/* CSS stream buffer length multiplies g_CSS_StreamBufferMs by bytes/second formatInfo[2] and divides1000 (media/0046E870...:190). Independently, two stream-service loops convert g_CSS_StreamServiceRateHz to Sleep milliseconds using1000/rate (media/0046B610...:1356,1438). Exact decimal int token retained. */
#define CSS_MILLISECONDS_PER_SECOND 1000

/* Exact-spelling recovered constants: literal_rules/F1..F3 record evidence.
 * TABLE_OFFSET constants are absolute displacements, not typed element indices. */
/* clash95.asm loc_424B38: inc edx adds one to tile movement cost before sub_410010 minimum-AP comparison; loc_424E62: mov edx,1 followed by sub_410130 spends construction AP after sub_410330 queued movement. UnitStack_SpendActionPointsClamped (0x410130) subtracts spendAmount from occupied UnitSlot AP bytes. Highlight loc_425445 independently increments movement cost before the same minimum-AP comparison. */
#define ROAD_BUILD_CONSTRUCTION_ACTION_POINTS 1
/* clash95.asm loc_4251B2 calls sub_424020/sub_424120 bridge-overlay predicates; loc_425201 calls sub_410010 then cmp eax,6 and jge loc_425425 to mark and refresh an available Road target. Recovered MapTile_HasAlignedBridgeApproachRoadOverlay/MapTile_IsBareBridgeCrossingRoadOverlayCandidate and UnitStack_GetMinCurrentActionPoints corroborate bridge-highlight-specific AP threshold; this is not asserted to be the total construction cost. */
#define ROAD_BUILD_BRIDGE_HIGHLIGHT_MIN_ACTION_POINTS 6
/* clash95.asm loc_4255D3 increments dword_527C38 then and ebx,7 and stores the frame index. sub_425120 consumes that index to address dword_514294 bounce offsets for four direction marker positions. Original table at00514294 and fixture original-road.bin offset0x88 contain first-eight offsets -8,-4,0,4,8,4,0,-4; mask names eight-frame wrap, not the nine-DWORD backing region capacity. */
#define ROAD_BUILD_MARKER_ANIMATION_FRAME_MASK 7
/* clash95.asm loc_4255D3 calls Time_Now then sub eax,0Ah and unsigned cmp/jbe against dword_527C28; eligible branch saves a fresh Time_Now value, advances the masked marker frame, and redraws four adjacent tiles. Builder_StartRoadBuildMode reproduces this exact subtraction/comparison and RoadBuildMode_HighlightBuildableAdjacentTile consumes the resulting bounce index; ticks deliberately avoids imposing an unverified wall-clock unit or changing strict comparison behavior. */
#define ROAD_BUILD_MARKER_ANIMATION_INTERVAL_TICKS 10

/* Religious-site category returned by MapTile_GetReligiousSiteCategory
 * (080_building_ui.inc.c:8256): the overlay id at terrain record +2 maps to one
 * of these; 0 = not a religious site. */
typedef enum ReligiousSiteCategory
{
  RELIGIOUS_SITE_CATEGORY_NONE = 0,
  RELIGIOUS_SITE_CATEGORY_SHRINE = 1,
  RELIGIOUS_SITE_CATEGORY_EMPTY_SHRINE = 2,
  RELIGIOUS_SITE_CATEGORY_CULT_PLACE = 3,
  RELIGIOUS_SITE_CATEGORY_EMPTY_CULT_PLACE = 4
} ReligiousSiteCategory;

/* Temple/shrine gift outcome dispatched by Temple_ProcessGift
 * (080_building_ui.inc.c:8601). Members named by observable mechanical effect
 * (the handler each case runs); designer labels are not recovered. */
typedef enum TempleGiftType
{
  TEMPLE_GIFT_SPAWN_UNITS = 0,
  TEMPLE_GIFT_KILL_STACK = 1,
  TEMPLE_GIFT_REST = 2,                    /* fatigue -100 */
  TEMPLE_GIFT_BLESS_MORALE = 3,            /* morale +20 */
  TEMPLE_GIFT_HEAL_FULL = 4,               /* slot HP := 100 */
  TEMPLE_GIFT_HEAL_FULL_RESET = 5,         /* HP := 100 + clears next field */
  TEMPLE_GIFT_CYCLE_ORDERS_3 = 6,
  TEMPLE_GIFT_BLESS_MORALE_MINOR = 7,      /* morale +2 */
  TEMPLE_GIFT_CYCLE_ORDERS_2 = 8,
  TEMPLE_GIFT_GOLD_100 = 9,
  TEMPLE_GIFT_GOLD_200 = 0xA,
  TEMPLE_GIFT_GOLD_50 = 0xB,
  TEMPLE_GIFT_GOLD_300 = 0xC,
  TEMPLE_GIFT_CURSE_MORALE = 0xD,          /* morale -20 */
  TEMPLE_GIFT_CURSE_MORALE_FATIGUE = 0xE   /* morale -1, fatigue +50 */
} TempleGiftType;

/* Settlement tax-burden tier (0..3) from Building_GetTaxBurdenTier
 * (080_building_ui.inc.c:7664) = count of exceeded tax thresholds, so the tier
 * rises monotonically with tax burden; drives population-growth adjustment.
 * Magnitude labels inferred from that monotonic effect. */
typedef enum TaxBurdenTier
{
  TAX_BURDEN_TIER_LOW = 0,        /* growth +5 */
  TAX_BURDEN_TIER_MODERATE = 1,   /* no adjustment */
  TAX_BURDEN_TIER_HIGH = 2,       /* growth -4 */
  TAX_BURDEN_TIER_SEVERE = 3      /* growth -Rng(10,15) */
} TaxBurdenTier;

/* World-map visual theme selector (MAP_THEME_INDEX, 3-way). Selects
 * backgrN.s32 / treemasN.s32 (040_world_map.inc.c:2871). The concrete theme
 * identity per index is unproven, so labels stay generic A/B/C. */
typedef enum MapTheme
{
  MAP_THEME_A = 0,
  MAP_THEME_B = 1,
  MAP_THEME_C = 2
} MapTheme;

/* AI difficulty/intelligence tier written to PlayerRuntimeState +31
 * (PLAYER_AI_INTELLIGENCE). Proven value tier 0..2; difficulty labels inferred
 * from the monotonic tier. */
typedef enum PlayerAiIntelligence
{
  PLAYER_AI_INTELLIGENCE_EASY = 0,
  PLAYER_AI_INTELLIGENCE_NORMAL = 1,
  PLAYER_AI_INTELLIGENCE_HARD = 2
} PlayerAiIntelligence;

/* Multiplayer player-slot selector (g_MultiplayerPlayerSlotTypes[], mod-6 UI
 * cycle) dispatched in PlayGame_Dispatch (090_special_sites_savegame.inc.c:4545):
 * 0..2 seed an AI player at intelligence 0..2, 3/4 a human with religion on/off,
 * 5 a closed slot. AI difficulty labels inferred from the intelligence tier. */
typedef enum MultiplayerPlayerSlotType
{
  MP_PLAYER_SLOT_AI_EASY = 0,
  MP_PLAYER_SLOT_AI_NORMAL = 1,
  MP_PLAYER_SLOT_AI_HARD = 2,
  MP_PLAYER_SLOT_HUMAN_RELIGIOUS = 3,
  MP_PLAYER_SLOT_HUMAN_SECULAR = 4,
  MP_PLAYER_SLOT_CLOSED = 5
} MultiplayerPlayerSlotType;

/* Battle-AI per-unit turn plan, produced by UnitBattle_SelectAiPlanMode
 * (080_building_ui.inc.c:5627) into g_UnitBattleAiCurrentPlanMode and dispatched
 * by UnitBattle_ScoreAiActionGridForUnit. Values 3 and 5 are never produced. */
typedef enum UnitBattleAiPlanMode
{
  BATTLE_AI_PLAN_HOLD = 0,           /* defender, early turn */
  BATTLE_AI_PLAN_ADVANCE = 1,        /* default melee approach */
  BATTLE_AI_PLAN_RANGED_ENGAGE = 2,  /* ranged line hit within turn 3 */
  BATTLE_AI_PLAN_DISENGAGE = 4,      /* no wall objective */
  BATTLE_AI_PLAN_INITIAL_SWEEP = 6   /* first turn, matching side */
} UnitBattleAiPlanMode;

/* Battle-AI per-cell action code from g_BattleCellStateGrid, dispatched by
 * UnitBattle_ExecuteAiActionForUnit (080_building_ui.inc.c:4987). Only these
 * five action codes are handled; other cell values are non-action (scores). */
typedef enum BattleAiCellAction
{
  BATTLE_AI_CELL_MELEE = 1,          /* MoveTrackNear + melee exchange/attack */
  BATTLE_AI_CELL_NOOP = 5,           /* no action */
  BATTLE_AI_CELL_FORCE_MOVE = 6,     /* MoveTrackForce toward target */
  BATTLE_AI_CELL_KITE = 7,           /* ApproachToSafeDistance */
  BATTLE_AI_CELL_SHOOT = 8           /* MoveShootingUnit (ranged) */
} BattleAiCellAction;

/* CLIPS conflict-resolution strategy (g_Rules_ConflictResolutionStrategy). The
 * seven canonical CLIPS strategies; each value is dispatched to its self-named
 * handler in Rules_InsertActivationSorted (render/120_media.inc.c:18692) and to
 * its name string in Rules_GetStrategyName (:19267). */
typedef enum ClipsConflictResolutionStrategy
{
  CLIPS_STRATEGY_DEPTH = 0,
  CLIPS_STRATEGY_BREADTH = 1,
  CLIPS_STRATEGY_LEX = 2,
  CLIPS_STRATEGY_MEA = 3,
  CLIPS_STRATEGY_COMPLEXITY = 4,
  CLIPS_STRATEGY_SIMPLICITY = 5,
  CLIPS_STRATEGY_RANDOM = 6
} ClipsConflictResolutionStrategy;

/* CLIPS 6.0 primitive value-type codes (the `type` tag on a value/field). Value
 * mapping confirmed by the field-hash switches Rules_ComputeFieldHashValue
 * (130_clips_language_part2.inc.c:11959) and Rules_HashFactFieldList (:7061):
 * 0/1 hash a numeric payload at +16, 2/3/8 intern as symbol names, 4 recurses
 * as a multifield, 5/6/7 hash a raw pointer; corroborated by CLIPS 6.30 source
 * (docs/archive/CLIPS_SOURCE_CROSSREF.md). */
typedef enum ClipsType
{
  CLIPS_TYPE_FLOAT = 0,
  CLIPS_TYPE_INTEGER = 1,
  CLIPS_TYPE_SYMBOL = 2,
  CLIPS_TYPE_STRING = 3,
  CLIPS_TYPE_MULTIFIELD = 4,
  CLIPS_TYPE_EXTERNAL_ADDRESS = 5,
  CLIPS_TYPE_FACT_ADDRESS = 6,
  CLIPS_TYPE_INSTANCE_ADDRESS = 7,
  CLIPS_TYPE_INSTANCE_NAME = 8
} ClipsType;
/* Religious-site overlay tile ids (terrain record +2). MapTile_GetReligiousSite
 * Category (080_building_ui.inc.c:8256) maps each to its RELIGIOUS_SITE_CATEGORY
 * result; the A/B/C suffix is the three interchangeable visual variants per
 * category (variant axis unproven). */
#define TILE_OVERLAY_SHRINE_A 0x2D8
#define TILE_OVERLAY_SHRINE_B 0x2DA
#define TILE_OVERLAY_SHRINE_C 0x2DC
#define TILE_OVERLAY_EMPTY_SHRINE_A 0x2D9
#define TILE_OVERLAY_EMPTY_SHRINE_B 0x2DB
#define TILE_OVERLAY_EMPTY_SHRINE_C 0x2DD
#define TILE_OVERLAY_CULT_PLACE_A 0x2DE
#define TILE_OVERLAY_CULT_PLACE_B 0x2E0
#define TILE_OVERLAY_CULT_PLACE_C 0x2E2
#define TILE_OVERLAY_EMPTY_CULT_PLACE_A 0x2DF
#define TILE_OVERLAY_EMPTY_CULT_PLACE_B 0x2E1
#define TILE_OVERLAY_EMPTY_CULT_PLACE_C 0x2E3
/* Fixed 640x480 display surface. SCREEN_WIDTH/HEIGHT from CreateWindowExA
 * (110_platform_input.inc.c:286) and g_Device_DefaultWindowRect {0,0,640,480};
 * SCREEN_MAX_X/Y are the inclusive right/bottom edges (width-1/height-1) passed
 * to Render_FillRect/blit as x1,y1 (e.g. 040_world_map.inc.c:1949). */
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define SCREEN_MAX_X 0x27F
#define SCREEN_MAX_Y 0x1DF
#define g_PortReinforcementSpawnRingOffsets ((PortSpawnOffset *)g_PortSpawnRingOffsetsTable)
#define g_QueenBirthMessageBuffer g_QueenDepartureEventMessageBuffer
/* Main-menu slider values are fields of the original 36-byte records at
 * VA 0x00518600, not separate globals. Keep aliases outside generated headers. */
#define g_Options_BrightnessSliderValue (*(int *)(void *)&g_OptionsMenuSliderThumbPositions[12])
#define g_Options_ScrollSpeedSliderValue (*(int *)(void *)&g_OptionsMenuSliderThumbPositions[48])
#define g_Options_MouseSpeedSliderValue (*(int *)(void *)&g_OptionsMenuSliderThumbPositions[84])
#define g_UnitBattleChargeModeActive_532060 g_UnitBattleChargeModeActive
#define g_UnitBattleChargeModeStartTick_532074 g_UnitBattleChargeModeStartTick

#define PLAYER_RUNTIME_STATE(playerIndex) (gameData + PLAYER_RUNTIME_STATE_OFFSET + PLAYER_DATA_STRIDE * (playerIndex))
#define PLAYER_DATA(playerIndex) PLAYER_RUNTIME_STATE(playerIndex)
#define PLAYER_IS_ACTIVE(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex)))
#define PLAYER_RELIGION_FLAG(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_RELIGION_FLAG_OFFSET))
#define PLAYER_QUEEN_RELATIONSHIP_STATE(playerIndex) (*(_BYTE *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_QUEEN_RELATIONSHIP_STATE_OFFSET))
#define PLAYER_QUEEN_PORTRAIT_INDEX(playerIndex) (*(_BYTE *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_QUEEN_PORTRAIT_INDEX_OFFSET))
#define PLAYER_QUEEN_NEXT_RELATIONSHIP_CHECK_TURN(playerIndex) (*(_WORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_QUEEN_NEXT_RELATIONSHIP_CHECK_TURN_OFFSET))
#define PLAYER_CAMERA_LEFT(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_CAMERA_LEFT_OFFSET))
#define PLAYER_CAMERA_TOP(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_CAMERA_TOP_OFFSET))
#define PLAYER_MINIMAP_VISIBLE(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_MINIMAP_VISIBLE_OFFSET))
#define PLAYER_HAS_HUMAN_CONTROLLER(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_IS_HUMAN_OFFSET))
#define PLAYER_AI_INTELLIGENCE(playerIndex) (*(_DWORD *)(uintptr_t)(PLAYER_DATA(playerIndex) + PLAYER_AI_INTELLIGENCE_OFFSET))
#define MAP_THEME_INDEX (*((unsigned __int8 *)(uintptr_t)(gameData + MAP_THEME_INDEX_OFFSET)))
#define MAP_WIDTH_TILES (*(_DWORD *)(uintptr_t)(gameData + MAP_WIDTH_TILES_OFFSET))
#define MAP_HEIGHT_TILES (*(_DWORD *)(uintptr_t)(gameData + MAP_HEIGHT_TILES_OFFSET))
#define MAP_VIEW_LEFT (*(_DWORD *)(uintptr_t)(gameData + MAP_VIEW_LEFT_OFFSET))
#define MAP_VIEW_TOP (*(_DWORD *)(uintptr_t)(gameData + MAP_VIEW_TOP_OFFSET))
#define ACTIVE_MISSION_INDEX (*(_DWORD *)(uintptr_t)(gameData + ACTIVE_MISSION_INDEX_OFFSET))
#define MISSION_FAILURE_FLAG (*((unsigned __int8 *)(uintptr_t)(gameData + MISSION_FAILURE_FLAG_OFFSET)))
#define GAME_TURN_COUNTER (*(_WORD *)(uintptr_t)(gameData + GAME_TURN_COUNTER_OFFSET))
#define TURN_OWNER_PLAYER_INDEX (*(_DWORD *)(uintptr_t)(gameData + TURN_OWNER_PLAYER_INDEX_OFFSET))
#define VIEWED_PLAYER_INDEX (*(_DWORD *)(uintptr_t)(gameData + VIEWED_PLAYER_INDEX_OFFSET))
#define PORT_ROW (*(_DWORD *)(uintptr_t)(gameData + PORT_ROW_OFFSET))
#define PORT_COLUMN (*(_DWORD *)(uintptr_t)(gameData + PORT_COLUMN_OFFSET))
#define PORT_NEXT_REINFORCEMENT_TURN (*(_DWORD *)(uintptr_t)(gameData + PORT_NEXT_REINFORCEMENT_TURN_OFFSET))
#define PORT_REINFORCEMENT_READY_FLAG (*(_DWORD *)(uintptr_t)(gameData + PORT_REINFORCEMENT_READY_FLAG_OFFSET))
#define PORT_REINFORCEMENT_UNIT_COUNT (*(_DWORD *)(uintptr_t)(gameData + PORT_REINFORCEMENT_UNIT_COUNT_OFFSET))
#define PORT_SHORE_VARIANT_FLAG (*(_DWORD *)(uintptr_t)(gameData + PORT_SHORE_VARIANT_FLAG_OFFSET))
#define BUILDING_RECORD(index) (gameData + BUILDING_TABLE_OFFSET + BUILDING_RECORD_SIZE * (index))
#define BUILDING_GARRISON_SERVICE_STATE(buildingPtr, slotIndex) (*(_BYTE *)(uintptr_t)((buildingPtr) + BUILDING_GARRISON_SERVICE_STATE_OFFSET + (slotIndex)))
#define UNIT_RECORD_SIZE BUILDING_RECORD_SIZE
#define UNIT_TABLE_OFFSET BUILDING_TABLE_OFFSET
#define UNIT_RECORD(index) BUILDING_RECORD(index)
#define TILE_TERRAIN_RECORD(row, column) ((unsigned __int16 *)(gameData + TILE_TERRAIN_ROW_STRIDE * (row) + TILE_TERRAIN_RECORD_STRIDE * (column)))
#define TILE_INDEX(row, column) (gameData + TILE_MAP_OFFSET + TILE_ROW_STRIDE * (row) + 2 * (column))
#define TILE_TRAP_OWNER_MASK(row, column) (*(_BYTE *)(uintptr_t)(gameData + TILE_TRAP_OWNER_MASK_OFFSET + TILE_TRAP_OWNER_MASK_ROW_STRIDE * (row) + (column)))
#define UNIT_STACK(index) (gameData + UNIT_STACK_TABLE_OFFSET + UNIT_STACK_STRIDE * (index))
#define UNIT_STACK_RECORD(index) ((UnitStackRecord *)(uintptr_t)UNIT_STACK(index))
#define UNIT_STACK_SLOT(stackPtr, slotIndex) ((stackPtr) + UNIT_STACK_SLOT_BASE_OFFSET + UNIT_STACK_SLOT_STRIDE * (slotIndex))
#define UNIT_STACK_TILE_ROW(stackPtr) (*(__int16 *)(stackPtr))
#define UNIT_STACK_TILE_COLUMN(stackPtr) (*(__int16 *)((stackPtr) + 2))
#define UNIT_STACK_OWNER_INDEX(stackPtr) (*(_BYTE *)(uintptr_t)((stackPtr) + 4))
#define UNIT_STACK_FACING(stackPtr) (*(_BYTE *)(uintptr_t)((stackPtr) + 5))
/* 8-way facing/movement direction (row=Y down, column=X right). Fully specified
 * by Facing_DirectionFromDelta8 (050_units.inc.c:290). Index order is
 * West=0, SW, S, SE, E, NE, N, NW=7 (a counterclockwise sweep on a Y-down
 * screen). Stored at unit-stack +5 (UNIT_STACK_FACING) and battle-unit +3. */
typedef enum Direction8
{
  DIRECTION8_WEST = 0,
  DIRECTION8_SOUTHWEST = 1,
  DIRECTION8_SOUTH = 2,
  DIRECTION8_SOUTHEAST = 3,
  DIRECTION8_EAST = 4,
  DIRECTION8_NORTHEAST = 5,
  DIRECTION8_NORTH = 6,
  DIRECTION8_NORTHWEST = 7
} Direction8;
#define DIRECTION8_COUNT 8
#define UNIT_STACK_PATH_BUFFER(stackPtr) ((stackPtr) + UNIT_STACK_PATH_OFFSET)
#define UNIT_SLOT_TYPE(slotPtr) (*(__int16 *)(slotPtr))
#define UNIT_SLOT_OWNER(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 2))
#define UNIT_SLOT_ACTION_POINTS(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 8))
#define UNIT_SLOT_HEALTH_PERCENT(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 9))
#define UNIT_SLOT_FATIGUE(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 10))
#define UNIT_SLOT_MORALE(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 11))
#define UNIT_SLOT_STANCE_BITS(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 12))
#define UNIT_SLOT_FLAGS(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 13))
#define UNIT_SLOT_STATUS_LEVEL(slotPtr) (UNIT_SLOT_STANCE_BITS(slotPtr) & 0x03)
#define UNIT_SLOT_ORDER_STATE(slotPtr) ((UNIT_SLOT_STANCE_BITS(slotPtr) >> 2) & 0x03)
#define UNIT_SLOT_VOLLEYS_USED(slotPtr) ((UNIT_SLOT_STANCE_BITS(slotPtr) >> 4) & 0x07)
#define UNIT_SLOT_REMAINING_VOLLEYS(slotPtr) ((UNIT_SLOT_STATUS_LEVEL(slotPtr) + 1) - UNIT_SLOT_VOLLEYS_USED(slotPtr))
#define UNIT_SLOT_SET_VOLLEYS_USED(slotPtr, volleysUsed) \
  (UNIT_SLOT_STANCE_BITS(slotPtr) = (UNIT_SLOT_STANCE_BITS(slotPtr) & 0x8F) | (((volleysUsed) & 0x07) << 4))
#define UNIT_SLOT_AUX_STATE(slotPtr) (*(_DWORD *)(uintptr_t)((slotPtr) + 18))
#define UNIT_SLOT_STATE_BITS(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 22))

/* BattleUnitEntry (RECOVERED_STRUCTURES.json): the 31-byte tactical-battle unit
 * slot in BattleRuntimeState.battle_unit_entries[22], based at g_MapData + 852
 * with stride 31. Mirrors the world UNIT_SLOT core (type/owner/AP/health/stance/
 * state at the same offsets) and adds battle-only facing/grid/animation fields.
 * entryPtr = g_MapData + BATTLE_UNIT_ENTRIES_OFFSET + BATTLE_UNIT_ENTRY_STRIDE*i.
 * Field casts match the decompiler's actual site casts (grid_x/y are _WORD). */
#define BATTLE_UNIT_ENTRIES_OFFSET 852
#define BATTLE_UNIT_ENTRY_STRIDE 31
#define BATTLE_UNIT_ENTRY(mapDataBase, entryIndex) \
  ((mapDataBase) + BATTLE_UNIT_ENTRIES_OFFSET + BATTLE_UNIT_ENTRY_STRIDE * (entryIndex))
#define BATTLE_UNIT_TYPE(entryPtr) (*(__int16 *)(entryPtr))
#define BATTLE_UNIT_OWNER(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 2))
#define BATTLE_UNIT_FACING(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 3))
#define BATTLE_UNIT_GRID_X(entryPtr) (*(_WORD *)(uintptr_t)((entryPtr) + 4))
#define BATTLE_UNIT_GRID_Y(entryPtr) (*(_WORD *)(uintptr_t)((entryPtr) + 6))
#define BATTLE_UNIT_ACTION_POINTS(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 8))
#define BATTLE_UNIT_HEALTH_PERCENT(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 9))
#define BATTLE_UNIT_STANCE_BITS(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 12))
#define BATTLE_UNIT_ANIM_BITS(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 17))
#define BATTLE_UNIT_LAST_ANIM_TICK(entryPtr) (*(_DWORD *)(uintptr_t)((entryPtr) + 18))
#define BATTLE_UNIT_STATE_BITS(entryPtr) (*(_BYTE *)(uintptr_t)((entryPtr) + 22))
#define BUILDING_PRISONER_SLOT(buildingPtr, slotIndex) \
  ((buildingPtr) + BUILDING_PRISONER_SLOT_BASE_OFFSET + BUILDING_PRISONER_SLOT_STRIDE * (slotIndex))
#define BUILDING_PRISONER_TYPE(slotPtr) (*(char *)(uintptr_t)(slotPtr))
#define BUILDING_PRISONER_OWNER(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 1))
#define BUILDING_PRISONER_ACTION(slotPtr) (*(_BYTE *)(uintptr_t)((slotPtr) + 3))
#define BUILDING_PRISONER_RANSOM(slotPtr) (*(_WORD *)(uintptr_t)((slotPtr) + 4))

/* C uses an unsigned 32-bit compatible type for this enum. Pin it in C++ too:
 * the recovered calls also carry -1/0xFFFFFFFF sentinels through this type. */
#ifdef __cplusplus
typedef enum unit_type : unsigned int
#else
typedef enum unit_type
#endif
{
  UNIT_TYPE_PEASANT = 0,
  UNIT_TYPE_LIGHT_INFANTRY = 1,
  UNIT_TYPE_HEAVY_INFANTRY = 2,
  UNIT_TYPE_PIKEMAN = 3,
  UNIT_TYPE_HEAVY_SPEARMAN = 4,
  UNIT_TYPE_LIGHT_CAVALRY = 5,
  UNIT_TYPE_HEAVY_CAVALRY = 6,
  UNIT_TYPE_KNIGHTS = 7,
  UNIT_TYPE_DRAGON_CAVALRY = 8,
  UNIT_TYPE_ARCHER = 9,
  UNIT_TYPE_CROSSBOWER = 10,
  UNIT_TYPE_MUSKETEER = 11,
  UNIT_TYPE_CATAPULT = 12,
  UNIT_TYPE_RAM = 13,
  UNIT_TYPE_CANNON = 14,
  UNIT_TYPE_FORESTER = 15,
  UNIT_TYPE_GORAL = 16,
  UNIT_TYPE_BUILDER = 17,
  UNIT_TYPE_WORM = 18,
  UNIT_TYPE_ELEPHANT = 19,
  UNIT_TYPE_CYCLOP = 20,
  UNIT_TYPE_TROLL = 21,
  UNIT_TYPE_SCORPION = 22,
  UNIT_TYPE_SKELETON = 23,
  UNIT_TYPE_WIZARD = 24,
  UNIT_TYPE_GHOST = 25,
  UNIT_TYPE_EAGLE = 26,
  UNIT_TYPE_PEGASUS = 27,
  UNIT_TYPE_WINGER = 28,
  UNIT_TYPE_FLY = 29,
  UNIT_TYPE_DRAGON = 30,
  UNIT_TYPE_GOLD_CARGO = 31,
  UNIT_TYPE_PEASANT_CARGO = 32,
  UNIT_TYPE_SPECIAL_FOOT_PERSONAGE = 33,
  UNIT_TYPE_SPECIAL_MOUNTED_PERSONAGE = 34
} unit_type;

#define UNIT_TYPE_COUNT 35

enum BuildingPrisonerAction
{
  BUILDING_PRISONER_ACTION_NONE = 0,
  BUILDING_PRISONER_ACTION_BEHEAD = 1,
  BUILDING_PRISONER_ACTION_TORTURE = 2,
  BUILDING_PRISONER_ACTION_PAY = 3
};

typedef struct QueenWhimRecord
{
  unsigned __int16 required_stronghold_funds;
  char *texts[3];
} QueenWhimRecord;

typedef struct PortSpawnOffset
{
  int row_delta;
  int column_delta;
} PortSpawnOffset;

typedef struct InputBackendState
{
  _DWORD direct_input;
  _DWORD keyboard_device;
  _DWORD mouse_device;
  _DWORD joystick_device;
  int mouse_delta_x;
  int mouse_delta_y;
  int joystick_axis_x;
  int joystick_axis_y;
  int joystick_button_primary;
  int joystick_button_secondary;
  int mouse_button_primary;
  int mouse_button_middle;
  int mouse_button_secondary;
  char keyboard_state[256];
  int mouse_device_ready;
  int keyboard_device_ready;
  int joystick_device_ready;
} InputBackendState;

typedef struct TileHighlightSlot
{
  int tile_x;
  int tile_y;
} TileHighlightSlot;

#define g_QueenWhimRecords ((QueenWhimRecord *)&g_QueenWhimRecords_5191F0)
#define g_InputMouseDeltaX (g_InputBackendState.mouse_delta_x)
#define g_InputMouseDeltaY (g_InputBackendState.mouse_delta_y)
#define g_InputMousePrimaryButtonState (*((signed char *)&g_InputBackendState.mouse_button_primary))
#define g_InputMouseSecondaryButtonState (*((signed char *)&g_InputBackendState.mouse_button_secondary))
#define g_Input_KeyStateArray ((signed char *)&g_InputBackendState.keyboard_state[0])

// Compatibility aliases while stat-callsite cleanup is still in progress.
#define Unit_CalcEffectivenessA UnitStats_CalcEffectiveMeleeAttack
#define UI_IconIndexFromStats UnitStats_GetMeleeIconIndex
#define Unit_CalcEffectivenessB UnitStats_CalcEffectiveDefensePower
#define Unit_CalcIndexB UnitStats_GetDefenseIconIndex
#define Unit_CalcEffectivenessC UnitStats_CalcEffectiveShotPower
#define Unit_GetBaseC UnitStats_GetBaseShotPower
#define Unit_CalcEffectivenessD UnitStats_CalcEffectiveWallAttack
#define g_UnitTypeBaseMeleeAttack_51257E g_UnitTypeBaseMeleeAttack
#define g_UnitTypeBaseDefensePower_51257F g_UnitTypeBaseDefensePower
#define g_UnitTypeBaseActionPoints_512580 g_UnitTypeBaseActionPoints
#define g_UnitTypeBaseShotPower_512581 g_UnitTypeBaseShotPower
#define g_UnitTypeMaxRange_512582 g_UnitTypeMaxRange
#define g_UnitTypeMinRange_512583 g_UnitTypeMinRange
#define g_UnitTypeBaseWallAttack_512584 g_UnitTypeBaseWallAttack
typedef struct RenderSurfaceStorage {
  unsigned char bytes[0xC0];
} RenderSurfaceStorage;

typedef struct RenderPrimarySurfaceStorage {
  unsigned char bytes[0x4E0];
} RenderPrimarySurfaceStorage;

typedef struct EvalNodeDescriptor {
  unsigned char type;
  unsigned char flags;
  unsigned char reserved0[14];
  void *evaluate;
  unsigned char reserved1[24];
} EvalNodeDescriptor;

typedef _DWORD EvalNodeDescriptorCompact[12];

typedef struct EvalResultBuffer {
  int reserved;
  int type;
  int value;
  int begin;
  int end;
} EvalResultBuffer;

typedef struct EvalMultifieldEntry {
  int reserved0;
  int type;
  int value;
  int begin;
  int end;
  int reserved1;
} EvalMultifieldEntry;
typedef struct __attribute__((packed)) RenderSpriteRemapEntry {
  unsigned short sprite_id;
  unsigned char timing;
} RenderSpriteRemapEntry;
#define g_TerrainAnimFrameDurationTable (((unsigned char *)g_TerrainAnimationRemapTable) + 2)
#define TERRAIN_ANIMATION_REMAP_COUNT ((int)(sizeof(g_TerrainAnimationRemapTable) / sizeof(g_TerrainAnimationRemapTable[0])))
#define g_ColorCyclePrimaryFrameIndex (g_Render_AnimatedFrameTable[595])
#define g_ColorCycleStateArrayBase (&g_Render_AnimatedFrameTable[7])
#define g_Font_GlyphRemapTable (&g_Render_AnimatedFrameTable[8])
#define g_Render_SpriteAnimDelayBytes (((unsigned char *)g_SpriteCodeRemapTable) + 2)
#define g_ClipsBreakFlag HIDWORD(g_ClipsHaltExecutionFlag)

enum
{
  MAIN_MENU_REQUEST_EXIT = 0,
  MAIN_MENU_REQUEST_CAMPAIGN = 1,
  MAIN_MENU_REQUEST_CREDITS = 2,
  MAIN_MENU_REQUEST_MULTIPLAYER = 3,
  MAIN_MENU_REQUEST_OPTIONS = 4,
  MAIN_MENU_REQUEST_LOAD_GAME = 5
};
#define WORLD_MAP_ACTION_WIDGET_RECORD_SIZE 53
#define WORLD_MAP_ACTION_WIDGET_COUNT 6

/* Original builder records: [0x511BC0,0x511D02), six 53-byte records + sentinel.
 * Road data: [0x51420C,0x5144CE), including the original overlapping scan. */
#define BUILDER_ACTION_WIDGET_TABLE_BYTES 322

/* BuildBuilding aliases point inside its own original packed table. */
#define BUILD_CURSOR_WIDGET_TABLE_BYTES 322
#define g_BuildBuildingActionWidgetStateBase (*(int *)(g_BuildBuildingActionWidgetTable + 8))
#define g_BuildBuildingActionWidgetHandlerBase (*(_DWORD *)(g_BuildBuildingActionWidgetTable + 32))
#define ROAD_BUILD_DATA_BYTES 706
#define ROAD_BUILD_BOUNCE_OFFSETS_OFFSET 0x88
#define ROAD_BUILD_DIRECTION_WIDGETS_OFFSET 0xAC
#define ROAD_BUILD_CONTROL_WIDGETS_OFFSET 0x180
#define g_BridgeApproachRoadOverlayTileIds ((int *)(g_RoadBuildData))
#define g_RoadBuildModeMarkerBounceOffsets ((int *)(g_RoadBuildData + ROAD_BUILD_BOUNCE_OFFSETS_OFFSET))
#define g_RoadBuildModeDirectionalWidgets (g_RoadBuildData + ROAD_BUILD_DIRECTION_WIDGETS_OFFSET)
#define g_RoadBuildModeNorthMarkerX (*(int *)(g_RoadBuildData + 0xAC))
#define g_RoadBuildModeNorthMarkerY (*(int *)(g_RoadBuildData + 0xB0))
#define g_RoadBuildModeEastMarkerX (*(int *)(g_RoadBuildData + 0xE1))
#define g_RoadBuildModeEastMarkerY (*(int *)(g_RoadBuildData + 0xE5))
#define g_RoadBuildModeSouthMarkerX (*(int *)(g_RoadBuildData + 0x116))
#define g_RoadBuildModeSouthMarkerY (*(int *)(g_RoadBuildData + 0x11A))
#define g_RoadBuildModeWestMarkerX (*(int *)(g_RoadBuildData + 0x14B))
#define g_RoadBuildModeWestMarkerY (*(int *)(g_RoadBuildData + 0x14F))
#define g_RoadBuildModeControlWidgets ((_DWORD *)(g_RoadBuildData + ROAD_BUILD_CONTROL_WIDGETS_OFFSET))
#define g_RoadBuildModeControlWidgetState (*(int *)(g_RoadBuildData + 0x188))
 // weak
#define g_WorldMapMapModeWidgetFlags (*(int *)(g_WorldMapActionButtonWidgetTable + 8))
#define g_WorldMapJoinUnitsWidgetRecord (*(unsigned char *)(g_WorldMapActionButtonWidgetTable + WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * 3))
#define g_WorldMapJoinUnitsWidgetFlags (*(int *)(g_WorldMapActionButtonWidgetTable + WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * 3 + 8))
 // weak
typedef struct TextSpriteResourceSlotRecord {
  const char *source_stem;
  int cached_sprite_set;
  unsigned __int16 line_step_word;
  unsigned __int16 glyph_spacing_word;
} TextSpriteResourceSlotRecord;

#define TEXT_SPRITE_RESOURCE_SLOT(stem, line_step, glyph_spacing) \
  { stem ".sfn", 0, line_step, glyph_spacing }


#define TEXT_SPRITE_RESOURCE_SLOT_COUNT ((int)(sizeof(g_TextSpriteResourceSlots) / sizeof(g_TextSpriteResourceSlots[0]) - 1))
 // weak
typedef struct WorldMapTopMenuHitRecord {
  __int16 left;
  __int16 top;
  __int16 right;
  __int16 bottom;
  _WORD *menu;
} WorldMapTopMenuHitRecord;

#define WORLD_MAP_TOP_MENU_HIT_RECORD_COUNT \
  ((int)(sizeof(g_WorldMapTopMenuHitRecords) / sizeof(g_WorldMapTopMenuHitRecords[0])))


#define g_UnitTypeBattleMoveStepPx ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].battle_move_step_px)
#define g_UnitTypeMoveAnimationTickIntervalMs ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].move_animation_tick_interval_ms)
#define g_UnitTypeAnimationFrameIntervalMs ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].animation_frame_interval_ms)
#define g_UnitTypeHasIdleAnimationFlags ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].idle_animation_flags[0])
#define g_UnitTypeSpriteVerticalOffsetPx ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].sprite_vertical_offset_px)
#define g_UnitTypeAttackAnimationFrameCount ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].attack_animation_frame_count)
#define g_UnitTypeShotAnimationFrameCount ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].shot_animation_frame_count)
#define g_UnitTypeFlags ((const _DWORD *)&g_UnitTypeRuntimeCoreMetadata[0].flags)
#define g_UnitTypeBaseMeleeAttack ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].base_melee_attack)
#define g_UnitTypeBaseDefensePower ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].base_defense_power)
#define g_UnitTypeBaseActionPoints ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].base_action_points)
#define g_UnitTypeBaseShotPower ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].base_shot_power)
#define g_UnitTypeMaxRange ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].attack_range_max)
#define g_UnitTypeMinRange ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].attack_range_min)
#define g_UnitTypeBaseWallAttack ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].base_wall_attack)
#define g_UnitTypeRoadMoveCost ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].road_move_cost)
#define g_UnitTypePlainClassMoveCostA ((const unsigned char *)&g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[0])
#define g_UnitTypeForestMoveCost g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[1]
#define g_UnitTypeDesertMoveCost g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[2]
#define g_UnitTypeSwampMoveCost g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[3]
#define g_UnitTypePlainClassMoveCostB g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[4]
#define g_UnitTypeWaterSurfaceMoveCost g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[5]
#define g_UnitTypeHillsMoveCost g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[6]
#define g_UnitTypeMountainsMoveCost g_UnitTypeRuntimeCoreMetadata[0].world_surface_move_costs[7]
enum
{
  TERRAIN_MOVE_PROFILE_PLAIN_A = 0,
  TERRAIN_MOVE_PROFILE_FOREST = 1,
  TERRAIN_MOVE_PROFILE_DESERT = 2,
  TERRAIN_MOVE_PROFILE_SWAMP = 3,
  TERRAIN_MOVE_PROFILE_PLAIN_B = 4,
  TERRAIN_MOVE_PROFILE_WATER = 5,
  TERRAIN_MOVE_PROFILE_HILLS = 6,
  TERRAIN_MOVE_PROFILE_MOUNTAINS = 7
};
 // weak
#define UNIT_BATTLE_ACTION_WIDGET_COUNT 6
 // weak
#define g_UnitBattleShootButtonState (*(int *)(g_UnitBattleActionWidgetTable + 8))
#define g_UnitBattleChargeButtonWidget (*(unsigned char *)(g_UnitBattleActionWidgetTable + WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * 2))
#define g_UnitBattleChargeButtonState (*(int *)(g_UnitBattleActionWidgetTable + WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * 2 + 8))
#define g_UnitBattleExitButtonState (*(unsigned char *)(g_UnitBattleActionWidgetTable + WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * 5 + 8))
#define g_UnitBattleExitButtonOverlaySpriteIndex (*(int *)(g_UnitBattleActionWidgetTable + WORLD_MAP_ACTION_WIDGET_RECORD_SIZE * 5 + 24))
 // weak
#define g_MultiplayerStartColumns (g_MultiplayerStartRows + 1)
 // weak
#define g_CursorDesc_Busy_SecondaryId (g_CursorDesc_Busy[1])
#define g_CursorDesc_Busy_Kind (g_CursorDesc_Busy[2])
#define g_CursorDesc_Busy_Reserved1 (g_CursorDesc_Busy[3])
#define g_CursorDesc_Busy_Reserved2 (g_CursorDesc_Busy[4])
#define g_CursorDesc_Busy_HotspotX (g_CursorDesc_Busy[5])
#define g_CursorDesc_Busy_HotspotY (g_CursorDesc_Busy[6])
#define g_CursorDesc_Busy_Reserved3 (g_CursorDesc_Busy[7])
#define g_CursorDesc_Busy_Reserved4 (g_CursorDesc_Busy[8])
#define g_CursorDesc_Busy_Reserved5 (g_CursorDesc_Busy[9])
 // weak
#define g_RenderDeviceClipRightX (*(__int16 *)((unsigned char *)&g_MainRenderDevice + 2))
#define g_RenderDeviceDisplayContextPtr (*(int *)((unsigned char *)&g_MainRenderDevice + 0xB8))
#define g_DDrawDevicePtr (*(int *)((unsigned char *)&g_MainRenderDevice + 0xBC))
#define g_RenderContext (*(int *)((unsigned char *)&g_MainRenderDevice + 0xC4))
#define g_RenderDeviceAviModeChangePending (*(int *)((unsigned char *)&g_MainRenderDevice + 0xC8))
#define g_RenderDeviceAviModeChangeGuard (*(int *)((unsigned char *)&g_MainRenderDevice + 0xCC))
#define g_DisplaySurfaceBitDepth (*(int *)((unsigned char *)&g_MainRenderDevice + 0xD4))
#define g_RenderEnvPaletteContext (*(_UNKNOWN *)((unsigned char *)&g_MainRenderDevice + 0xDC))
 // weak
#define g_MiniMapDrawMask_511FF0 g_MiniMapDrawMask
#define g_MiniMapRectLeft_523344 g_MiniMapRectLeft
#define g_MiniMapRectTop_523346 g_MiniMapRectTop
#define g_MiniMapRectWidth_523348 g_MiniMapRectWidth
#define g_MiniMapRectHeight_52334A g_MiniMapRectHeight
#define g_MiniMapSurface_52334C g_MiniMapSurface
#define g_MiniMapTerrainColorTable_523F50 g_MiniMapTerrainColorTable
#define g_MiniMapPixelsPerTile_523F54 g_MiniMapPixelsPerTile
 // weak
#define UNIT_SPRITE_CACHE_RECORD_STRIDE 15
#define UNIT_SPRITE_CACHE_RECORD_COUNT 100
#define UNIT_SPRITE_CACHE_BYTES (UNIT_SPRITE_CACHE_RECORD_STRIDE * UNIT_SPRITE_CACHE_RECORD_COUNT)
 // weak, original 0x523F88..0x524563
#define UNIT_SPRITE_CACHE_DWORD(offset) (*(int *)(void *)(g_UnitSpriteCacheRecords + (offset)))
#define g_UnitSpriteCacheTableBase UNIT_SPRITE_CACHE_DWORD(0)
#define g_UnitSpriteCacheRecordOwnerKey (g_UnitSpriteCacheRecords + 4)
#define g_UnitSpriteCacheRecordPoseKey (g_UnitSpriteCacheRecords + 5)
#define g_UnitSpriteCacheRecordFacingKey (g_UnitSpriteCacheRecords + 6)
#define g_UnitSpriteCacheRecordSpriteHandle UNIT_SPRITE_CACHE_DWORD(7)
#define g_UnitSpriteCacheRecordLastUseTick UNIT_SPRITE_CACHE_DWORD(11)
 // weak
#define g_BuildingTransferTargetIdsLookahead (g_BuildingTransferTargetIds + 1)
 // recovered contiguous block at 0x5437DC..0x54389B
#define g_BattleDeploymentBucketStorage_5437DC (g_BattleDeploymentBucketStorage)
#define g_BattleDeploymentBucketRole1 (g_BattleDeploymentBucketStorage + 11)
#define g_BattleDeploymentBucketRole2 (g_BattleDeploymentBucketStorage + 23)
#define g_BattleDeploymentBucketRole3 (g_BattleDeploymentBucketStorage + 36)
 // weak
#define g_BuildingSpriteCacheKeyCol2 (g_BuildingSpriteCache + 1)
#define g_BuildingSpriteCacheKeyCol3 (g_BuildingSpriteCache + 2)
#define g_BuildingSpriteCacheKeyCol4Signed (g_BuildingSpriteCache + 3)
#define g_BuildingSpriteCacheKeyCol5 (g_BuildingSpriteCache + 4)
#define g_BuildingSpriteCacheRecordSpriteHandle (*(int *)(g_BuildingSpriteCache + 5))
#define g_BuildingSpriteCacheRecordLastUseTick (*(int *)(g_BuildingSpriteCache + 9))
#define BUILDING_SPRITE_CACHE_RECORD_STRIDE 13
#define BUILDING_SPRITE_CACHE_RECORD_COUNT 50
 // weak
enum { CASTLE_SITE_ANCHOR_CACHE_COUNT = 100 };
 // weak
#define g_MouseCursorRawX (*((int *)&g_RenderState[9]))
#define g_MouseCursorRawY (*((int *)&g_RenderState[10]))

/* Types originally introduced inside recovered implementation fragments. */
typedef struct WCCompatLink {
  int next_link;
  int value;
} WCCompatLink;

typedef struct WCCompatListBase {
  int head_link;
  int vtable;
  int tail_link;
  int count;
  int alloc_fn;
  int free_fn;
} WCCompatListBase;

typedef struct CompatRenderStateTail
{
  int field_464_active;
  int field_468_active;
  int field_46C_ticks;
  int field_470_ticks;
  int field_474_handle;
} CompatRenderStateTail;

/*
 * The original globals at 0x512570..0x51258D are fields inside one packed
 * 88-byte record, not independent one-element arrays.  Retaining those
 * placeholders made every nonzero unit type index into unrelated host data.
 * The records below restore all 88 executable-backed bytes while
 * keeping the original 88-byte indexing used throughout the recovered C.
 * Original pointer values are Win32 VAs kept as evidence only; they must not
 * be dereferenced as host addresses. The native pointer companion resolves
 * their targets. The 32 bytes at +38 remain semantically unrecovered.
 */
#pragma pack(push, 1)
typedef struct UnitTypeRuntimeCoreMetadataRecord
{
  _DWORD original_localized_name_table_va;
  _DWORD original_resource_key_va;
  unsigned char battle_move_step_px;
  unsigned char move_animation_tick_interval_ms;
  unsigned char animation_frame_interval_ms;
  unsigned char idle_animation_flags[4];
  unsigned char sprite_vertical_offset_px;
  unsigned char attack_animation_frame_count;
  unsigned char shot_animation_frame_count;
  _DWORD flags;
  unsigned char base_melee_attack;
  unsigned char base_defense_power;
  unsigned char base_action_points;
  unsigned char base_shot_power;
  unsigned char attack_range_max;
  unsigned char attack_range_min;
  unsigned char base_wall_attack;
  unsigned char road_move_cost;
  unsigned char world_surface_move_costs[8];
  unsigned char unrecovered_38_69[32];
  unsigned char vision_radius;
  unsigned char production_time;
  unsigned char production_cost;
  uint16_t production_licence_cost;
  unsigned char production_required_tech_level_mode_2;
  unsigned char production_required_tech_level_other_modes;
  unsigned char role;
  unsigned char corpse_sprite_base_index;
  unsigned char melee_attack_sound_frame;
  unsigned char ranged_attack_sound_frame;
  _DWORD original_move_sound_stem_va;
  unsigned char move_sound_variant_count;
  unsigned char move_sound_base_volume;
  unsigned char autoresolve_casualty_weight;
} UnitTypeRuntimeCoreMetadataRecord;
#pragma pack(pop)

/* Host-only companion for the three pointer fields in the original packed
 * record. Localized triplets retain original sharing and font-encoded bytes. */
typedef struct UnitTypeRuntimePointerRecord
{
  char *const *localized_names;
  const char *resource_key;
  const char *move_sound_stem;
} UnitTypeRuntimePointerRecord;

typedef char UnitTypeRuntimeCoreMetadataRecord_size_check[
  sizeof(UnitTypeRuntimeCoreMetadataRecord) == UNIT_TYPE_METADATA_STRIDE ? 1 : -1];

CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, unrecovered_38_69) == 38, "unit metadata raw span");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, vision_radius) == 70, "unit metadata vision");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, production_time) == 71, "unit metadata production time");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, production_cost) == 72, "unit metadata production cost");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, production_licence_cost) == 73, "unit metadata licence cost");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, production_required_tech_level_mode_2) == 75, "unit metadata mode 2 tech");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, production_required_tech_level_other_modes) == 76, "unit metadata other tech");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, role) == 77, "unit metadata tactical role");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, corpse_sprite_base_index) == 78, "unit metadata corpse sprite");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, melee_attack_sound_frame) == 79, "unit metadata melee sound");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, ranged_attack_sound_frame) == 80, "unit metadata ranged sound");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, original_move_sound_stem_va) == 81, "unit metadata movement stem VA");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, move_sound_variant_count) == 85, "unit metadata movement variants");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, move_sound_base_volume) == 86, "unit metadata movement volume");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeRuntimeCoreMetadataRecord, autoresolve_casualty_weight) == 87, "unit metadata casualty weight");

#endif /* CLASH95_RECOVERED_TYPES_H */
