/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Legacy CRT/Win32-era import declarations without manifest definitions (282); typed against compatibility/decomp_runtime_stubs.c in a later tranche. */
#ifndef CLASH95_RECOVERED_LEGACY_IMPORTS_H
#define CLASH95_RECOVERED_LEGACY_IMPORTS_H

#include "recovered_types.h"

int AVIFileExit();
int __stdcall AVIStreamEndStreaming();
int __cdecl Audio_MixInterleaved16(int a1, int a2, int a3, signed int *a4);
unsigned int  Audio_ReturnDSoundError(unsigned int result);
int __fastcall CAviDecompressor_ApplyDecoderFormatParams(_DWORD, _DWORD); // weak
int CRT_ConstructThreadDataBlock(); // weak
int CRT_DestroyThreadDataBlock(); // weak
_DWORD CRT_FreeTlsIndex(); // weak
__int64 __fastcall CRT_GetBootstrapThreadData(_DWORD, _DWORD);
int __fastcall CRT_RegisterFinalizableObject(_DWORD, _DWORD); // weak
int __cdecl CRT_RunGuardedStaticLocalInit(void);
int CRT_ThrowExcStringException();
int CRT_WatcomEHFrameHandler();
void  __noreturn CRT_WatcomEHHandleNestedException(int a1, int a2);
int __cdecl CSyncObject_Unlock(CSyncObject *this, __int32, __int32 *);
int Compat_AllocFileStream(void);
int Compat_AllocLow32Bytes(int size);
int Compat_CanOpenReadPath(const char *path);
void Compat_CopyPrefixN(char *dest, const char *src, unsigned int count);
HRESULT Compat_DirectDrawSurface_Blt(LPDIRECTDRAWSURFACE surface, RECT *dest_rect, LPDIRECTDRAWSURFACE src_surface, RECT *src_rect, DWORD flags, void *blt_fx);
HRESULT Compat_DirectDrawSurface_GetAttachedSurface(LPDIRECTDRAWSURFACE surface, void *caps, void *out_surface);
HRESULT Compat_DirectDrawSurface_IsLost(LPDIRECTDRAWSURFACE surface);
HRESULT Compat_DirectDrawSurface_Lock(LPDIRECTDRAWSURFACE surface, RECT *rect, int *desc, DWORD flags, HANDLE event_handle);
HRESULT Compat_DirectDrawSurface_Restore(LPDIRECTDRAWSURFACE surface);
HRESULT Compat_DirectDrawSurface_SetClipper(LPDIRECTDRAWSURFACE surface, void *clipper);
HRESULT Compat_DirectDrawSurface_SetPalette(LPDIRECTDRAWSURFACE surface, void *palette);
HRESULT Compat_DirectDrawSurface_Unlock(LPDIRECTDRAWSURFACE surface, void *lock_ptr);
HRESULT Compat_DirectDraw_CreatePalette(LPDIRECTDRAW dd, DWORD flags, void *entries, void *out_palette);
HRESULT Compat_DirectDraw_CreateSurface(LPDIRECTDRAW dd, int *desc, void *out_surface);
HRESULT Compat_DirectDraw_QueryInterface(LPDIRECTDRAW dd, const void *riid, void *out_object);
ULONG Compat_DirectDraw_Release(LPDIRECTDRAW dd);
HRESULT Compat_DirectDraw_SetCooperativeLevel(LPDIRECTDRAW dd, HWND hwnd, DWORD flags);
HRESULT Compat_DirectDraw_SetDisplayMode(LPDIRECTDRAW dd, int width, int height, int bpp, int refresh_rate, int flags);
void Compat_FreeFileStream(int stream_ptr);
void Compat_FreeLow32Bytes(int ptr);
int Compat_InitFileStream(int stream_ptr, int fd_index, int mode_char, int open_flags);
int Compat_OpenFileDescriptor(const char *path, int mode_char, int open_flags);
int Compat_StreamRead(int stream_ptr, void *buffer, int byte_count);
int Compat_StreamSeek(int stream_ptr, int offset, int whence);
int Compat_StreamSetBuffer(int stream_ptr, int buffer_size);
int Compat_StreamTell(int stream_ptr);
char *Compat_StrrchrChar(const char *text, int ch);
char *Compat_StruprAsciiInPlace(char *text);
int Compat_WcppCtorArrayStorage1m(void *base, int count, const void *descriptor);
int Compat_WcppCtorArrayStorage1s(void *block, int count, const void *descriptor);
BOOL __stdcall CreateDirectoryA(LPCSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes);
HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
BOOL __stdcall CreateProcessA();
HANDLE __stdcall CreateThread(LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
BOOL __stdcall DeleteFileA(LPCSTR lpFileName);
HRESULT __stdcall DirectDrawCreate(GUID *lpGUID, LPDIRECTDRAW *lplpDD, IUnknown *pUnkOuter);
int __stdcall DirectInputCreateA();
int __stdcall DirectSoundCreate();
BOOL __stdcall DuplicateHandle();
int EFG_Format_();
void __stdcall EnterCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
_DWORD ExcString_AsCharPtr(void);
void __stdcall ExitProcess();
void __stdcall ExitThread(DWORD dwExitCode);
BOOL __stdcall FindClose();
HANDLE __stdcall FindFirstFileA(LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData);
HRSRC __stdcall FindResourceA();
UINT __stdcall GetACP();
BOOL __stdcall GetCPInfo();
LPSTR __stdcall GetCommandLineA();
LPWSTR __stdcall GetCommandLineW();
HANDLE __stdcall GetCurrentProcess();
DWORD __stdcall GetCurrentProcessId();
HANDLE __stdcall GetCurrentThread();
DWORD __stdcall GetCurrentThreadId();
LPCH __stdcall GetEnvironmentStrings();
BOOL __stdcall GetExitCodeProcess(HANDLE hProcess, LPDWORD lpExitCode);
DWORD __stdcall GetFileAttributesA();
DWORD __stdcall GetLastError();
DWORD __stdcall GetModuleFileNameA();
UINT __stdcall GetOEMCP();
FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
DWORD __stdcall GetTimeZoneInformation(LPTIME_ZONE_INFORMATION lpTimeZoneInformation);
HGLOBAL __stdcall GlobalAlloc(UINT uFlags, SIZE_T dwBytes);
HGLOBAL __stdcall GlobalFree();
LPVOID __stdcall GlobalLock(HGLOBAL hMem);
BOOL __stdcall GlobalUnlock(HGLOBAL hMem);
int __cdecl ICClose();
int __cdecl ICDecompress();
int __stdcall ICGetDisplayFormat();
int __stdcall ICLocate();
double __cdecl IF_ASIN();
double __cdecl IF_DACOS();
double IF_DCOSH();
double  IF_DPOW();
double IF_DSINH();
double IF_DTANH();
int __fastcall IO_InertRouterCallbackSlot(_DWORD, _DWORD); // weak
int IO_OutNewline();
char * IO_OutWriteToken(char *result);
int __fastcall IO_RemoveFileByPath(_DWORD, _DWORD); // weak
void __stdcall LeaveCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
signed int  Lexer_CheckValueList(int *a1, int a2);
_DWORD * Lexer_FindTemplateSlot(int a1, int a2, _DWORD *a3);
int  Lexer_OutputFieldRange(int result, int a2, int a3, int a4, int a5);
int  Lexer_ParseDeftemplate(int a1, int a2);
int  Lexer_ParseDuplicate(int a1, int a2);
int  Lexer_ParseModify(int a1, int a2);
signed int  Lexer_WarnImpliedTemplate(int a1, int a2, int a3);
HMODULE __stdcall LoadLibraryA();
HGLOBAL __stdcall LoadResource(HMODULE hModule, HRSRC hResInfo);
LPVOID __stdcall LockResource();
_DWORD * Module_AllocList(signed int a1);
BOOL __stdcall MoveFileA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName);
int __stdcall MultiByteToWideChar();
int __thiscall Noop_AppShutdownPostAudioCloseHook(_DWORD); // weak
int Noop_AppShutdownPreAudioCloseHook(void); // weak
int __fastcall Noop_CrtExitHandlerPair(_DWORD, _DWORD);
int Noop_CrtIoInitHook(void);
int Noop_CrtLockEnterLeaveResetStub(void);
_DWORD Noop_CrtSingleThreadLockStub(); // weak
int Noop_DebugHotkeyF1Handler(void); // weak
int __fastcall Noop_DeftemplateResetCallback(_DWORD, _DWORD); // weak
int Noop_FatalQueryStreamDestruct(void);
int Noop_FatalQueryStreamPutBackByte(void);
int Noop_InputDeviceDoOp(void);
int Noop_InputDeviceGetParamB(void);
int Noop_InputDeviceSetParamA(void);
int Noop_PathEntryArrayDeletingDtor(void);
int __thiscall Noop_PlayGameSessionBoundaryHook(_DWORD); // weak
int Noop_RulesRecordScalarDeletingDtor(void);
int Noop_SurfaceCursorUnboundedAdvance(void);
int __thiscall Noop_WCIsvListErrorHook(_DWORD); // weak
int Noop_WorldMapFrameRedrawHook(void); // weak
BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount);
void __stdcall RaiseException(DWORD dwExceptionCode, DWORD dwExceptionFlags, DWORD nNumberOfArguments, const ULONG_PTR *lpArguments);
BOOL __stdcall ReadFile();
BOOL __stdcall RemoveDirectoryA(LPCSTR lpPathName);
int Render_CreateSprite();
int Render_DrawSprite();
void Render_LoadResourceSprite_v2();
int  Render_LoadResourceSprite_v3(_BYTE *a1);
void  Render_LoadResourceSprite_v4(int a1, _BYTE *a2, int a3, char a4, DWORD a5);
int  Render_SetResourceHandle(int, int);
BOOL __stdcall ResetEvent();
DWORD __stdcall ResumeThread(HANDLE hThread);
void __stdcall RtlUnwind(PVOID TargetFrame, PVOID TargetIp, PEXCEPTION_RECORD ExceptionRecord, PVOID ReturnValue);
BOOL __stdcall SetEnvironmentVariableA();
BOOL __stdcall SetEnvironmentVariableW(LPCWSTR lpName, LPCWSTR lpValue);
BOOL __stdcall SetEvent();
void __stdcall SetLastError(DWORD dwErrCode);
BOOL __stdcall SetThreadPriority();
LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
DWORD __stdcall SuspendThread(HANDLE hThread);
DWORD __stdcall TlsAlloc();
BOOL __stdcall TlsFree(DWORD dwTlsIndex);
LPVOID __stdcall TlsGetValue();
BOOL __stdcall TlsSetValue(DWORD dwTlsIndex, LPVOID lpTlsValue);
int  UI_ConfirmSelectionApply(int a1, int a2, DWORD a3, char a4, double a5);
int  UI_HandleClickDispatch(int a1);
int  UI_SetCurrentSelection(int a1, int a2);
LONG __stdcall UnhandledExceptionFilter();
int  Unit_CopyFlagsFromTemplate(int result, int a2);
signed int  Unit_GetSquadCount(intptr_t a1);
DWORD __stdcall WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds);
BOOL __stdcall WriteFile();
int __fastcall _AddThreadData_();
double __cdecl _CHP(_DWORD, _DWORD);
int _FDFS();
int __fastcall _FiniRtns();
int _GetThreadData_();
__int64 __thiscall _I8D();
__int64 __fastcall _I8M();
int _InitRtns();
int __fastcall _InitThreadData_();
int _NTAtMaxFiles_();
int _NTConsoleOutput_();
int __fastcall _NTFindNextFileWithAttr_();
int __cdecl _NTGetFakeHandle_();
int _NTInitFileHandles_();
int _NTRemoveFileHandle_();
int _ReallocThreadData_();
int _RemoveThreadData_();
int __cdecl _SetIOMode_();
int _allocfp_();
int __fastcall _brktime_();
int __fastcall _ccmdline_();
int _chktty_();
int __fastcall _clib_ulltoa_();
int _cnvs2d_();
int __fastcall _doclose_();
int __fastcall _fatal_runtime_error_();
int __fastcall _flush_();
int _freefp_();
int _init_stack_limits_();
int _ioalloc_();
int _lib_GetModuleFileNameW_(_DWORD module, _WORD *buffer, _DWORD byte_count);
int _no_support_loaded(void);
__int64 _nt_filetime_cvt_();
errno_t __cdecl _set_errno_(int Value);
int __cdecl _set_errno_dos_();
int __cdecl _set_errno_nt_();
int __fastcall _wcpp_4_call_terminate__();
int __thiscall _wcpp_4_corrupted_stack__();
int __cdecl _wcpp_4_ctor_array_storage_1m__();
int _wcpp_4_ctor_array_storage_1s__();
int __fastcall _wcpp_4_dtor_array__();
_DWORD __stdcall _wcpp_4_exc_setup__();
int __fastcall _wcpp_4_fatal_runtime_error__();
__int64 __thiscall _wcpp_4_pgm_thread__();
int _wcpp_4_stab_trav_init__();
int __fastcall _wcpp_4_stab_trav_move__();
int _wcpp_4_stab_trav_next__();
_DWORD __cdecl bad_exception_dtor(bad_exception *this);
_DWORD __stdcall beginthreadex_();
int __fastcall calloc_();
int __cdecl close_();
void __noreturn endthread_();
int __thiscall fflush_();
__int64 __fastcall fgetc_();
char *fgets_(char *buffer, int buffer_size, int stream_handle);
int __thiscall findclose_();
int __fastcall findnext_();
int __fastcall fputs_();
int __cdecl fread_();
__int64 __fastcall ftell_();
int ftime_(void *time_buffer);
int  fwrite_(const void *, int, int, int);
int __fastcall getcwd_();
int getenv_();
int __fastcall isatty_();
int __fastcall ismbclegal_();
__int64 __thiscall j_Mem_Alloc(_DWORD); // weak
int j___FreeThreadDataList_(void); // weak
_DWORD j___NTAddFileHandle_(); // weak
int j___NTAddFileHandle__0(); // weak
int j___NTRemoveFileHandle_(void);
int __cdecl j__nfree_();
int __cdecl j_j__nfree_();
int j_rand_();
int j_srand_(void); // weak
HFILE __stdcall lclose(HFILE hFile);
HFILE __stdcall lopen();
UINT __stdcall lread(HFILE hFile, LPVOID lpBuffer, UINT uBytes);
int __fastcall lseek_();
int mbclen_();
int __fastcall memcpy_();
int __thiscall nfree_(_DWORD); // weak
int __fastcall nrealloc_();
int plib_malloc__1();
int __fastcall setvbuf_();
int __cdecl sscanf_(const char *buffer, const char *format, ...);
int __thiscall stackavail_();
int __fastcall stricmp_();
int __fastcall strncmp_();
int __fastcall strncpy_();
int __cdecl strrchr_();
double __fastcall strtod_();
_DWORD __stdcall sub_47C181();
_DWORD __stdcall sub_47C1C0();
_DWORD sub_48455B();
int __fastcall sub_488A97();
int sub_4965FF();
int __fastcall sub_496643();
int __fastcall sub_4B5A33();
int system_(const char *command);
int tell_();
int __fastcall tolower_();
int __thiscall towupper_();
int __fastcall unknown_libname_10();
int unknown_libname_13();
int __thiscall unknown_libname_2();
int __fastcall unknown_libname_5();
int unknown_libname_7();
int unknown_libname_8();
int __fastcall vsprintf_();
MMRESULT __stdcall waveOutClose(HWAVEOUT hwo);
MMRESULT __stdcall waveOutGetDevCapsA(UINT_PTR uDeviceID, LPWAVEOUTCAPSA pwoc, UINT cbwoc);
UINT __stdcall waveOutGetNumDevs();
MMRESULT __stdcall waveOutOpen(LPHWAVEOUT phwo, UINT uDeviceID, LPCWAVEFORMATEX pwfx, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
MMRESULT __stdcall waveOutPrepareHeader();
MMRESULT __stdcall waveOutReset(HWAVEOUT hwo);
MMRESULT __stdcall waveOutUnprepareHeader();
MMRESULT __stdcall waveOutWrite(HWAVEOUT hwo, LPWAVEHDR pwh, UINT cbwh);
int __fastcall wcslen_();
int __fastcall wcstombs_();
int __fastcall wctomb_();

#endif /* CLASH95_RECOVERED_LEGACY_IMPORTS_H */
