/* GENERATED by tools/gen_recovered_structs.py -- do not edit by hand.
 *
 * Packed struct overlays for the recovered game records, with explicit gap
 * members for unrecovered spans and compile-time pins on sizeof/offsetof.
 * A layout mismatch fails the build. Regenerate after editing
 * RECOVERED_STRUCTURES.json. Pointers are 4-byte low32_ptr handles (the
 * reconstruction's 32-bit memory model compiled under LP64).
 */

#ifndef CLASH95_RECOVERED_STRUCTS_H
#define CLASH95_RECOVERED_STRUCTS_H

#include <stddef.h>
#include "recovered_types.h"

typedef uint32_t low32_ptr;

typedef struct __attribute__((packed)) UnitTypeMetadataRecord {
  low32_ptr localized_name_table;
  low32_ptr resource_key;
  uint8_t move_pixel_speed;
  uint8_t move_tick_delay;
  uint8_t animation_frame_interval;
  uint8_t animation_flags;
  unsigned char unrecovered_0x0C_0x0F[3];
  uint8_t sprite_vertical_offset_px;
  uint8_t melee_attack_frame_count;
  uint8_t ranged_attack_frame_count;
  uint32_t type_flags;
  uint8_t base_melee_attack;
  uint8_t base_defense_power;
  uint8_t base_action_points;
  uint8_t base_shot_power;
  uint8_t attack_range_max;
  uint8_t attack_range_min;
  uint8_t base_wall_attack;
  uint8_t road_move_cost;
  uint8_t world_surface_move_costs[8];
  uint8_t unrecovered_38_69[32];
  uint8_t vision_radius;
  uint8_t production_time;
  uint8_t production_cost;
  uint16_t production_licence_cost;
  uint8_t production_required_tech_level_mode_2;
  uint8_t production_required_tech_level_other_modes;
  uint8_t role;
  uint8_t corpse_sprite_base_index;
  uint8_t melee_attack_sound_frame;
  uint8_t ranged_attack_sound_frame;
  low32_ptr move_sound_stem;
  uint8_t move_sound_variant_count;
  uint8_t move_sound_base_volume;
  uint8_t autoresolve_casualty_weight;
} UnitTypeMetadataRecord;
CLASH95_STATIC_ASSERT(sizeof(UnitTypeMetadataRecord) == 88, "UnitTypeMetadataRecord size");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, localized_name_table) == 0, "UnitTypeMetadataRecord.localized_name_table");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, resource_key) == 4, "UnitTypeMetadataRecord.resource_key");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, move_pixel_speed) == 8, "UnitTypeMetadataRecord.move_pixel_speed");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, move_tick_delay) == 9, "UnitTypeMetadataRecord.move_tick_delay");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, animation_frame_interval) == 10, "UnitTypeMetadataRecord.animation_frame_interval");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, animation_flags) == 11, "UnitTypeMetadataRecord.animation_flags");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, sprite_vertical_offset_px) == 15, "UnitTypeMetadataRecord.sprite_vertical_offset_px");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, melee_attack_frame_count) == 16, "UnitTypeMetadataRecord.melee_attack_frame_count");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, ranged_attack_frame_count) == 17, "UnitTypeMetadataRecord.ranged_attack_frame_count");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, type_flags) == 18, "UnitTypeMetadataRecord.type_flags");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, base_melee_attack) == 22, "UnitTypeMetadataRecord.base_melee_attack");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, base_defense_power) == 23, "UnitTypeMetadataRecord.base_defense_power");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, base_action_points) == 24, "UnitTypeMetadataRecord.base_action_points");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, base_shot_power) == 25, "UnitTypeMetadataRecord.base_shot_power");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, attack_range_max) == 26, "UnitTypeMetadataRecord.attack_range_max");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, attack_range_min) == 27, "UnitTypeMetadataRecord.attack_range_min");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, base_wall_attack) == 28, "UnitTypeMetadataRecord.base_wall_attack");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, road_move_cost) == 29, "UnitTypeMetadataRecord.road_move_cost");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, world_surface_move_costs) == 30, "UnitTypeMetadataRecord.world_surface_move_costs");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, unrecovered_38_69) == 38, "UnitTypeMetadataRecord.unrecovered_38_69");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, vision_radius) == 70, "UnitTypeMetadataRecord.vision_radius");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, production_time) == 71, "UnitTypeMetadataRecord.production_time");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, production_cost) == 72, "UnitTypeMetadataRecord.production_cost");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, production_licence_cost) == 73, "UnitTypeMetadataRecord.production_licence_cost");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, production_required_tech_level_mode_2) == 75, "UnitTypeMetadataRecord.production_required_tech_level_mode_2");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, production_required_tech_level_other_modes) == 76, "UnitTypeMetadataRecord.production_required_tech_level_other_modes");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, role) == 77, "UnitTypeMetadataRecord.role");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, corpse_sprite_base_index) == 78, "UnitTypeMetadataRecord.corpse_sprite_base_index");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, melee_attack_sound_frame) == 79, "UnitTypeMetadataRecord.melee_attack_sound_frame");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, ranged_attack_sound_frame) == 80, "UnitTypeMetadataRecord.ranged_attack_sound_frame");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, move_sound_stem) == 81, "UnitTypeMetadataRecord.move_sound_stem");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, move_sound_variant_count) == 85, "UnitTypeMetadataRecord.move_sound_variant_count");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, move_sound_base_volume) == 86, "UnitTypeMetadataRecord.move_sound_base_volume");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeMetadataRecord, autoresolve_casualty_weight) == 87, "UnitTypeMetadataRecord.autoresolve_casualty_weight");

typedef struct __attribute__((packed)) UnitTypeLocalizedNameTable {
  low32_ptr polish_name;
  low32_ptr english_name;
  low32_ptr german_name;
} UnitTypeLocalizedNameTable;
CLASH95_STATIC_ASSERT(sizeof(UnitTypeLocalizedNameTable) == 12, "UnitTypeLocalizedNameTable size");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeLocalizedNameTable, polish_name) == 0, "UnitTypeLocalizedNameTable.polish_name");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeLocalizedNameTable, english_name) == 4, "UnitTypeLocalizedNameTable.english_name");
CLASH95_STATIC_ASSERT(offsetof(UnitTypeLocalizedNameTable, german_name) == 8, "UnitTypeLocalizedNameTable.german_name");

typedef struct __attribute__((packed)) UnitMoveSpriteCacheEntry {
  int32_t unit_type_id;
  uint8_t owner_index;
  uint8_t facing_direction;
  uint8_t frame_index;
  int32_t sprite_handle;
  int32_t last_used_tick;
} UnitMoveSpriteCacheEntry;
CLASH95_STATIC_ASSERT(sizeof(UnitMoveSpriteCacheEntry) == 15, "UnitMoveSpriteCacheEntry size");
CLASH95_STATIC_ASSERT(offsetof(UnitMoveSpriteCacheEntry, unit_type_id) == 0, "UnitMoveSpriteCacheEntry.unit_type_id");
CLASH95_STATIC_ASSERT(offsetof(UnitMoveSpriteCacheEntry, owner_index) == 4, "UnitMoveSpriteCacheEntry.owner_index");
CLASH95_STATIC_ASSERT(offsetof(UnitMoveSpriteCacheEntry, facing_direction) == 5, "UnitMoveSpriteCacheEntry.facing_direction");
CLASH95_STATIC_ASSERT(offsetof(UnitMoveSpriteCacheEntry, frame_index) == 6, "UnitMoveSpriteCacheEntry.frame_index");
CLASH95_STATIC_ASSERT(offsetof(UnitMoveSpriteCacheEntry, sprite_handle) == 7, "UnitMoveSpriteCacheEntry.sprite_handle");
CLASH95_STATIC_ASSERT(offsetof(UnitMoveSpriteCacheEntry, last_used_tick) == 11, "UnitMoveSpriteCacheEntry.last_used_tick");

typedef struct __attribute__((packed)) BuildingSpriteCacheEntry {
  uint8_t building_class_or_group;
  uint8_t owner_index;
  int8_t damage_variant;
  uint8_t building_variant_index;
  uint8_t footprint_tile_variant;
  int32_t sprite_set_handle;
  int32_t last_used_tick;
} BuildingSpriteCacheEntry;
CLASH95_STATIC_ASSERT(sizeof(BuildingSpriteCacheEntry) == 13, "BuildingSpriteCacheEntry size");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, building_class_or_group) == 0, "BuildingSpriteCacheEntry.building_class_or_group");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, owner_index) == 1, "BuildingSpriteCacheEntry.owner_index");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, damage_variant) == 2, "BuildingSpriteCacheEntry.damage_variant");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, building_variant_index) == 3, "BuildingSpriteCacheEntry.building_variant_index");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, footprint_tile_variant) == 4, "BuildingSpriteCacheEntry.footprint_tile_variant");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, sprite_set_handle) == 5, "BuildingSpriteCacheEntry.sprite_set_handle");
CLASH95_STATIC_ASSERT(offsetof(BuildingSpriteCacheEntry, last_used_tick) == 9, "BuildingSpriteCacheEntry.last_used_tick");

typedef struct __attribute__((packed)) UnitSlotRecord {
  int16_t unit_type_id;
  uint8_t owner_player_index;
  unsigned char unrecovered_0x03_0x08[5];
  uint8_t current_action_points;
  uint8_t current_health_percent;
  uint8_t fatigue;
  uint8_t morale;
  uint8_t stance_bits;
  uint8_t state_flags;
  unsigned char unrecovered_0x0E_0x12[4];
  uint32_t aux_runtime_state;
  uint8_t state_bits_2;
  unsigned char unrecovered_0x17_0x1F[8];
} UnitSlotRecord;
CLASH95_STATIC_ASSERT(sizeof(UnitSlotRecord) == 31, "UnitSlotRecord size");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, unit_type_id) == 0, "UnitSlotRecord.unit_type_id");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, owner_player_index) == 2, "UnitSlotRecord.owner_player_index");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, current_action_points) == 8, "UnitSlotRecord.current_action_points");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, current_health_percent) == 9, "UnitSlotRecord.current_health_percent");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, fatigue) == 10, "UnitSlotRecord.fatigue");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, morale) == 11, "UnitSlotRecord.morale");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, stance_bits) == 12, "UnitSlotRecord.stance_bits");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, state_flags) == 13, "UnitSlotRecord.state_flags");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, aux_runtime_state) == 18, "UnitSlotRecord.aux_runtime_state");
CLASH95_STATIC_ASSERT(offsetof(UnitSlotRecord, state_bits_2) == 22, "UnitSlotRecord.state_bits_2");

typedef struct __attribute__((packed)) PathWaypoint {
  uint8_t tile_row;
  uint8_t tile_column;
  uint16_t cumulative_cost;
} PathWaypoint;
CLASH95_STATIC_ASSERT(sizeof(PathWaypoint) == 4, "PathWaypoint size");
CLASH95_STATIC_ASSERT(offsetof(PathWaypoint, tile_row) == 0, "PathWaypoint.tile_row");
CLASH95_STATIC_ASSERT(offsetof(PathWaypoint, tile_column) == 1, "PathWaypoint.tile_column");
CLASH95_STATIC_ASSERT(offsetof(PathWaypoint, cumulative_cost) == 2, "PathWaypoint.cumulative_cost");

typedef struct __attribute__((packed)) QueuedPathBuffer {
  int32_t waypoint_count;
  PathWaypoint waypoints[100];
} QueuedPathBuffer;
CLASH95_STATIC_ASSERT(sizeof(QueuedPathBuffer) == 404, "QueuedPathBuffer size");
CLASH95_STATIC_ASSERT(offsetof(QueuedPathBuffer, waypoint_count) == 0, "QueuedPathBuffer.waypoint_count");
CLASH95_STATIC_ASSERT(offsetof(QueuedPathBuffer, waypoints) == 4, "QueuedPathBuffer.waypoints");

typedef struct __attribute__((packed)) UnitStackRecord {
  int16_t tile_row;
  int16_t tile_column;
  uint8_t owner_player_index;
  uint8_t facing_direction;
  UnitSlotRecord unit_slots[10];
  QueuedPathBuffer queued_path;
  uint8_t is_hidden_on_world_map;
  unsigned char unrecovered_0x2D1_0x2D5[4];
} UnitStackRecord;
CLASH95_STATIC_ASSERT(sizeof(UnitStackRecord) == 725, "UnitStackRecord size");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, tile_row) == 0, "UnitStackRecord.tile_row");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, tile_column) == 2, "UnitStackRecord.tile_column");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, owner_player_index) == 4, "UnitStackRecord.owner_player_index");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, facing_direction) == 5, "UnitStackRecord.facing_direction");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, unit_slots) == 6, "UnitStackRecord.unit_slots");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, queued_path) == 316, "UnitStackRecord.queued_path");
CLASH95_STATIC_ASSERT(offsetof(UnitStackRecord, is_hidden_on_world_map) == 720, "UnitStackRecord.is_hidden_on_world_map");

typedef struct __attribute__((packed)) MapTileRecord {
  uint16_t terrain_tile_id;
  uint16_t overlay_tile_id;
  uint16_t road_or_bridge_tile_id;
  unsigned char unrecovered_0x06_0x0E[8];
} MapTileRecord;
CLASH95_STATIC_ASSERT(sizeof(MapTileRecord) == 14, "MapTileRecord size");
CLASH95_STATIC_ASSERT(offsetof(MapTileRecord, terrain_tile_id) == 0, "MapTileRecord.terrain_tile_id");
CLASH95_STATIC_ASSERT(offsetof(MapTileRecord, overlay_tile_id) == 2, "MapTileRecord.overlay_tile_id");
CLASH95_STATIC_ASSERT(offsetof(MapTileRecord, road_or_bridge_tile_id) == 4, "MapTileRecord.road_or_bridge_tile_id");

typedef struct __attribute__((packed)) TileTrapOwnerMaskLayer {
  uint8_t owner_mask;
} TileTrapOwnerMaskLayer;
CLASH95_STATIC_ASSERT(sizeof(TileTrapOwnerMaskLayer) == 1, "TileTrapOwnerMaskLayer size");
CLASH95_STATIC_ASSERT(offsetof(TileTrapOwnerMaskLayer, owner_mask) == 0, "TileTrapOwnerMaskLayer.owner_mask");

typedef struct __attribute__((packed)) PlayerPrisonerTransferQueue {
  int8_t prisoner_type_id;
  uint8_t captured_owner_player_index;
  uint16_t capture_tile_row;
  uint16_t capture_tile_column;
} PlayerPrisonerTransferQueue;
CLASH95_STATIC_ASSERT(sizeof(PlayerPrisonerTransferQueue) == 6, "PlayerPrisonerTransferQueue size");
CLASH95_STATIC_ASSERT(offsetof(PlayerPrisonerTransferQueue, prisoner_type_id) == 0, "PlayerPrisonerTransferQueue.prisoner_type_id");
CLASH95_STATIC_ASSERT(offsetof(PlayerPrisonerTransferQueue, captured_owner_player_index) == 1, "PlayerPrisonerTransferQueue.captured_owner_player_index");
CLASH95_STATIC_ASSERT(offsetof(PlayerPrisonerTransferQueue, capture_tile_row) == 2, "PlayerPrisonerTransferQueue.capture_tile_row");
CLASH95_STATIC_ASSERT(offsetof(PlayerPrisonerTransferQueue, capture_tile_column) == 4, "PlayerPrisonerTransferQueue.capture_tile_column");

typedef struct __attribute__((packed)) PlayerRuntimeState {
  int32_t is_active;
  char display_name[11];
  int32_t camera_left;
  int32_t camera_top;
  int32_t minimap_visible_flag;
  int32_t controller_mode;
  unsigned char unrecovered_0x1F_0x27[8];
  int32_t religion_flag;
  unsigned char unrecovered_0x2B_0x2F[4];
  uint8_t tech_level;
  uint8_t last_reported_tech_level;
  int32_t battle_action_taken_flag;
  int32_t consecutive_idle_battle_turns;
  uint8_t revealed_tiles_bitset[1300];
  PlayerPrisonerTransferQueue prisoner_transfer_queue[10];
  unsigned char unrecovered_0x589_0x58B[2];
  uint8_t queen_relationship_state;
  uint8_t queen_portrait_index;
  uint16_t queen_next_relationship_check_turn;
} PlayerRuntimeState;
CLASH95_STATIC_ASSERT(sizeof(PlayerRuntimeState) == 1423, "PlayerRuntimeState size");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, is_active) == 0, "PlayerRuntimeState.is_active");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, display_name) == 4, "PlayerRuntimeState.display_name");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, camera_left) == 15, "PlayerRuntimeState.camera_left");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, camera_top) == 19, "PlayerRuntimeState.camera_top");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, minimap_visible_flag) == 23, "PlayerRuntimeState.minimap_visible_flag");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, controller_mode) == 27, "PlayerRuntimeState.controller_mode");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, religion_flag) == 39, "PlayerRuntimeState.religion_flag");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, tech_level) == 47, "PlayerRuntimeState.tech_level");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, last_reported_tech_level) == 48, "PlayerRuntimeState.last_reported_tech_level");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, battle_action_taken_flag) == 49, "PlayerRuntimeState.battle_action_taken_flag");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, consecutive_idle_battle_turns) == 53, "PlayerRuntimeState.consecutive_idle_battle_turns");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, revealed_tiles_bitset) == 57, "PlayerRuntimeState.revealed_tiles_bitset");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, prisoner_transfer_queue) == 1357, "PlayerRuntimeState.prisoner_transfer_queue");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, queen_relationship_state) == 1419, "PlayerRuntimeState.queen_relationship_state");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, queen_portrait_index) == 1420, "PlayerRuntimeState.queen_portrait_index");
CLASH95_STATIC_ASSERT(offsetof(PlayerRuntimeState, queen_next_relationship_check_turn) == 1421, "PlayerRuntimeState.queen_next_relationship_check_turn");

typedef struct __attribute__((packed)) PortRuntimeState {
  int32_t port_tile_row;
  int32_t port_tile_column;
  int32_t next_reinforcement_turn;
  int32_t reinforcement_ready_flag;
  int32_t pending_reinforcement_unit_count;
  int32_t shoreline_variant_visual_flag;
} PortRuntimeState;
CLASH95_STATIC_ASSERT(sizeof(PortRuntimeState) == 24, "PortRuntimeState size");
CLASH95_STATIC_ASSERT(offsetof(PortRuntimeState, port_tile_row) == 0, "PortRuntimeState.port_tile_row");
CLASH95_STATIC_ASSERT(offsetof(PortRuntimeState, port_tile_column) == 4, "PortRuntimeState.port_tile_column");
CLASH95_STATIC_ASSERT(offsetof(PortRuntimeState, next_reinforcement_turn) == 8, "PortRuntimeState.next_reinforcement_turn");
CLASH95_STATIC_ASSERT(offsetof(PortRuntimeState, reinforcement_ready_flag) == 12, "PortRuntimeState.reinforcement_ready_flag");
CLASH95_STATIC_ASSERT(offsetof(PortRuntimeState, pending_reinforcement_unit_count) == 16, "PortRuntimeState.pending_reinforcement_unit_count");
CLASH95_STATIC_ASSERT(offsetof(PortRuntimeState, shoreline_variant_visual_flag) == 20, "PortRuntimeState.shoreline_variant_visual_flag");

typedef struct __attribute__((packed)) PortSupplyUnitTypePoolEntry {
  int32_t unit_type_id;
} PortSupplyUnitTypePoolEntry;
CLASH95_STATIC_ASSERT(sizeof(PortSupplyUnitTypePoolEntry) == 4, "PortSupplyUnitTypePoolEntry size");
CLASH95_STATIC_ASSERT(offsetof(PortSupplyUnitTypePoolEntry, unit_type_id) == 0, "PortSupplyUnitTypePoolEntry.unit_type_id");

typedef struct __attribute__((packed)) BattleUnitEntry {
  int16_t unit_type_id;
  uint8_t owner_player_index;
  uint8_t facing_direction;
  int16_t grid_x;
  int16_t grid_y;
  uint8_t action_points;
  uint8_t health_percent;
  uint8_t fatigue;
  uint8_t morale;
  uint8_t stance_bits;
  unsigned char unrecovered_0x0D_0x11[4];
  uint8_t anim_frame_and_effect_bits;
  uint32_t last_animation_tick;
  uint8_t battle_state_bits;
  unsigned char unrecovered_0x17_0x1F[8];
} BattleUnitEntry;
CLASH95_STATIC_ASSERT(sizeof(BattleUnitEntry) == 31, "BattleUnitEntry size");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, unit_type_id) == 0, "BattleUnitEntry.unit_type_id");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, owner_player_index) == 2, "BattleUnitEntry.owner_player_index");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, facing_direction) == 3, "BattleUnitEntry.facing_direction");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, grid_x) == 4, "BattleUnitEntry.grid_x");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, grid_y) == 6, "BattleUnitEntry.grid_y");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, action_points) == 8, "BattleUnitEntry.action_points");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, health_percent) == 9, "BattleUnitEntry.health_percent");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, fatigue) == 10, "BattleUnitEntry.fatigue");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, morale) == 11, "BattleUnitEntry.morale");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, stance_bits) == 12, "BattleUnitEntry.stance_bits");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, anim_frame_and_effect_bits) == 17, "BattleUnitEntry.anim_frame_and_effect_bits");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, last_animation_tick) == 18, "BattleUnitEntry.last_animation_tick");
CLASH95_STATIC_ASSERT(offsetof(BattleUnitEntry, battle_state_bits) == 22, "BattleUnitEntry.battle_state_bits");

typedef struct __attribute__((packed)) TooltipBackdropState {
  low32_ptr backdrop_surface;
  int32_t top;
  int32_t left;
  int32_t bottom;
  int32_t right;
  int32_t resource_handle;
  int32_t aux_context;
} TooltipBackdropState;
CLASH95_STATIC_ASSERT(sizeof(TooltipBackdropState) == 28, "TooltipBackdropState size");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, backdrop_surface) == 0, "TooltipBackdropState.backdrop_surface");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, top) == 4, "TooltipBackdropState.top");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, left) == 8, "TooltipBackdropState.left");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, bottom) == 12, "TooltipBackdropState.bottom");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, right) == 16, "TooltipBackdropState.right");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, resource_handle) == 20, "TooltipBackdropState.resource_handle");
CLASH95_STATIC_ASSERT(offsetof(TooltipBackdropState, aux_context) == 24, "TooltipBackdropState.aux_context");

typedef struct __attribute__((packed)) BuildingPrisonerSlot {
  int8_t prisoner_type_id;
  uint8_t captured_owner_player_index;
  uint8_t turns_held;
  uint8_t pending_action;
  uint16_t ransom_value;
} BuildingPrisonerSlot;
CLASH95_STATIC_ASSERT(sizeof(BuildingPrisonerSlot) == 6, "BuildingPrisonerSlot size");
CLASH95_STATIC_ASSERT(offsetof(BuildingPrisonerSlot, prisoner_type_id) == 0, "BuildingPrisonerSlot.prisoner_type_id");
CLASH95_STATIC_ASSERT(offsetof(BuildingPrisonerSlot, captured_owner_player_index) == 1, "BuildingPrisonerSlot.captured_owner_player_index");
CLASH95_STATIC_ASSERT(offsetof(BuildingPrisonerSlot, turns_held) == 2, "BuildingPrisonerSlot.turns_held");
CLASH95_STATIC_ASSERT(offsetof(BuildingPrisonerSlot, pending_action) == 3, "BuildingPrisonerSlot.pending_action");
CLASH95_STATIC_ASSERT(offsetof(BuildingPrisonerSlot, ransom_value) == 4, "BuildingPrisonerSlot.ransom_value");

typedef struct __attribute__((packed)) MergedTerrainMoveProfile {
  uint8_t road_or_bridge_move_cost;
  uint8_t world_surface_move_costs[8];
} MergedTerrainMoveProfile;
CLASH95_STATIC_ASSERT(sizeof(MergedTerrainMoveProfile) == 9, "MergedTerrainMoveProfile size");
CLASH95_STATIC_ASSERT(offsetof(MergedTerrainMoveProfile, road_or_bridge_move_cost) == 0, "MergedTerrainMoveProfile.road_or_bridge_move_cost");
CLASH95_STATIC_ASSERT(offsetof(MergedTerrainMoveProfile, world_surface_move_costs) == 1, "MergedTerrainMoveProfile.world_surface_move_costs");

typedef struct __attribute__((packed)) WorldMapActionWidgetRecord {
  int32_t left_x;
  int32_t top_y;
  int32_t widget_flags;
  low32_ptr sprite_set_handle_holder_low32;
  int32_t default_sprite_index;
  int32_t alternate_sprite_index;
  int32_t overlay_sprite_index;
  low32_ptr transition_callback_low32;
  low32_ptr action_callback_low32;
  low32_ptr localized_label_pl_low32;
  low32_ptr localized_label_en_low32;
  low32_ptr localized_label_de_low32;
  uint8_t label_or_sound_flag;
  low32_ptr ui_sound_name_low32;
} WorldMapActionWidgetRecord;
CLASH95_STATIC_ASSERT(sizeof(WorldMapActionWidgetRecord) == 53, "WorldMapActionWidgetRecord size");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, left_x) == 0, "WorldMapActionWidgetRecord.left_x");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, top_y) == 4, "WorldMapActionWidgetRecord.top_y");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, widget_flags) == 8, "WorldMapActionWidgetRecord.widget_flags");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, sprite_set_handle_holder_low32) == 12, "WorldMapActionWidgetRecord.sprite_set_handle_holder_low32");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, default_sprite_index) == 16, "WorldMapActionWidgetRecord.default_sprite_index");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, alternate_sprite_index) == 20, "WorldMapActionWidgetRecord.alternate_sprite_index");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, overlay_sprite_index) == 24, "WorldMapActionWidgetRecord.overlay_sprite_index");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, transition_callback_low32) == 28, "WorldMapActionWidgetRecord.transition_callback_low32");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, action_callback_low32) == 32, "WorldMapActionWidgetRecord.action_callback_low32");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, localized_label_pl_low32) == 36, "WorldMapActionWidgetRecord.localized_label_pl_low32");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, localized_label_en_low32) == 40, "WorldMapActionWidgetRecord.localized_label_en_low32");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, localized_label_de_low32) == 44, "WorldMapActionWidgetRecord.localized_label_de_low32");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, label_or_sound_flag) == 48, "WorldMapActionWidgetRecord.label_or_sound_flag");
CLASH95_STATIC_ASSERT(offsetof(WorldMapActionWidgetRecord, ui_sound_name_low32) == 49, "WorldMapActionWidgetRecord.ui_sound_name_low32");

typedef struct __attribute__((packed)) BuildingEconomyDialogWidgetRecordTable {
  int32_t left;
  int32_t top;
  int32_t state_flags;
  low32_ptr sprite_set_holder;
  int32_t normal_sprite_id;
  int32_t hover_sprite_id;
  int32_t extra_sprite_id;
  low32_ptr transition_callback;
  low32_ptr action_callback;
  low32_ptr label_pl;
  low32_ptr label_en;
  low32_ptr label_de;
  uint8_t tooltip_mode;
  low32_ptr sound_name;
} BuildingEconomyDialogWidgetRecordTable;
CLASH95_STATIC_ASSERT(sizeof(BuildingEconomyDialogWidgetRecordTable) == 53, "BuildingEconomyDialogWidgetRecordTable size");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, left) == 0, "BuildingEconomyDialogWidgetRecordTable.left");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, top) == 4, "BuildingEconomyDialogWidgetRecordTable.top");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, state_flags) == 8, "BuildingEconomyDialogWidgetRecordTable.state_flags");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, sprite_set_holder) == 12, "BuildingEconomyDialogWidgetRecordTable.sprite_set_holder");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, normal_sprite_id) == 16, "BuildingEconomyDialogWidgetRecordTable.normal_sprite_id");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, hover_sprite_id) == 20, "BuildingEconomyDialogWidgetRecordTable.hover_sprite_id");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, extra_sprite_id) == 24, "BuildingEconomyDialogWidgetRecordTable.extra_sprite_id");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, transition_callback) == 28, "BuildingEconomyDialogWidgetRecordTable.transition_callback");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, action_callback) == 32, "BuildingEconomyDialogWidgetRecordTable.action_callback");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, label_pl) == 36, "BuildingEconomyDialogWidgetRecordTable.label_pl");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, label_en) == 40, "BuildingEconomyDialogWidgetRecordTable.label_en");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, label_de) == 44, "BuildingEconomyDialogWidgetRecordTable.label_de");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, tooltip_mode) == 48, "BuildingEconomyDialogWidgetRecordTable.tooltip_mode");
CLASH95_STATIC_ASSERT(offsetof(BuildingEconomyDialogWidgetRecordTable, sound_name) == 49, "BuildingEconomyDialogWidgetRecordTable.sound_name");

typedef struct __attribute__((packed)) BuildingTransferTargetList {
  int16_t target_building_index_or_sentinel;
} BuildingTransferTargetList;
CLASH95_STATIC_ASSERT(sizeof(BuildingTransferTargetList) == 2, "BuildingTransferTargetList size");
CLASH95_STATIC_ASSERT(offsetof(BuildingTransferTargetList, target_building_index_or_sentinel) == 0, "BuildingTransferTargetList.target_building_index_or_sentinel");
#endif
