/* GENERATED by tools/gen_pure_decls.py. */
#ifndef CLASH95_PURE_DECLS_H
#define CLASH95_PURE_DECLS_H

/* CLASH95_TESTING must be defined by the coverage object-library target so
 * only explicitly frozen helpers marked CLASH95_TEST_VISIBLE lose static
 * linkage in test builds. */
#include "../../src/recovered/split/recovered_internal.h"

#endif
