/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/media/0046B610_0046E5D0_media_005.cpp' (2); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0046B610_0046E5D0_MEDIA_005_LOCAL_H
#define CLASH95_TU_0046B610_0046E5D0_MEDIA_005_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL int Audio_MixVoiceSpanDispatch_46BB40(signed int stepFixed, int sampleCount, char accumFlag, void *accumBuffer) CLASH95_LOCAL_SYMBOL(Audio_MixVoiceSpanDispatch_46BB40);
CLASH95_LOCAL unsigned int Audio_MixVoiceSpanDispatch_46BB9A(
        unsigned int result,
        signed int stepFixed,
        unsigned int sampleCount,
        __int16 volumeAndFlag,
        void *accumBuffer) CLASH95_LOCAL_SYMBOL(Audio_MixVoiceSpanDispatch_46BB9A);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0046B610_0046E5D0_MEDIA_005_LOCAL_H */
