/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/media/004735F0_00475080_media_009.cpp' (3); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_004735F0_00475080_MEDIA_009_LOCAL_H
#define CLASH95_TU_004735F0_00475080_MEDIA_009_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL _DWORD *Compat_FileSystemQueryOpen(int file_system, int mode_flags) CLASH95_LOCAL_SYMBOL(Compat_FileSystemQueryOpen);
CLASH95_LOCAL int Compat_FileSystemQueryResultIsReady(_DWORD *opened_query) CLASH95_LOCAL_SYMBOL(Compat_FileSystemQueryResultIsReady);
CLASH95_TEST_VISIBLE void Compat_FileSystemQueryResultRelease (_DWORD *opened_query) CLASH95_LOCAL_SYMBOL(Compat_FileSystemQueryResultRelease);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_004735F0_00475080_MEDIA_009_LOCAL_H */
