/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/media/00471C60_00473570_media_008.cpp' (2); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_00471C60_00473570_MEDIA_008_LOCAL_H
#define CLASH95_TU_00471C60_00473570_MEDIA_008_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_TEST_VISIBLE void Compat_StringHolderAssignJoined (_DWORD *holder, const char *prefix, const char *suffix) CLASH95_LOCAL_SYMBOL(Compat_StringHolderAssignJoined);
CLASH95_TEST_VISIBLE void Compat_StringHolderInsertText (_DWORD *holder, int index, const char *inserted_text) CLASH95_LOCAL_SYMBOL(Compat_StringHolderInsertText);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_00471C60_00473570_MEDIA_008_LOCAL_H */
