/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Own-TU declarations for 'src/media/0047AA90_0047C760_media_013.cpp' (1); never included by another TU or the aggregate. */
#ifndef CLASH95_TU_0047AA90_0047C760_MEDIA_013_LOCAL_H
#define CLASH95_TU_0047AA90_0047C760_MEDIA_013_LOCAL_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

CLASH95_LOCAL int InputBackend_ScaleHostMouseDeltaToRecoveredUnits(int render_state, int host_delta) CLASH95_LOCAL_SYMBOL(InputBackend_ScaleHostMouseDeltaToRecoveredUnits);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_TU_0047AA90_0047C760_MEDIA_013_LOCAL_H */
