/* GENERATED by tools/gen_subsystem_headers.py -- do not edit. */
/* Shared state-TU globals consumed by 'media' (73); declarations only, private to this consuming subsystem. */
#ifndef CLASH95_MEDIA_SHARED_STATE_H
#define CLASH95_MEDIA_SHARED_STATE_H

#include "../recovered_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern char IsTable[256];
extern char a1[3];
extern char a10[3];
extern char a11[3];
extern char a12[3];
extern char a2[3];
extern char aActivations[12];
extern char aArgacces[9];
extern char aClass[6];
extern char aCompilations[13];
extern char aExpectedAtLeas[20];
extern char aFacts_0[6];
extern char aFunction[10];
extern char aFunctionParser[60];
extern char aInitSlots[11];
extern int g_BinaryItemListHead;
extern int (__thiscall *g_CRT_FileHandleLockAcquireHook)(_DWORD);
extern int (__fastcall *g_CRT_FileHandleLockReleaseHook)(_DWORD, _DWORD);
extern _UNKNOWN g_CRT_StdoutStream;
extern int g_ClipsCommandEvalInProgress;
extern int g_ClipsCurrentEvaluationDepth;
extern int g_ClipsCurrentExpression;
extern int g_ClipsDeleteMessageSymbol;
extern int g_ClipsEphemeralItemBytes;
extern int g_ClipsEphemeralItemCount;
extern int g_ClipsEvaluationError;
extern int g_ClipsFalseSymbol;
extern int g_ClipsHaltExecution;
extern __int64 g_ClipsHaltExecutionFlag;
extern int g_ClipsMemFreeListTemp;
extern int g_ClipsMemPoolReturnBucketIndex;
extern int g_ClipsMemoryTable;
extern int g_ClipsPrimitiveTypeClassMap[1];
extern int g_Clips_CurrentPartialMatch;
extern int g_Clips_InstanceListHead;
extern int g_CompatStringHolder_Vtable;
extern _DWORD g_CrtThreadDataMgmtDisabledFlag;
extern char g_CursorCoordShift;
extern int g_DefruleConstructClass;
extern int g_FileSystemMountOpenMode;
extern char *g_IO_LogicalNameTable_WDialog[3];
extern char *g_IO_LogicalNameTable_WError[5];
extern char *g_IO_LogicalNameTable_WTrace[4];
extern char *g_IO_LogicalName_WDisplay;
extern int g_Instance_PurgeInProgress;
extern int g_Module_ChangeGeneration;
extern int g_PathEntryArray_Vtable[2];
extern int g_PathEntry_Vtable;
extern int g_Print_AddressesToStringsFlag;
extern int g_Print_InstanceAddressesToNamesFlag;
extern int g_Print_PreserveEscapedCharactersFlag;
extern _DWORD g_RenderState[286];
extern int g_Rules_ActiveInstanceCount;
extern void *g_Rules_BloadFileHeaderID;
extern int g_Rules_BloadFunctionPtrTable;
extern char *g_Rules_BsaveVersionID;
extern int g_Rules_ClearInProgressFlag;
extern int g_Rules_CurrentLogicalJoin;
extern int g_Rules_CurrentlyExecutingRule;
extern void *g_Rules_DummyFactPtr;
extern int g_Rules_EntityTimeTagCounter;
extern _DWORD g_Rules_FactPatternEntityRecord[15];
extern int g_Rules_GlobalRHSBinds;
extern int g_Rules_JoinOperationInProgress;
extern _DWORD g_Rules_ObjectPatternVTable[15];
extern int g_Rules_ResetInProgressFlag;
extern int g_Rules_WatchActivationsFlag;
extern int g_Rules_WatchFactsFlag;
extern int g_SelectedUnitIndex;
extern HANDLE hThread;

/* Deliberate unprototyped residue: recovered call sites depend on K&R semantics
 * (varying arity) or the slot type is unrecovered; kept verbatim as provenance. */
#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
#endif
extern _DWORD (*g_CRT_StaticLock1AcquireHook)();
extern _DWORD (*g_CRT_StaticLock1ReleaseHook)();
extern _DWORD (*g_CRT_TlsIndexDestroyHook)();
#if !defined(__cplusplus) && (defined(__GNUC__) || defined(__clang__))
#pragma GCC diagnostic pop
#endif

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CLASH95_MEDIA_SHARED_STATE_H */
